### ISSUE TITLE
V² Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#1]
![v2-home-hack](https://cloud.githubusercontent.com/assets/7278716/13603081/a431886e-e575-11e5-81c9-e87ee34d45c8.png)
# Layout

Please see a hacked version in the image above or

Follow the Layout of the Hero Page: → http://square.github.io/
# Content►Header
## Title Line
- **Left:** Phoenix Squared Logo — Modular PC Open Source Initiative 
- **Right:** github.com/v-squared
## Tagline (centered)

Community Projects for modular and upgradable Mini and All-In-One PC & Workstation
## Table of Contents

(centered, links listed in one line, separated by hyphens)

For Maker - For DIY - Products - Social Media - Marketing - Organization - Misc
# Content►Body
## For Makers

_Standards, Blueprints & Development Kits_
### V²Case

Modular, scalable, quiet, Mini-PC Case for Desktop Parts with standardized Accessories. **Maker Docu:** Standards, Blueprints, Development Kits, Developer Stories, User Stories
### V²Accessories

Standardized Accessories for V²Case: V²Feet, V²Bracket, V²Access, V²Control, V²Color, V²Duino, V²Cooler, V²Parallel. **Maker Docu:** Standards, Blueprints, Development Kits, Developer Stories, User Stories
### V²PC

Ready made PC Configurations ranging from Entry Level to High End. Covering custom configurations for Personal Use, Game PC and Workstations. **Maker Docu:** Standards, Blueprints, Development Kits, Developer Stories, User Stories
### V²Bare

Ready made Bare Bone Configurations. 3L, 6L and 9L Models.  **Maker Docu:** Standards, Blueprints, Development Kits, Developer Stories, User Stories
### V²Panel

PC I/O Panel with Remote Power On, 4 USB Ports, Head Set Ports, Arduino compatible MCU for extensive Fan and RGB Lights Control.  **Maker Docu:** Standards, Blueprints, Development Kits, Developer Stories, User Stories
### V²Dock

Boost your V²PC with a docked GPU or 4 RAID Disks. Data Rates up to 4000 MB/s.  **Maker Docu:** Standards, Blueprints, Development Kits, Developer Stories, User Stories
## For DIY

_PC Know How & Tools_
### V²Configurator

PC Configurator Web App. Easy to use. Elegant UI. Pick a V²Configuration as your base config and then customize to your needs. Your custom Configuration can be easily shared in Forums, emails, etc to get feedback.
### V² How to DIY Mini PC

How-to Articles on custom building your own DIY Mini or All-In-One Computer 
### V²Base.Compatibility

V² Compatibility Web App
## Trailblazer Products

_V² Standards turned into real Products_
### ViCase

Modular, scalable, quiet, Mini-PC Case for Desktop Parts with standardized Accessories. **Buyer Info:** Features, Models, Use
### ViAccessories

Accessories made by Village Tronic for any V²Case such as ViCase: ViFeet, ViBracket, ViAccess, ViControl, ViColor, ViDuino, ViCooler, ViParallel. **Buyer Info:** Models & Features, Use
### ViPC

Ready build custom PCs ranging from Entry Level to High End based on V²PC configurations. Covering custom configurations for Personal Use, Game PC and Workstations. Build with ViCase. **Buyer Info:** Features, Models, Use
### ViBare

Ready build Bare Bone PCs build with ViCase. 3L, 6L and 9L models with V²Bare feature set.  **Buyer Info:** Features, Models, Use
### ViPanel

PC I/O Panel with Remote Power On, 4 USB Ports, Head Set Ports, Arduino compatible MCU for extensive Fan and RGB Lights Control. V²Case or ATX Case options.  **Buyer Info:** Features, Models, Use
### ViDock

Boost your V²PC with a docked GPU or 4 RAID Disks. Data Rates up to 4000 MB/s.  **Buyer Info:** Features, Models, Use
# Social Media

_The easiest way to get in contact with us_
## Facebook

The birthplace of this Community. It all started on the VillageViDock Facebook Page. Started in 2009 as Village ViDock
## YouTube

Where we publish our Videos or relevant Videos made by community members. Started in 2012.
## Twitter

We are new on Twitter. But intend to make our presence a great one with your help!
# Marketing
## Community Promotions

Crowd Funding Campaigns with discounts and stretch goal bonus.
## Shops

Listing of all shops selling V² Products
## Milestones

**True North** describes how it looks when we accomplish our **Mission**. **Strategy** is how go about it in activities reaching **Stages** and **Milestones**.
## Organization

_About the people, process and legal stuff creating the V² Open Standards_
### About

History, Mission, Board, Operations, Bylaws, Logo, License, Open Standard
### Contributing

Fix Bugs, Projects in search of Owner, Workflows, Joining ongoing Projects, Become a member.
### Blog

News, Incubating Articles, Public Brainstorming
## Misc

_Other stuff that did not fit above_
### v2-Videogular-SingleStep

Videogular Plugin to single step frame by frame in a video. Forward and backwards. 
### v2-Video-Active

Interactive HTML5 Angular Video Player made with Angular.
### v2-Slide

Powerful Slideshow Plugin made with Angular.
### V²Art

About all artwork used in V² Projects. Concepts, source files, finished images and illustrations,  visual style guides & visual workflows.
### V²Docu

About writing consistently and efficient. 
### V²Contribution

Workflow and Tutorials on how to contribute to V²
### V²Site

Research and Know How on Workflow and Coding of websites for V². 
# Tasks
- [x] @LukasChen: Install Jekyll. Make yourself familiar with it
- [x] @VillageHubertChen: Find Hero Home Page  → http://square.github.io/
- [x] @VillageHubertChen: Write initial draft of Home Page
- [x] @VillageHubertChen: Review by SL → Development Kits must be listed under Maker!
- [x] @LukasChen: Research Best way to Page Layout in 2016 in V-Squared/v2-Site#2
- [x] @VillageHubertChen: Finalize writing of Home Page
- [x] @bcaswelch   Review
- [x] @VillageHubertChen: Research: Best way to build website for V² in V-Squared/v2-Site#1
- [x] @LukasChen: Create first Version of Home Page as per above description, then trigger HC for review
- [x] @VillageHubertChen: Review first Version of Home Page. Write change list for LC

**Comment by VillageHubertChen** [comment]
I published final proposal in first comment.

**Comment by VillageHubertChen** [comment]
Added to specs:
- Add Organization:  1) About 2) Contributing 3) Blog
- Change Hero Products → Trailblazer Products

**Comment by VillageHubertChen** [comment]
## Useful Reference for writing on the Standard part later:

### Open Source
- https://opensource.org/
- http://www.oshwa.org/definition/
- https://opensource.org/osr

### About us → https://opensource.org/about
- History
- Board
- Trademark & Logo

**Comment by VillageHubertChen** [comment]
Updated a hacked version of the Hero Page in Card.

**Comment by VillageHubertChen** [comment]
# Added Campaigns

Since we now want to push a ViCase campaign we added it to Home Page.
→ V-Squared/v2-How-to-Online-Shop#6

**Comment by VillageHubertChen** [comment]
# Streamlined Section Titles

Restructured the previous sections: "Community & Shops" and "Marketing & Plans". This become necessary after adding Campaigns.

**Comment by VillageHubertChen** [comment]
# Rapid Prototyping Page

https://v2homepage-old-lukaschen.c9users.io/

**Comment by VillageHubertChen** [comment]
# First Version is up
- http://v-squared.github.io/
- **Finished:** Layout, Animation, Testing on all devices, Text, Table of Contents
- **Working On:** Images, Restructuring of Repositories, Links to Repositories

**Comment by VillageHubertChen** [comment]
# Usability Reports

We tested on many devices, OS, browsers and screen sizes. As long as the browser is not too outdated it all worked fine. Sascha especially liked that tapping the images showed additional text, when using is Windows 10 mobile. He could use it with one hand. Also testing on Android 4 with one year old browser as well as iPhone 4 showed the site worked fine.

**Comment by VillageHubertChen** [comment]
The Initial V²Home Page is working and published now. To complete this project → #2 , #3 , #5 , #6

As such this Issue can be closed now :-)

**Comment by VillageHubertChen** [comment]
# Reference Information on Transitions
- http://getuikit.com/docs/overlay.html#overlay-transitions
- For the text scrolling in on hover over square image
