### ISSUE TITLE
Add Abstract to Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#10]
# First Draft of Abstract

This is an Open Source, Non-Profit Organization on GitHub that creates, compiles and catalogs projects, know-how articles, standards, blue prints and applications for the purpose to make Mini and All-In-One Computer modular and ugradable. For the benefit of the individual DIY person as well as the Industry as a whole. We have published what we have under CC and MIT License and we are working on closing all holes. Since this is Open Source, you are invited to help. Or simply use what is already available. Pay attention to the Progress batches.
# Order of Placement
1. Heading
2. Abstract
3. Horizontal Rule (page width only, not window width)
4. Table of Content
# Layout
- centered
- nice font attributes (check other sites which are doing same thing on what they do)
# Tasks
- [x] HC: Write with GI the initial Draft of Abstract
- [x] HC: Improve writing of Abstract
- [x] @LukasChen publish on [V² Home Page](http://v-squared.github.io/), trigger HC for review
- [x] HC: Review Lukas implementation on [V² Home Page](http://v-squared.github.io/)
