### ISSUE TITLE
Rendering all Images for V²Plan Board and Slide

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#102]
- [x] HC: Create List of Images
- [x] HC: Create description of Images
- [x] ML: Design Images, then take snap shot with real view of preview, whatever is faster and looks good enough
# List of Images that need Rendering
## Spreading
- [x] Snap
- Filename: Spreading.png
- 2 x Phoenix
- one with price on sale
- loud speaker
## Target
- [x] Snap
- Filename: Target.png
- Phoenix + Compass
- https://grabcad.com/library/compass-16
## Road Map
- [x] Snap
- Filename: Road-Map.png
- Phoenix + Map
- Map Image: →  \MINI-PC\Users\Mini\Documents\Marketing\v2-Site\Snaps\Road-Map
## Dashboard
- [x] Snap
- Filename: Dashboard.png
- Phoenix in Car or in Airplane cockpit, in front of dashboard
- https://grabcad.com/library/millennium-falcon-cockpit-console-dashbaord-full-detail ←
## Campaign 1 V²Site
- [x] Snap
- Filename: v-sqaured-site.png
- Phoenix 1: right side with hammer
- Phoenix 2: On top
- Phoenix 3: Left side behind, doing something. Mostly the Phoenix is covered by .com

![](http://www.ojornalista.com/wp-content/uploads/2012/06/criar_site.jpg)
## Campaign 2 Community
- [x] Snap
- Filename: v-squared-community.png
  ![](http://synergycommunity.com/wp-content/uploads/2013/09/community-178148.jpg)
- About 10 people, all same shape, but different color. Pick colors with color picker from this image
- place one or two Phoenix into the community
- People and Phoenix have same height and thickness
- People as silhouette outlines with 3d thickness same style as Phoenix will become our style
## Campaign 3 Shop & Press
- [x] Snap
- Filename: v-squared-shop.png
- Phoenix behind the counter
- Shop name: V²Shop on counter or on wall behind counter
- ViCase Mini on top of counter
- https://grabcad.com/library/bar-with-history-1
- https://grabcad.com/library/shop-7
- https://grabcad.com/library/jewellery-shop-1
## Contributing
- [x] Snap
- Filename: Contributing.png
- ![](http://springhillnow.com/wp-content/uploads/2012/03/build-community.jpg)
- All 4 puzzle pieces are very dark gray, almost block, surface satin plastic black
  - they symbolize V²Case
- Separation lines of 3 assembled puzzle pieces visible due to reflection of bevel
- 4 community people helping to put it together. Same colors for people as community image.
  - Outline as per hand drawing
  - People and Phoenix have same height and thickness
# Images to Location Assignments
## Plan Slide in Home Page
- **Size:** 360s = 360 x 360 px
1. Target-360s.jpg
2. Road-Map-360s.jpg
3. Dashboard-360s.jpg
4. v-sqaured-site-360.jpg
5. v-squared-community-360s.jpg
6. v-squared-shop-press-360s.jpg
# Reference
- `\\MINI-PC\Users\Mini\Documents\Marketing\v2-Site\Snaps` (Folder with snaps so far)
