### ISSUE TITLE
Epic►003►Move Plan Articles to V-Squared.github.io

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#106]
- [x] HC: Find article → [Building a Big Web Site on GitHub](#issuecomment-217838186)
- [x] HC: Update article with latest changes and impacts of this issue
- [x] HC: Add cross link to this issue, give it subtitle on why
- [x] HC: Write → Why to move Plan Articles to V-Squared.github.io Repository → below
- [x] HC: Write → Order of Content Development → below
- [x] HC: Document Page / Folder Structure for
  -  V²►Products → #113 
  -  V²►Plan → #78 
  -  V²►Organization → #80 
  -  V²►Spreading → #82 
- [x] @bcaswelch OK or ECR: → OK
  - → Why to move Plan Articles to V-Squared.github.io Repository → below
  - → Order of Content Development → below
- [x] @bcaswelch OK or ECR: → OK
  -  V²►Products → #113 
  -  V²►Plan → #78 
  -  V²►Organization → #80 
  -  V²►Spreading → #82 
- [x] @LukasChen  OK or ECR: → OK
  -  V²►Products → #113 
  -  V²►Plan → #78 
  -  V²►Organization → #80 
  -  V²►Spreading → #82 
- [x] LC, HC: Write → [All steps: Plan → V-Squared.github.io](#issuecomment-222887943)
- [x] LC: Write → [New Jekyll Folder Structure](#issuecomment-222888311)
  - [x] Use same format as HC used in above Page Structure Issues
    - Use editor with fixed font to develop and when finished paste in above comment
  - [x] Trigger HC for review
- [x] LC: Research on the [Made mistakes Jekyll theme](https://mademistakes.com/work/jekyll-themes/) jekyll structure
- [x] HC: Announce to everybody to stop making updates to articles until further notice
- [x] LC: Restructure the V²Plan Repository
- [x] LC: Move V²Plan Code to V-Squared.github.io repository
- [x] LC: Test all is working
# Why to move Plan Articles to V-Squared.github.io Repository
## Avoid redundancy of Jekyll Code

The structure of our web site before this issue has one repository for each _Board_ (V²Site is using a _Library Shelf Metaphor_. The top level sections of our site are called _Boards_). This had advantages when we started. But now that we are using Jekyll we realize that Jekyll can not cleanly support this structure. It would lead to duplicating code nine times for nine boards, which is a developer's night mare. As such we need to consolidate all nine board repositories into one, which is V-Squared.github.io.
## Increase Contribution Statistics

We are are an Open Source Project on GitHub who benefit from contributors. The first thing many contributors do when evaluating a project on GitHub is to check out:  [Graphs](https://github.com/V-Squared/V-Squared.github.io/graphs/contributors) and [Pulse](https://github.com/V-Squared/V-Squared.github.io/pulse). Before this restructure our statistics looked like we are not active, because all our work happened in the other nine repositories. After this consolidation our statistics will look much more alive, as such much more attractive to potential contributors.
# Order of Content Development
## S1: V²Plan

Our focus is to gain speed and we are doing this by adding contributors. We just added 3 more contributors this week: Bobby, Tom and Karen. In order to continue working together we need:
1. Clear description of our _Targets_
2. A clear _Road Map_ how to reach these _Targets_
3. A _Dashboard_ that is managing our _Sprints_
4. A _System_ that makes using all of the above consistent
5. _Documentation_ on how to use all of the above

[V²Plan](https://v-squared.github.io/v2-Plan/) delivers all of the above.
## S2: Spreading

Bobby's first work is to write the DIY and Configuration Articles. They are located in the _Spreading_ Board. To provide him the necessary tools to work we have to finish this _Board_ ASAP.
## S3: Products

The V² _Products_ Board is the incubation chamber for product pages used in our _ViSite_ as well as _V²Shop-Midwest_. Currently we are building a lot of documentation technical debt, marked by labels: _o.debt.docu_ . Once we have the Products Board ready, we can instantly move documentation to there without creating more technical debt
## S4: Organization

Potential V² contributors as well as potential V²Shop customers checking us out will also want to learn more about us. This is published in the Board _Organization_.

**Comment by VillageHubertChen** [comment]
# All steps: Plan → V-Squared.github.io
- [x] request anyone to stop contributing to V²Plan for today
- [x] Pull the entire code repository of v2-Plan
- [x] Move the entire code entry to V-Squared.github.io repository
- [x] resolve any identical folder conflicts.
  - [x] If you do not know how to resolve or takes longer than 30 minutes talk to HC
- [x] upgrade board-bar.yml file to contain the board jumbotron content. Use same method and code then with same feature for book-bar.yml file and book jumbotron
- [x] host on your developer machine, test it. Solve any problems.
  - [x] If you do not know how to resolve or takes longer than 30 minutes talk to HC
- [x] Trigger HC to test on your machine
- [x] Push new unified version to GitHub

**Comment by VillageHubertChen** [comment]
# New Jekyll Folder Structure

```
v-squared.github.io
  ├ _data
  │   ├ boardBar.yml
  │   ├ standards-bookBar.yml
  │   ├ products-bookBar.yml
  │   ┊
  │   ├ organization-bookBar.yml
  │   └ repository.json (List of all repositories, used in home page and in footer for every page)
  │
  ├ _includes
  │   ├ article-bar.html
  │   ├ contents-bar.html
  │   ├ footer.html
  │   ├ head.html (HTML head)
  │   ├ board-bar.html
  │   └ book-bar.html
  │
  ├ _javascript
  │   ├ controllers
  │   ├ dependencies
  │   └ directives
  │
  ├ _layouts
  │   ├ default.html
  │   ├ home.html
  │   ├ page.html
  │   └ post.html
  │
  ├ _post (contains all blog posts)
  │   ┊
  ├ _sass
  │   ┊
  ├ css
  │   ┊
  ├ fonts
  │   ┊
  ├ icons
  │   ┊
  ├ standards (board folder)
  │   ┊
  ├ products (board folder)
  │   ┊
  ├ makers (board folder)
  │   ┊
  ├ diy (board folder)
  │   ┊
  ├ retail (board folder)
  │   ┊
  ├ spreading (board folder)
  │   ┊
  ├ apps (board folder)
  │   ┊
  ├ Plan  (board folder)
  │   ├ system (book folder)
  │   ├ road-map (book folder)
  │   ├ contributing.md (article on book level)
  │   ├ dashboard.md (article on book level)
  │   ├ target.md (article on book level)
  │   ├ system.md (Intro Article to series in System Book)
  │   ├ road-map.md (Intro Article to series in Road Map Book)
  │   └ index.md (Intro Article to Plan Board)
  │
  ├ organization
  ├ _config.yml (Global configuration of this site, such as site name, etc ...)
  ├ feed.xml
  ├ README.md
  ├ .gitognore
  └ index.html
```

**Comment by LukasChen** [comment]
# Problems of moving v-squared.github.io

## Everything in intro is in the index.html file
