### ISSUE TITLE
Add Navigation Bar v1

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#11]
# Toolbar Menu Items
- V² Logo -> Home
- For Maker
- For DIY
- Products
- Social Media
- Marketing
- Organization
- Misc
# Placement / Layout Changes
- Top of Page
# Integration of Menu Bar with existing page
1. Implement #10 (Add Abstract to Home Page) first
2. Place Toolbar
3. We experience the page and we discuss how to go from here
# Breadcrumbs

In the final design we should find a place for breadcrumbs
# Proposed Site Structure
- Sections of Home Page / Table of Contents also becomes an entry in the navigation bar
- Each section gets its own repository
  - It contains the Section's web site
  - It may contain all section's articles, in case know how articles are the content of this section
    - Examples: "Marketing" and "Organization" sections 
  - If the section has many projects, then each project will get its own project repository
  - The section repository contains a directory entry for each related project repository
  - The directory entry links to the project repository
- Each sections repository gets its own gh-pages with:
  - It's own Jekyll
  - It's own Article pages
  - But the Menu Bar and Footer are pulled from gh-pages of v-squared.github.io
# Tasks
- [x] HC: Develop V²Site's structure and navigation bar
- [x] HC: Get Sascha's feedback → OK
- [x] HC: Get Lukas' feedback → OK
- [x] @LukasChen Make first Implementation, then trigger HC for review
