### ISSUE TITLE
Board Structure: V² > Products

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#113]
# Tasks
- [x] Move → [Page Structure Production](https://github.com/V-Squared/v2-Production/issues/2) from v2-Production to this repository to match new structure
- [x] Write → Additional Information on Content in Production (below)
- [x] Fill in remaining Page Structure of Board "Products". Keep it consistent with the 6 tiles in the Production Slide Show on the Home Page
- [x] Mark Pages needed for Milestone: V²►Products Start
## Debt Docu
- Create a Page about Page Structure for V²Site
- Place it → V²►Spreading►Know How►GitHub Template►Site Structure
- Find all Page Structure Pages and copy their content to that page
- Write an Introduction that this is our structure and here for our reference and your inspiration
# Page Structure

```
V² Home Page
     ├ Standards
     ├ Trailblazer Products
     │     │
     │     ├ ViStand
     │     │     ├ Use
     │     │     ├ Features
     │     │     ├ Specs
     │     │     └ Promotion
     │     │
     │     ├ ViCase Mini
     │     │     ├ Use
     │     │     ├ Features
     │     │     ├ Specs
     │     │     └ Promotion
     │     │
     │     ├ ViPC & ViBarebone
     │     │     ├ Use
     │     │     ├ Features
     │     │     ├ Specs
     │     │     ├ Configurations
     │     │     └ Promotion
     │     │
     │     ├ Accessories
     │     │     ├ Intro
     │     │     ├ ViCase-Feet
     │     │     ├ ViCase-Bracket
     │     │     ├ ViCase-Access
     │     │     ├ ViCase-Stand
     │     │     ├ ViCase-Lights
     │     │     ├ ViCase-Remote
     │     │     ├ ViCooler-L 
     │     │     ├ ViCooler-XL
     │     │     └ ViPanel
     │     │
     │     ├ ViDock
     │     │     ├ Intro
     │     │     ├ Specs
     │     │     └ Schedule
     │     │
     │     └ Production
     │           ├ Intro
     │           ├ Quality
     │           ├ Feature Requests
     │           ├ Schedule
     │           ├ Known Issues
     │           ├ Revisions
     │           └ Announcements
     │
     ├ Makers
     ├ DIY
     ┊
```
# Additional Information on Content in Production
## Production Quality

Specifications and Test Procedures of our Production Quality
## Known Issues and Feature Requests

Dealer and customer can open Issues related to production. Such as feature request or quality complaints. We will work with the customer on the issue until resolved. A typical result can be an improvement to the design. Since we make a new production no longer than 4 weeks apart, latest after 4 weeks the new production is out and problem is fixed in shipping product. GitHub issues will serve as ticket system and development and production management system.
## Production Schedule

All production schedule related information is published in Production Web Site (gh-pages) of the v2-Production repository
## Production Announcement

This is the place to make any announcements concerning production, such as when the new version is shipping
## Production Revision Documentation

Every time we make a new production run and a new revision we will document in here for reference. So customer can check which version they have and can look up known problems and complete list of features to this version. Including documentation of the revision numbering system.
## Structure
- V² Home Page
  - V² Production Home Page
    1. Production Quality
    2. Known Issues / Feature Requests
    3. Production Schedule
    4. Production Announcements
    5. Production Revisions

The V² Production Home Page has 4 Cards which link to 4 Articles that contain what is promised on the card.
## Pull relevant information from here

→ [V²►Plan►Production Tile in Product Portfolio ](https://github.com/V-Squared/v2-Plan/issues/23#issuecomment-216100255)
# Reference

Board Structure: V² > Standards #219
Board Structure: V²►Products #113 
Board Structure for V²►Plan #78 
Board Structure of V²►Organization #80 
Board Structure for V²►Spreading #82 
Epic►011►Parent: Board Structure for V²►DIY 2016W23 #122

**Comment by VillageHubertChen** [comment]
# Updated Product Pages ViStand / ViMount / ViAiO

```
 V² Home Page
     ├ Standards
     ├ Trailblazer Products
     │     │
     │     ├ ViStand
     │     │     ├ Intro
     │     │     ├ Features
     │     │     ├ Use
     │     │     ├ Specs
     │     │     ├ Unboxing 
     │     │     ├ Reviews
     │     │     ├ Promotion
     │     │     └ Buy
     │     │
     │     ├ ViMount
     │     │     ├ Intro
     │     │     ├ Features
     │     │     ├ Use
     │     │     ├ Specs
     │     │     ├ Unboxing 
     │     │     ├ Reviews
     │     │     ├ Promotion
     │     │     └ Buy
     │     │
     │     ├ ViAiO
     │     │     ├ Intro
     │     │     ├ Features
     │     │     ├ Use
     │     │     ├ Configurations
     │     │     ├ Unboxing
     │     │     ├ Reviews
     │     │     ├ Promotion
     │     │     └ Buy
     │     │
     │     ├ Accessories
     │     │     ├ Intro
     │     │     ├ ViRemote
     │     │     └ ViStand-Speaker
     │     │
     │     ├ Production
     │     │     ├ Intro
     │     │     ├ Quality
     │     │     ├ Feature Requests
     │     │     ├ Schedule
     │     │     ├ Known Issues
     │     │     ├ Revisions
     │     │     └ Announcements
     │     │
     │     └ Modular, Green & Ethos
     │           ├ Modular
     │           ├ Green
     │           ├ Community
     │           └ Ethos
     │
     ├ Makers
     ├ DIY
     ┊

```

**Comment by VillageHubertChen** [comment]
# First two Articles
- ViStand > Intro (intro.md) (Just place holder text)
- ViStand > Features (features.md) (Content see below)
- [ ] LC: Create the Board
- [ ] LC: Create both Articles
- [x] HC: Strip out the Art Briefs from [02c ViStand Features (Plan B)](https://app.classeur.io/#!/files/2knN4I7TjAHX2E79LN7D)
- [ ] HC: Publish → 02c ViStand Features (Plan B)
- [ ] LC: Make a Quick & Dirty Tabs implementation. Ideally finish before we leave to airport :-)
