### ISSUE TITLE
Add Jumbotron to V² Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#12]
# Adding Jumbotron

With adding Abstract and Navigation Bar the top of the Home Page became to crowded. Adding a Jumbotron will fix that.
# Reordering Sections
## Old Section Order & Section Titles
1. **For Maker** Standards, Blueprints, Development Kits, Developer Stories, User Stories
2. **For DIY** PC Know How & Tools
3. **Trailblazer Products** V² Standards turned into real Products
4. **Social Media** The easiest way to get in contact with us
5. **Marketing** Spreading the Word and Products through Community
6. **Organization** About the people, process and legal stuff creating the V² Open Standards
7. **Misc** All sorts of Projects that did not fit in a above
## New Section Order & Section Titles
1. **Trailblazer Products** Showcase with real products what you can build with V² Standards and Blueprints.
2. **For Maker** Standards, Blueprints, Development Kits, Compliance Tests
3. **For DIY** PC Know How & Tools make building a Custom PC easier.
4. **Social Media** Talk to us and spread the word
5. **Marketing** Spreading the Word and Products through Community
6. **Organization** About the people, process and legal stuff creating the V² Open Standards
7. **Misc** More useful things ...
# Alternate Backgrounds per section
- **Purpose:** Visual separation of Sections
- **Implementation:** Use CSS selector to set background color to every even section
# Add Open Source Compliance Section
## Motivation

To show right at the beginning that we are fully compliant to all Open Source Guidelines. This will motivate contributors to contribute and makers to use our standards and copy our blueprints.
## Title & Tagline
- **Title:** Open Source Compliance
- **Tagline:** Use V² Standards and Copy V² Blueprints with Zero Cost and Zero Worries
## Placement
- Under Jumbotron
## List of Logos and their Tooltips
- **GitHub** We host all projects, web sites and know how on the leading Project Hosting Web Site. Project management is done with its ticketing system "GitHub Issues".
- **Open Source Initiative** V² Initiative is compliant with all Guidelines of the Open Source Initiative. Use V² or contribute to it with confidence.
- **Open Hardware** All our open source hardware projects are compliant to the guidelines of the Open Source Hardware Association and thus earned the Open Source Hardware Logo.
- **MIT** MIT License is the most free to copy license in the Open Source Software world. Copy our designs with confidence for any intended use.
- **CC** Creative Commons License is the most free to copy license in the Open Source Hardware world. Copy our designs with confidence for any intended use.
- **Arduino** The leading Open Source Micro Controller Platform. We use it for advanced embedded functions. Easy to develop and document. Low cost in mass production.
## Hero Design
- **URL:** http://uber.demo.joomlart.com/index.php/blocks/clients
- **Style:** Clients - Image Gray
- **Key Features**
  - gray logo at first
  - hover shows logo with their colors and tool tips as per above
## Workflow
1. LC: First use text as logo place holders. Design the page with the place holder. Once we see how they are used work with HC on final logo adaption
2. HC perform the logo adaption as per above meeting
# Tasks
- [x] HC & LC Initial Brainstorming
- [x] HC write Issue based on Brainstorming
- [x] Reordering Sections
- [x] Create a new Issue for: "Add Open Source Logos"
- [x] @LukasChen First Implementation. Trigger HC for review. Repeat until pass. Then close issue

**Comment by VillageHubertChen** [comment]
# Added Open Source Compliance Section

Upon Lukas' request and demoed hero page, we added the Open Source Compliance Section. See above.

**Comment by VillageHubertChen** [comment]
# Results of first Review:

## Error List:
- [x] LC: New Tagline "Trailblazer Products"
- [x] LC: New Tagline "For Maker"
- [x] LC: New Tagline "For DIY"
- [x] LC: New Tagline "Social Media"
- [x] LC: New Tagline "Marketing"
- [x] LC: New Tagline "Misc"
- [x] LC: Quotes in Tooltip for GitHub was missing

**Comment by LukasChen** [comment]
Done :tada:
