### ISSUE TITLE
Logo Customization

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#120]
# Tasks
- [x] BC: Trigger HC to come up with a customization project
- [x] HC: Write User Stories
- [x] HC: Propose a Price List
- [x] HC: Write Manufacturing Processes
- [x] BC: Give feedback to User Stories in comments. We shall only continue if you guys think you can sell this
- [x] BC: Buy sample material: 1.5 ... 3 mm strong sheet aluminum. Sand blasted, anodized black.
- [x] BC: Create a V²Shop Logo. Let HC know if you need any help. Check with KC which file format she needs
- [x] KC: Engrave the V²Shop Logo onto the Sample Aluminum
- [x] BC: Take a picture and publish in here
- [x] BC: Trigger HC to discuss next steps
- [ ] BC: Get → [Quotation Request](#issuecomment-229880153)
# Target for this sprint

Picture of Laser engraved logo on sample aluminum, sandblasted, anodized, black
# User Stories
## Designer / Photographer / Artist

I am a designer using the ViCase All-In-One for work. I very much appreciate to get a powerful desktop workstation in an All-In-One form factor at Desktop PC pricing. As a designer I need to shop my creations to my customers. All my studio is designed by me and is an expression of my capabilities of a designer to my visiting customers. The stylish ViCase fits perfect in this concept. As such it was the icing on the cake that I could order my ViPC in the V²Shop customized with my Logo engraved. I went all out to engrave it both on ViCase-Access and ViCase Top-Cover.
## Gamer

I am a Gamer who uses ViCase for gaming. I chose it because it is very portable. The Top-Cover customization options were just too tempting to resist. I customized the "Scream" template with my handle on Steam.
## Organization

I am the Purchasing Manager of our Organization. We chose ViCase because it gave us the option to use Designer Workstations at Desktop pricing. We ordered the 50 pcs OEM option. Appearance is very important to our company. The ViCase Design is already very appealing. Being able to engrave our company logo at an affordable price simply put it over the top. The service of the V²Shop is simply wonderful!
# Price List

| Qty | Price | Lead Time | Type |
| :-: | :-: | :-: | :-- |
| 1 | $45 | 1 week | Engraving on Insert |
| 2 | $40 | 1 week | Engraving on Insert |
| 5 | $35 | 1 week | Engraving on Insert |
| 20 | $15 | 5 weeks | Silk Screen Print on Top Cover |
# Manufacturing Processes
## Engraving on Inserts

![](http://www.hd-plex.com/images/product/customization/detailpicture.jpg)

The examples above are engraved with a Laser. Engraving with milling is available too. The advantage of this method is that after engraving the inserts can be brushed and remove burrs and burn marks. We would deliver a special ViCase Top Cover and ViCase Access with insert sockets.
## Engraving directly into Top Cover

Check if you can find a vendor that can do and will look good. I am guessing CNC engraving is possible. I have my doubts on Laser engraving as it shall leave burn marks. Find engraving partners who can tell you what they can do and who can send you samples and quotes.

The second disadvantage is double shipping costs, as you need to contractor shop and they need to return to you. Also shipping cost is higher has the Top-Cover is much bigger than the Logo Insert.
## Silk Screen Printing onto Top Cover

Look, feel and quality will be identical to ViDock. We will use German two component epoxy Marabu Ink with real silver particles. Light fast for > 200 years. Ink is for Street Signs, as such highly light fast. Printed in house. 20 pcs and up will be

**Comment by bcaswelch** [comment]
I'll bring a sample to Full Spectrum Laser (company Karen is with). They have many examples of laser cutting on metal with a very clean finish. 

This is a great idea that I think people will like; between this and the lighting people will have a lot of flexibility in how they present their ViPCs. This is important to many people who want to show off their powerful computer :)

**Comment by VillageHubertChen** [comment]
1. Great. 
2. Take pictures when you are there and publish here, or find pictures on their site and publish here or link to their site. If not too many different samples, publish all, even the ones you think you will not want to use. 
3. Together we will then discuss on how to modify the ViCase design to use them.
4. I am reading between the lines here, but do you confirm now you want to go for the Lase Cut Insert option?

**Comment by bcaswelch** [comment]
Why not a laser cut directly onto the top cover? This will be simpler to manage and make it more personal.

**Comment by VillageHubertChen** [comment]
The answers are in my previous writing: 
1. Higher shipping cost (may not be relevant if using your mothers firm)
   1. Shipping both ways
   2. Larger items
2. Burn marks. Every image of metal after laser cut that I have seen had burn marks. They cleaned it either by sandblasting or brushing. In this case it can not be done, as the top cover is already anodized.

Your next step must be to see a sample of black anodized aluminum that has been laser cut. Check if there are no burn marks or if they can be removed without cosmetic defects. If that is possible and if shipping cost is no issue, than that is a solution.

**Comment by VillageHubertChen** [comment]
Update by talking with Karen: Her company has Laser that can both engrave and cut Aluminum. These are Fiber Laser which leave no burn marks. Since in this case also the transportation cost are not relevant, engraving the customer's logo directly onto either _Top Cover_ or _ViCase-Access_ is all: Looks most elegant, easiest to do, lowest cost. Next step to do is to make samples:

Make a nice V²Shop logo and engrave it, then upload the picture to here.

P.S. I updated the task list in the top comment accordingly

**Comment by VillageHubertChen** [comment]
# Target for this sprint

Picture of Laser engraved logo on sample aluminum, sandblasted, anodized, black

**Comment by bcaswelch** [comment]
Can we go through what kind of sample I should buy? Want to make you I am buying the right aluminium

Edit: disregard this comment.

**Comment by VillageHubertChen** [comment]
The task itself reads:  "Buy sample material: 1.5 ... 3 mm strong sheet aluminum. Sand blasted, anodized black."

This is pretty much all spec you need. Should be available in shops that sell sheet materials or on ebay. It is also possible places like _Home Depot_ have this

**Note:** In the top right of a comment there is a cross. When clicking you will be asked if you want to delete the comment. You can delete all comments of the issue, but not the first one. I was confused why you wrote disregard but let the original comment persist. Let me know I answered all your questions, particularly where to buy the sample.

**Comment by VillageHubertChen** [comment]
@bcaswelch Please report progress. By now you should have: 1) Logo 2) Sample Alu, 3) Sample Laser cut. Please post pictures and answer open questions. Trigger me then in comment.

**Comment by bcaswelch** [comment]
@VillageHubertChen 
@kcaswelch 

![img_20160630_180412998](https://cloud.githubusercontent.com/assets/16950279/16509566/22798614-3ef3-11e6-9787-c776ae6a1671.jpg)

CO2 hobby laser on top, CO2 Pro Laser on bottom. The bottom cut used a different source image and won't be as rough. 

### Pro Series

Faster cuts, does deeper into metal. Expensive

### Hobby Series

Not quite as professional looking, cheap machine cost.

## Conclusion

This won't be a machine we would buy right at the beginning because theres no sales data on how popular custom etching would actually be (and my sister would be using the machine more than we would for a custom shop) but both machines give a nice finish so the option is one to consider.

**Comment by VillageHubertChen** [comment]
# Proposal on how to proceed

@bcaswelch @kcaswelch 

## Feedback
1. Thanks for making the samples
2. If the CO2 hobby laser was using a low resolution file and the pro laser using a high resolution file, then these samples do not offer a means of comparing quality between the two
3. Size: These logos are very big. They are not indicative of real world logo.
   - Typical Standard logo sizes: 60 x 10 mm, 30 x 20 mm, 25 x 25 mm 
     - Each of above logos have about 600 mm² surface area
     - Typical logo has 30% etching are → etching area = 200 m²
   - ViCase has space for logos above.
   - ViCase Access Maximum Logo Size: 15 x 15 mm = 225 ², etched area → 75 mm²
4. Buying or Contracting. At this point this is a no-brainer. Buying a laser is not only initial fixed cost, you also have maintenance cost and time spend on learning how to use. We do not know at this time how many customer will want this service. As such, buying may be a waste of money. Buying will become interesting when you have lots of custom logo etching and your cost of etching in house is lower than contract etching
5. Lowering cost of contract etching:
   - Lower the logo size. See above. Most people will not even want such a big logo for reasons of good taste
   - reconsider inserts
6. What happened to the option to use Karen's company to etch custom logos for you?
7. Is it possible that at least in the beginning Karen's company can sometimes cut logos as a favor until business is picking up?
8. Please get a quote as below:

## Quotation Request
1. Each Logo is of: 600 mm² Logo area with 33% etching area → 200 mm² to be removed.
2. Depth is not important. Less depth = lower cost is fine. All we need is high contrast silver to black
3. Cost in USD.

| Number of Individual Logos | Low Cost Laser | Pro Laser |
| --: | :-: | :-: |
| 1 |  |  |
| 3 |  |  |
| 10 |  |  |

## About Inserts
- We can find ready made inserts here and sell to you at low cost
- We can CNC cut an insert holder for the contracting shop, making placing inserts fast & error free

**Comment by bcaswelch** [comment]
1. R&U, I'll drop by this week and see what kind of quote I could get from them.
2. Probably not as relevant for the professional crowd, but many people like to put designs on their cases, not just a small logo.  Are you planning on limiting the surface area people are able to put their logo on? Or let em have the entire top cover?

**Comment by VillageHubertChen** [comment]
# Quote, Logo Size, Top Cover Design

@bcaswelch 
1. Quote: Let me know once you have it
2. Custom design top cover: This is a good idea. I suggest to treat it as a different product. If have modified the quotation request. See below:

# Updated Quotation Requests

## Quotation Request: "Logo on Top Cover"
1. Work Piece size: 245 x 245 mm
2. Each Logo is of: 600 mm² Logo area with 33% etching area → 200 mm² to be removed.
3. Depth is not important. Less depth = lower cost is fine. All we need is high contrast silver to black
4. Cost in USD.

| Number of Individual Logos | Low Cost Laser | Pro Laser |
| --: | :-: | :-: |
| 1 |  |  |
| 3 |  |  |
| 10 |  |  |

## Quotation Request: "Logo Insert" ← Preferred
1. Work Piece size: 30 x 70 mm aluminum. We will provide it
2. We will provide a Fixture to hold up to 20 logos in one work step
3. You would provide artwork exactly as per their spec, so they could run your artwork without spending time on rework.
4. Each Logo is of: 600 mm² Logo area with 33% etching area → 200 mm² to be removed.
5. Depth is not important. Less depth = lower cost is fine. All we need is high contrast silver to black
6. Cost in USD.
7. We pay return shipping
8. They would keep inventory of inserts in stock
9. Workflow:
   1. They have inserts and fixture in stock
   2. You email new artwork
   3. They cut
   4. They ship with a letter

| Number of Individual Logos | Low Cost Laser | Pro Laser |
| --: | :-: | :-: |
| 1 |  |  |
| 3 |  |  |
| 10 |  |  |

## Quotation Request : "Design"
1. Work Piece size: 245 x 245 mm
2. The whole top cover is laser etched = etching area 245 x 245 mm
3. Etched percentage is either 10% or 30% (Two choices for customer to make their design)

| Number of Individual Logos | Low Cost 10% | Low Cost 30% | Pro Laser 10% | Pro Laser 30% |
| --: | :-: | :-: | :-: | :-: |
| 1 |  |  |  |  |
| 3 |  |  |  |  |
