### ISSUE TITLE
Choosing and Building first ViPC Configuration

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#121]
# Gated by
- [ ] →  Epic►014►Parent: Write Custom PC Configuration Articles #135 
# PSU Options
- Gold Flex ATX 300 W
- 250W HDPlex plus DELL 240W Notebook Brick
# Config
- Update GTX 750 Config from Config Article
- Check out workstation config
- two GPU options: GTX 750 Ti  / K1200
- [x] Build a configuration here in markdown with amazon shopping list
- [ ] Trigger HC for review this evening your time

**Comment by bcaswelch** [comment]
# Tasks
- [x] BC: Create updated config
- [x] HC: Review proposal, create to do list on how to clean up
- [ ] BC, HC: Brainstorm on Base Configuration and Variation Configs for this PC
- [ ] BC: Add Missing Parts as per → below
- [ ] BC: Clean up table as per my example → below
- [ ] HC: Writing an Article on rules how to pick a configuration
- [ ] HC: Create an Article on this in the new DIY Section
- [ ] HC: Compile all writing on Solidworks speed comparison
  - This skype chat
  - HDPLEX Issue
  - Our Comparison Movie on RealView

# Configuration

## Nice table

| Type | URL | Price |
| --: | :-- | --: |
| Motherboard | [MSI Intel Skylake LGA 1151 Mini ITX](https://www.amazon.com/MoBo-MSI-H110I-Pro-AC/dp/B01DT4915S) | $90 |
| CPU | [Intel 6600 i5 3.3ghz](https://www.amazon.com/CPU-I5-6500-FC/dp/B010T6CWI2/) | $235 |
| SSD | [Samsung 850 EVO 250 GB M.2 SSD](https://www.amazon.com/Samsung-850-EVO-250-MZ/dp/B00TGIVZTW/) | $100 |

## Messy table

| Type | URL | Price |
| --: | :-- | --: |
| GPU | [Gigabyte 750ti 2GB Card Half/Height](http://www.amazon.com/Gigabyte-GV-N75TOC-2GL-Graphics-Cards/dp/B00MW8NXAW?ie=UTF8&psc=1&redirect=true&ref_=ox_sc_act_title_5&smid=ATVPDKIKX0DER) | $123 |
| Memory | [Kingston HyperX FURY Black 8GB 2133 DDR4](http://www.amazon.com/Kingston-2133MHz-Non-ECC-Desktop-HX421C14FB/dp/B00TY6A56U?ie=UTF8&psc=1&redirect=true&ref_=ox_sc_act_title_4&smid=ATVPDKIKX0DER) | $40 |
| Power Supply | [HDPLEX 250W DC-ATX Power](http://www.amazon.com/HDPLEX-Hi-Fi-DC-ATX-Supply-16V-24V/dp/B00J3X7RU6?ie=UTF8&psc=1&redirect=true&ref_=ox_sc_act_title_2&smid=A2DZ6EQ0NU9MSE) | $85 |
| Power Brick | [Dell PA-9E 240W External Brick](http://www.amazon.com/Original-PA-9E-Replacement-adapter-Notebook/dp/B00AVMYMUG?ie=UTF8&psc=1&redirect=true&ref_=ox_sc_act_title_3&smid=A3EYD1ZWL7OQ1F) | $45 |

## Example on how to clean up Amazon URLs
- **Before:** http://www.amazon.com/MSI-Motherboard-H110I-Pro-AC/dp/B01DT4915S?ie=UTF8&psc=1&redirect=true&ref_=ox_sc_act_title_6&smid=ATVPDKIKX0DER
- **After:** www.amazon.com/MoBo-MSI-H110I-Pro-AC/dp/B01DT4915S
- **Before2:** http://www.amazon.com/Intel-I5-6500-FC-LGA14C-Processor-BX80662I56500/dp/B010T6CWI2/ref=lp_2529650011_1_1?srs=2529650011&ie=UTF8&qid=1464922790&sr=8-1
- **After2:** https://www.amazon.com/CPU-I5-6500-FC/dp/B010T6CWI2/
- Rules:
  - You delete everything after the after and including the question mark
  - You can rewrite the name of the item in the URL. It is ignored by Amazon. Make it short and meaningful, just as the example above. Write names in object oriented notation with higher meaning first.
  - Sometimes you need to browse following the tree of navigation to find the same item to get rid of all the mess in the URL
  - use https:// instead of http://
  - This is a bid of work, but well worth it as we will use the URL in text in so many places and this reformatting makes the difference of working fast in the source code and stay in the zone or working very slow and not focused.
  - test it after changing

## Why this build:

-Includes best low profile GPU for testing games (what popular reviewers want)
-CPU is plenty for gaming
-8GB ram is sweetspot for price/performance, typical amount of memory
-240W power brick will give enough headroom. 160w is not enough for a strong CPU+GPU

## Strategic tests for this machine
- Noise of Flex ATX
- Reliability of HDPLEX
- Solidworks Speed of GTX 750 vs K1200
- Lightworks Speed of GTX750 vs K1200
- Adobe Premiere Speed of GTX 750 vs K1200
- Comparison SSD vs M2
  - Boot
  - Solidworks Open Project
  - Lightworks Taping Out Movie

## Missing Parts:
- [ ] Flex ATX Gold 300 W
- [ ] Link to Issue of testing HDPLEX PSU

## Researching
- Can we optimize this machine to work with 160W ?

**Comment by VillageHubertChen** [comment]
# Brief of our Skype Call

# Update on Disks

## NVME is still seems more expensive

Above Samsung SSD is SATA not NVME. The [256GB NVME](https://http://www.amazon.com/SSD-NVME-950-PRO-256GB/dp/B015SOI392/) is $180. That makes NVME SSD still a significant premium over SATA SSD. Before making final choice need to check in detail

# Develop two Base Configuration

## Entry Level

This should be very close to the one Bobby researched, except we will go back to SSD 2.5" and possibly consider an i5

### Variation 1: Silent
- 160 W Passive cooled PSU (Silent version)
- Workstation Class (K600)

### Variation 2: Value
- 300W Flex
- GTX 750 Ti

## High End Workstation
- fastest CPU
- 750 / K1200
- Flex ATX 300W
- NVME

# Considerations on Marketing

## Entry Level / Mid Range
- Dell and Apple look better

## High End Workstation:
- We look better than Dell, Apple, HP
- [ ] HC: Link my Workstation Research Article to here
- Niche market, easier to get leading reviewers of this Niche market
- Focus on Markets where we have great know how
  - Photography
  - Gaming (Portable Gaming PC)
  - Engineering Workstation: M-CAD, E-CAD
  - Video Editing Workstation: Lightworks & Premiere
  - Developing Software
- It is better to be the King of 5 hills than to be overlooked in the bigger mainstream market

# Summary on Solidworks

## Rotating of Complex Model Test Results

Michael rotated full assembly of ViCase, full screen size on i7 with Full HD Display:
1. Two Displays - 2 GPU: 1 fps
2. Two Displays - iGPU: 3 fps
3. Two Displays - GTX 750 hacked for Solifworks: 60 fps

This is a very important finding. We should push this in an Article. It is a very good reason to get a workstation PC to work with SolidWorks.

## Idea to demo in Article

We make 2 Gifs, place them side by side. We rotate ViCase. Gifs are small size, set to 30 fps. No need to show resolution. We want to show fps. This should be very impressive demo. Then just say you want speed. Use a Desktop GPU. Simple, believable statement.

## Compile other writing to here
- [ ] Solidworks writing in HDPLEX issue
- [ ] Real view benefits

**Comment by bcaswelch** [comment]
| Type | URL | Price |
| --: | :-- | --: |
| Motherboard | [Gigabyte Z170 ITX](http://www.amazon.com/Gigabyte-LGA1151-Mini-ITX-Motherboards-GA-Z170N-Gaming/dp/B014W2000Q?) | $155 |
| CPU | [Intel 6700k i7 4.0ghz](http://www.amazon.com/Intel-Boxed-I7-6700K-Processor-BX80662I76700K/dp/B012M8LXQW?) | $355 |
| SSD | [Samsung 850 Pro 512 PCIe](http://www.amazon.com/Samsung-950-PRO-Internal-MZ-V5P512BW/dp/B01639694M?) | $328 |
| GPU | [Gigabyte GTX 750ti 2GB](http://www.amazon.com/Gigabyte-GV-N75TOC-2GL-Graphics-Cards/dp/B00MW8NXAW?) | $123 |
| RAM | [Corsair Vengeance 16GB 3000MHz](http://www.amazon.com/Corsair-Vengeance-3000MHz-PC4-24000-Memory/dp/B0134EW7G8?) | $70 |
| PWR | [FLEX ATX 300W GOLD](http://www.amazon.com/FSP-Group-80Plus-Supply-FSP300-60FAG/dp/B0176DXSLG/ref=sr_1_1?) | $80 |

Total Price: $1,110.00

_Why this build_

-CPU is best you can get, high clock speed and performance. Only question is power... May have to use a 6700 (non-k) as it uses significantly less wattage.

-Motherboard has all of the perks of a high end board, great reviews and supports all of the new ports. 

-Memory is high clocked, high performance. Corsair Vengeance very reputable memory sticks. 16gb is the sweetspot for multitasking, gaming, and rendering.

-Samsung PCIe drive is one of the highest regarded on the market, very reputable. 512gb is going to be expensive but as a single drive, this is will enough space for many users. Or we have a 256gb pcie drive paired with a larger hard drive disk.

GTX 750ti is a given, best card for its size. 

_Issue_ ISSUE RESOLVED

The big question in power. 250w is going to be cutting it close when it comes to an i7 + GTX card. Theoretically it should work, but still may cause problems.

**Comment by VillageHubertChen** [comment]
## PSU Config

I am thinking to make the default PSU the 300W Flex ATX Gold. This PC can not reach the _Silent_ class anyways because of GPU Cooler and CPU Cooler. Having the little noise of the Flex ATX in this context should not be disturbing. I hope you can tell me on Monday when you receive the Flex ATX GOld PSU and can test how quiet it is in real life.

**Comment by VillageHubertChen** [comment]
## Great Job on Clean Markdown Table

Great Job! Keep up the good work :+1:

**Comment by VillageHubertChen** [comment]
## Discussing Workflow in Issues

### Current Style

My current style of working on issues was to go back into a made post and update it. But I am realizing this has several drawbacks:
1. You and other contributors can not do that due to different privileges. So we would have two workflows for two classes of people. That is bad. I should work the same way as you and lead by example.
2. It is easy to overwrite each other
3. It is difficult to catch what is new when you arrive on an issue after you get the notification

### Proposed new style
1. Every new information is in a new post
2. If posts contains documentation to archive, during closing the issue one has to go through all comments and compile a consolidated Article

## Your thoughts

Let me know if you agree that we test this new approach for a bit and see if it works?

**Comment by bcaswelch** [comment]
So this new approach would have all new information through comments instead of updating current information? I'm fine with that.

Also, I agree with the 300w Flex. It would be nice to get the HDPLEX working with this system, but its too risky. 300w will give more than enough for the specs.

**Comment by VillageHubertChen** [comment]
## New Workflow

Exactly, simply put new information as new comment on the bottom. If you need to update existing one, copy it to a new comment, then edit it, then post it.
 → Please confirm that you can access the markdown source code of comments I wrote ?

## Power for High End Workstation

Using the HDPLEX is not risky at all. Michael has this configuration and he is running it safely for a year on 200W. My suspicion is (which you guys need to test) that the 300W FlexATX Gold is quiet enough in this context, it is lower cost and makes for a demo machine that you easier bring and demo, since it has no external power brick.

## HDPLEX will be a tested option for High End Workstation

You will test it and offer the HDPLEX. For users who only sporadically need the full performance and who are noise sensitive this may still be a good option.

## Idea for demo machine

Hack the FlexATX to have a switch to turn off the PSU fan for a moment. The reviewer than can experience the noise level difference if using HDPLEX

**Comment by VillageHubertChen** [comment]
# Noise Level Article and Testing

I will create an Article on this Topic. After you edit it and agree on the structure you and Tom will make testing of the noise levels of the different configuration. Then we have much better idea on how to explain and promote it to the customer and how to choose PSU for what kind of configurations
