### ISSUE TITLE
Epic►011►Parent: Board Structure for V²►DIY 2016W23

### ISSUE THREAD

**Issue by bcaswelch** [V-Squared/V-Squared.github.io#122]
# Tasks
- [x] Create Issue
- [x] Create Page Structure, start discussing with HC
- [x] HC: Use this page as brain dump for any related ideas on pages or partial page content
- [x] Find → [DIY Article in Wiki](https://github.com/V-Squared/v2-How-to-DIY-Mini-PC/wiki)
- [x] Move → "Bobby's notes on Article Topics" to comment at the bottom
# Debt Documentation
## Not all Page Structure is finished

We will need to go back in here and open this issue once we do other books. At that time I need to read all comments again, as information is spread out in creative chaotic and brain dump fashion.
## Need to create final Page Structure Tree

Not done yet. Currently we work in agile fashion that we have enough docu to do development and we are creating working web site over documentation.
# Reference

Board Structure: V² > Standards #219
Board Structure: V²►Products #113 
Board Structure for V²►Plan #78 
Board Structure of V²►Organization #80 
Board Structure for V²►Spreading #82 
Epic►011►Parent: Board Structure for V²►DIY 2016W23 #122

**Comment by bcaswelch** [comment]
```
 ├ ViCase DIY and Configuration
 ├ ##DIY Pages##
 │     ├ CPU 
 │     │     ├ i5 vs i7
 │     │     ├ Number of Cores
 │     │     ├ Importance of MHz 
 │     │        
 │     ├ GPU
 │     │     ├ Quadro vs. GTX
 │     │     ├ CUDA cores
 │     │     ├ VRAM
 │     │     
 │     ├ Memory
 │     │     ├ How much do you need?
 │     │     ├ DDR3 vs DDR4
 │     │     ├ Gaming vs. Modeling
 │     │ 
 │     ├ Storage Options
 │     │     ├ PCIe vs SATA
 │     │     ├ RAID
 │     │     ├ How much storage do you need?
 │     │     
 │     ├ ViPC Placement
 │     │     ├ Mounting to monitor
 │     │     └ Using as HTPC
 │     │
 │     ├ Choosing the right parts
 │     │     ├Trusted sellers
 │     │     ├ Performance for your needs
 │     │     └ Schedule
 │     │
 │     ├ Power supply Options
 │     │     ├ Wattage vs Noise
 │     │     ├ Internal vs External
 │     │    
 │     ├ Configuration Testing Procedures **lets discuss this page**
 │     │     ├ 
 │     │     ├
 │     │
 │     ├ V²Case Burn in Procedures
 │     │     ├ 
 │     │     ├ 
 │     │
 │     ├ V²Case Software Installation Procedures
 │     │     ├ Using included V² accessories 
 │     │     ├ RGB colors
 │     │
 │     ├ Troubleshooting your PC
 │     │     ├ Hardware issue
 │     │     ├ Software issue
 │     │
 │     └ Production (*)
 │           ├ Intro (*)
 │           ├ Quality
 │           ├ Feature Requests
 │           ├ Schedule
 │           ├ Known Issues
 │           ├ Revisions
 │           └ Announcements
 │
 ├ ##Configuration##
 │     │
 │     ├ Definition, Testing and Importance of 6 Quiet Levels
 │     │     ├ Choosing the right PSU
 │     │     ├ Benchmarks
 │     │ 
 │     │      
 │     │
 │     ├ The Gamer use case
 │     │     ├ GTX card
 │     │     ├ i5 CPU
 │     │     ├ 8gb RAM
 │     │ 
 │     ├ The Photographer use case
 │     │     ├ Fast storage
 │     │     ├ Powerful CPU
 │     │     ├ No GPU
 │     │     
 │     ├ The 3D modeler use case
 │     │     ├ i7 for hyperthreading
 │     │     ├ Quadro GPU
 │     │     └ High Memory
 │     │
 │     ├ Home Theatre use case
 │     │     ├ Silence is key
 │     │     ├ Lots of space
 │     │     └ Fast network connection
 │     │
 │     └ The Video Editor use case
 │           ├ Intro (*)
 │           ├ Quality
 │           ├ Feature Requests
 │
```

**Comment by VillageHubertChen** [comment]
# Add to top comment:

# Reference
- Page Structure: V²►Products #113 
- Page Structure for V²►Plan #78 
- Page Structure of Organization #80 
- Page Structure for V²►Spreading #82
- Page Structure for V²►DIY #122

**Comment by VillageHubertChen** [comment]
## Please find places for the following Articles:
- Definition, Testing and Importance of 6 Quiet Levels
- Power Options V²Case
- Configuration Testing Procedures
- V²Case Burn In Procedures
- V²Case Software Installation Procedures
- Troubleshooting your PC
- Optimizing your Workstation for Speed 
  - Procedure of Configuration Comparison Benchmarking
  - Best Custom PC Configuration for 3D Design
  - Best Custom PC Configuration for Photography
  - Best Custom PC Configuration for Gaming
  - Best Custom PC Configuration for Solidworks
  - Best Custom PC Configuration for Video Editing

**Comment by VillageHubertChen** [comment]
Hi Bobby, please finish this before Monday evening your time.

**Comment by VillageHubertChen** [comment]
- [ ] Replace the Gamer → Software Developer (in Page Structure)

**Comment by VillageHubertChen** [comment]
# Brain Dump►Generations Configurator and Configurations

## G1
- Config Article and Configurator use redundant data
- Layout in Config Article is hard to read for user
- Markdown Code is hard to read for writer
- Code in Configurator is not clean
- Configurator is written in Angular 1.3

## G2
- Config Article and Configurator use singular data (JSON)
- Powerful Layout. New "Include Method"
- Markdown Code is easy to read
  - Table Data is in external JSON file
- Code will be cleaned up. Have one year more experice now.
- Configurator written in Angular 1.5
  - it will be rewritten to Angular 2.0 later

**Comment by VillageHubertChen** [comment]
# Definition, Testing and Importance of 6 Quiet Levels
- [ ] Find a spot in the Page Structure of DIY
- [ ] Create an Article on this topic
- [ ] Move existing writing to there
- [ ] Edit / review / brainstorm
- [ ] BC, TC: Testing and recording of noise of configs

**Comment by VillageHubertChen** [comment]
# Proposed Top Level Change

## Current Top Levels
- DIY Pages
- Configurations

## Proposed Top Levels
- Ready Made Configurations
- Optimizing a Custom PC for Performance
- Optimizing a Custom PC for Cooling and Noise
- PC Assembly
- SW Installation & Updating
- PC Trouble Shooting
- DIY PC Know How 

## Question

What would you think about User Stories? Belong in here or in the products section?

**Comment by VillageHubertChen** [comment]
# Optimizing a Custom PC for Cooling and Noise
- Speedfan
- V²Panel MCU
- 3 Chamber Airflow
- Noise Measurements

## Work for Speedfan
- [ ] HC: Find writing in Trello
- [ ] HC: Create Page Locations
- [ ] HC: Create Pages
- [ ] HC: Mover Writing from Trello to V²DIY Pages
- [ ] BC: Repeat Configuring Speedfan for his workstation
- [ ] BC: Work with Author to make Speedfan autoboot

**Comment by VillageHubertChen** [comment]
# Urgent: Confirm → Proposed Top Level Change

See the comment above. As per our latest phone call we will then try beginning in two hours today to implement all Top Levels (Books) and then implement all Articles in the Book: "DIY Custom PC Know How" and subsequently copy all Articles from the Wiki pages. This way if all goes well tomorrow you can be writing.

**Comment by bcaswelch** [comment]
Yep, im ok with the change.

**Comment by bcaswelch** [comment]
```
V² Home Page
     ├ DIY
     │     ├ Parts of a Computer System
     │     │     ├ CPU
     │     │     ├ GPU
     │     │     ├ Memory
     │     │     ├ Storage
     │     │     ├ Power Supply
     │     │     ├ Motherboard
     │     │     ├ Memory
     │     │          
     │     ├ ViCase Placement
     │     │     ├ Creating an AiO
     │     │     ├ Standalone Machine
     │     │     └ Using as HTPC
     │     │
     │     ├ Choosing the right parts
     │     │     ├ Trusted sellers
     │     │     ├ Performance for your needs
     │     │     └ Schedule
     │     │    
     │     ├ Configuration Testing Procedures **lets discuss this page**
     │     │     ├ 
     │     │     ├
     │     │
     │     ├ V²Case Burn in Procedures
     │     │     ├ 
     │     │     ├ 
     │     │
     │     ├ V²Case Software Installation Procedures
     │     │     ├ Using included V² accessories 
     │     │     ├ RGB colors
     │     │
     │     ├ Troubleshooting your PC
     │     │     ├ Hardware issue
     │     │     ├ Software issue
     │     │
     │     └ Production (*)
     │           ├ Intro (*)
     │           ├ Quality
     │           ├ Feature Requests
     │           ├ Schedule
     │           ├ Known Issues
     │           ├ Revisions
     │           └ Announcements
     │
```

**Comment by VillageHubertChen** [comment]
# Defining DIY Board
- **Board-Bar Name:** DIY
- **Board Name:** V²DIY Workstation PC
- **Board Subtitle:** How-to and Know How Articles and Tools to optimize, build, upgrade and fix your Custom Workstation PC.

**Comment by VillageHubertChen** [comment]
# DIY Books

| Menu | Subtitle |
| --: | :-- |
| Configs | Ready Made Workstation Configurations |
| Optimize | How to Optimize Workstation PC Performance |
| Cool | How to Make your PC Cool & Quiet |
| Assemble | How to Assemble a Workstation PC yourself |
| AiO | How to Build an All-In-One Workstation |
| Install | Software Installation & Updating |
| Fixing | How to Fix Your Workstation PC |
| QA | How to Check Workstation PC is up to spec |
| Parts | Choosing & Understanding Workstation PC Parts |
| Tools | Custom Workstation PC Configuration Tools |
| Compare | Comparison Reviews |

The Books are choosen to rank high on search phrases with Google and YouTube. The introduction article will be written also considering hitting all the search words that workstation users and buyers are looking for. After all, we are here to help the Workstation PC user, so we should answer the most sought after questions first.

Menu names are not gramatically correct. They are choosen to be short.

**Comment by VillageHubertChen** [comment]
# Parts Articles

| Menu Name | Article Name |
| --: | :-- |
| Introduction | How to choose Workstation PC Parts |
| Boot Disk | How to choose the Boot Disk |
| Data Disks | How to choose Data Disks |
| RAID Disks | How to choose RAID Disks |
| Motherboard | How to choose the Motherboard |
| CPU | How to choose the CPU |
| DRAM | How to choose the Memory aka DRAM |
| Operating System | How to choose the Operating System aka OS |
| Case | How to choose the Workstation PC Case |
| Accessories | How to choose Workstation Accessories |

**Comment by VillageHubertChen** [comment]
# Comparison Review Articles

| Menu Name | Article Name |
| --: | :-- |
| Introduction | Comparisons Assisting in Buying a Workstation PC |
| Workstation Comparison | Comparison Review of Workstations up to $4000 |
| Custom PC Comparison | Comparison Review of Custom Build PC up to $4000 |
| Mac Mini Comparison | ViPC Mini PC versus Mac Mini Comparison Review |
| ViCase Generations | Comparison Review of ViCase Generations |

**Comment by VillageHubertChen** [comment]
# Bobby's notes on Article Topics

This has been moved from his top comment
- Choosing the right parts
- Which CPU for your needs?
  - Difference between i5 and i7. Gaming vs. Rendering
- Which GPU for your needs?
- GTX vs. Quadro. 
  - Gaming vs. 3D modeling performance
- Turning ViPC into an AiO
- Importance of memory
- Importance of drive speed

**Comment by VillageHubertChen** [comment]
# Closing Issue with Debt

## Debt Documentation

### Not all Page Structure is finished

We will need to go back in here and open this issue once we do other books. At that time I need to read all comments again, as information is spread out in creative chaotic and brain dump fashion.

### Need to create final Page Structure Tree

Not done yet. Currently we work in agile fashion that we have enough docu to do development and we are creating working web site over documentation.

**Comment by bcaswelch** [comment]
Sounds good.

**Comment by VillageHubertChen** [comment]
Thanks for the handshake comment to my last comment. If you can keep this habit will be great, then I know you got it.

**Comment by VillageHubertChen** [comment]
# Updated Board Structure

```
V² Home Page
     ├ Standards
     ├ Products
     ├ Makers
     ├ DIY
     │     ├ Intro V² Modular PC
     │     │     ├ Workstation Comparison
     │     │     ├ Custom PC Comparison
     │     │     ├ All-In-One Workstation Comparison
     │     │     ├ Mac Mini Comparison
     │     │     ├ The Missing Formfactor
     │     │     ├ The Missing PC Standard
     │     │     └ ViCase Generations
     │     │    
     │     ├ Parts of a Computer System
     │     │     ├ Boot Disk
     │     │     ├ Data Diskss
     │     │     ├ RAID Disks
     │     │     ├ Motherboard
     │     │     ├ CPU
     │     │     ├ DRAM
     │     │     ├ Operating System
     │     │     ├ Case
     │     │     └ Accessories
     │     │          
     │     ├ Configs
     │     │     ├ Overview
     │     │     ├ Spec Parts
     │     │     ├ Real Parts
     │     │     ├ Vendor Parts
     │     │     └ Configs
     │     │
     │     ├ Assembly
     │     │     ├ Assembly of DIY PC
     │     │     ├ Installaing OS
     │     │     ├ SpeedFan
     │     │     └ Quality Testing
     │     │    
     │     ├ Fixing
     │     │     ├ Designed for i Fix it
     │     │     ├ Fixing common problems
     │     │     └ Getting help
     │     │
     │     └ Apps
     │           └ V² Configurator
     │
     ├ Retail
     ┊ 
```
