### ISSUE TITLE
Refactoring V² Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#123]
# Tasks
- LC: [ ] Implement _Features_ as described below
- LC: [x] Implement _Big Picture Tabbed Slide Show_ as described below
- LC: [x] Fix Bugs in _Big Picture Tabbed Slide Show_ as described below
- LC: [ ] Trigger HC for review
- HC: [ ] Review
# Latest Terminology

We are splitting the Home Page into 3 Sections:
1. Features → presentation via feature layout
2. Big Picture → presentation via tabbed slide show
3. Footer → as is
# Features
- [ ] Read References:
  - [ ] → Introduction to V² (Features of V² Home Page) #23
  - [ ] → Epic►004►Parent►Hackathon V² Home Page #41 
- [ ] Read method of implementation
  - Possibly ignore designing the Jumbotron at this time
  - Design each feature the way you see fit. Then trigger for review
  - Features that you do not know how to design, leave the copy in the right spot as to trigger ideas on how to design them
- [ ] use new method that content is in YML and placement is via Jekyll Includes
  - exceptions:
    - anything related to SVGs including the interactive SVG
- Copy
  - all writing is in issue: → Introduction to V² (Features of V² Home Page) #23
  - [x] update above text
  - [ ] LC: Create picture place holders in GIMP. Correct size in pixel. Use Picture Place Holder No. In the issue you write the description to the picture place holder.
- [ ] Make beautiful styling of features.
  - there are lots of ideas and hero pages in  →  Introduction to V² (Part of V² Home Page) #23 
  - use your own ideas. Impress me :-)
  - Each feature shall get a visual. Use a place holder image for now.
# Big Picture Tabbed Slide Show
- [x] Add previous and next button as discussed using buttons with links to tabs from JSON file
- [x] adjust styling of readiness bar to new style
- [x] overlay readiness bar to bottom of square image
- [x] Move title as overlay to top of square image. Try white title with protection.
- [x] Move link to the corresponding Book Page into Overlay text
- [x] Overlay text remains exactly how it is now, except that we add the link to its book page
- [x] Remove Heading in Slide. We will use the tab as heading
- [x] Keep the sub title, but find a layout that uses very little vertical space
- [x] Compact vertical design, so two row slide show fits on most screens
- [x] LC: Fix broken layout bug
- [ ] HC: 2nd Row Content: Campaign 1, Campaign 2, Campaign 3 (as discussed)
