### ISSUE TITLE
Epic►008►Parent: Legal Protection of IP

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#124]
# Tasks
- [x] TC, BC, HC: Brainstorm Legal protection of IP
- [x] HC: Write → Business Model → below
- [x] HC: Write → Legal Protection of Intellectual IP → below
- [x] HC: Write → Legal Protection of Business Model → below
- [x] HC: Create Issue
- [x] SL: Review and brainstorm
- [x] HC: Include SL feedback
- [ ] GI: Review and brainstorm
- [ ] KC: Read and write feedback to → Business Model → below
- [ ] KC: Read and write feedback to → Legal Protection of Intellectual IP → below
- [ ] KC: Read and write feedback to → Protection of Business → below
- [ ] KC: Research if Copyright for ViCase is strong enough? → Write results in new comment.
- [ ] KC: Research if USO offers other legal protection method? → Write results in new comment.
- [ ] HC: Discuss feedback with KC and come to agreement on changes and how to proceed
- [ ] HC: Incorporate KC's feedback and create next action list
### Ideas
- Patents and Standards both are for documenting and protecting ideas
  - Standards require a companion license agreement
- Patents are expensive and community unfriendly
- Open standard is community friendly, not expensive and protects ideas all the same
### General Type of IPs to protect
1. Design: Copyright & Registered Design
2. Ideas: Open Source Standard with License
3. Trademarks: Trademarks
### Markets

Protect Europe and USA as they are the biggest markets
# Reference
- → Research which License #24

**Comment by VillageHubertChen** [comment]
# Business Model V² Core Organization
- Non Profit Community Owned Organization
  - Community Owned: Independant from Industry
  - Servicing: User, Press, OEM, Retailer
  - Non Profit: Keeps cost low and keeps us independant
    - Provides Tax benefits: Keeps cost low
    - Provides Tax benefots to buyers: increase sales of TBP
- Give away the Open Source Standard
  - Pros: Important for V² Standard to become mainstream
  - Cons: No revenue stream for V²Core team to pay for expenses
- Selling Trailblazer Products (TBP)
  - Demo what products you can build with V²Standard
  - Working Product in hand is 10 x more convincing than specs alone
  - Find design flaws in V²Standard, so we can fix them
  - RDK for OEM
  - Review Samples for Press
  - Keeps Community engaged
  - Revenue Stream for V²Core Team (this is our only revenue stream)
- Full time V² Core Team
  - Located in China for lowest cost and best possible OEM support
  - Full time team works faster than contribution only
  - Full time team keeps V² more consistent versus contribution only
  - Create the V² Web Site which serves as crystallization point to Contribution Work
- Lots of Contribution
  - Provide specialized know how better than core team
  - Community feedback ensures V² creates what people need and want
  - Lower cost to create V² Standard

## Why we spell out our business model here

We only can protect our business model, if we know it.

**Comment by VillageHubertChen** [comment]
# Legal Protection of Intellectual IP

## List of Known Threads requiring Legal Protection
- Another Standard Organization copies our work and claims it to be their own
- Another company claims Trailblazer Product Design and protects it with patents, copyright and other legal tools

## Protecting V² Open Standard IP

### Protecting Standard

Best protection as far as we can see is to publish the standard ASAP under a Suitable License. We plan to use CC-BY. For more information in this topic → Research which License #24 

## Protecting V² Trailblazer Products Design
- Print Copyright Village Tronic on:
  - Trailblazer Product Bottom Cover Model Label
  - On Product Web Site
  - Every picture of Trailblazer Products
- Always mention ViCase is copy right protected implementation of Free and Open Source V²Standard
- Consider getting a patent on gating design, so we will also print patent on it. Once applied, we can print patent pending on product label. We have experience in getting Patent granted.
- Research if there is another protection mechanism. In Germany there is [Registered Design](http://www.dpma.de/english/designs/index.html). It costs EUR 60. 
  - Is there an equivalent in USA?
  - Sascha found international design protection following the Haag Design Agreement
    - http://www.patente-stuttgart.de/index.php?page=publikationen_01009

### What can be Registered Design
- Square shape with centered squared air intake
- Contiguous side grill

## Protecting Trademarks
- Always list first occurrence on a page of each of our trademarks with (TM)
- Each page on web site as a link to trademarks, which lists all trademarks referenced in our site

## Increase Protection with Community Support
- Write Article on benefits to Community for applying our Business Model and Legal Protection
- Document our Legal Protection Efforts for public scrutiny / improvement.

**Comment by VillageHubertChen** [comment]
# Protection of V² Business

## Legal Protection of V² Business

If we can protect against the "Known Threads" then our Business should be protected. See above
- [ ] Research if their are other threads not listed yet

## Protection through Win / Win Business Scenarios

## Protection vs low cost copy cats

**Comment by VillageHubertChen** [comment]
# Objectives
- Help sales
- Help awareness
- Do not hurt sales
- Deliver standards early, as V² Mission is to deliver the missing standards
- Do not hinder OEM to start using V² Standards ahead of schedule
- Protect Revenue Stream of V²Core
- Protect IP of V²
- Motivate Press to promote V²

**Comment by VillageHubertChen** [comment]
# Proposed Label Design ViCase Mini G2v1 (v1)

## Open Source / Compatibility
- V² Logo
- Free and Open Source Modular PC Standard 
- V² Compatible: http://v-squared.github.io/

## Village Tronic Proprietery
- Phoenix Logo
- www.villagetronic.com/products/vicase-mini
- Pat. No: 
- Registered Design No:
- USA Protection No:
- Production Run No:
- Serial No:
- Warranty: 10 Years
- Manufacturing Year: 2016

**Comment by VillageHubertChen** [comment]
# Enforcing Legal Protection

# Seek Win - Win first

## Always seek mediation first

Enforcing legal protection always comes at the cost of negative karma. As such we should try hard to avoid it. Prior to enforcing we should try mediation. If we can reach a win - win agreement, the better for all.

## Some companies only react to legal enforcement

If mediation failed and the remaining choice is between using legal enforcement or accepting significant harm to this community we will use legal enforcement in order to protect this community.

# How to enforce

## Injunction to Customs
- Injunction with customs on Import, stop Retailer to import violating products
- Common practice, same as other standard organizations

### How to get an Injunction
- Trademark Violation
- License Violation
- Registered Design Violation
- Patent Violation

## Take down notice to web sites

In case of Trademark, License or Registered Design violation we can send a take down notice to the operator of the web site with a request to take that article / product down. If we back our claims up in 99% of cases that page will be removed ASAP.

## Take down notice to search engines
- Works the same as the topic above, but with higher efficiency.
- Protecting our trademarks as search words only for our products is most important
  - It is desired if a V²Case maker claims to be V²Case compatible
  - It is a license and trademark violation if he claims his product is ViCase

## Choosing Licenses to enable Injunction

## License agreements
- V²Trademark Usage
- Look of V² (Square Case with Square Grill, Side Grill all around)
- with power to revoke if product fails self tests

## Proof of first use
- GitHub Revision Management system

# Create a Trailblazer Grace Period
- after grace period every copy is fair
- we put out all 3D design files Open Source

**Comment by VillageHubertChen** [comment]
# Create Rules that create desired behavior

## Desired behavior
- Do not copy Trailblazer Product design within Grace Period
  - ViCase products use a protected design by Village Tronic
- Do create V² compatible products with your own design
  - If so, need to reference to V² Site
- Protect your design of V² Standard
- Do not claim V² Standard to be your creation
- Do not claim your products are ViCase
- Do reference to V²
  - Legally you have to due to license
  - It is in your best interest as it helps sales and reduces costs
