### ISSUE TITLE
Epic►010►Parent: V²DIY User Stories / Data Structure / Apps

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#125]
- [x] HC: Write → Problems to solve → below
- [ ] HC: Write → User Stories → below
- [ ] HC: Write → Workflows → below
- [ ] HC: Write → Alternative Sources for Parts → below
- [ ] HC: Write → Layer Model → below
- [ ] HC: Write → Data Model and Usage → below
- [x] HC: Write → Apps → below
- [x] HC: Write → Compatibility Rules → below
- [x] HC: Write → Alternative Marketplaces → below
- [ ] HC: Write → Implementation / Technologies → below
- [x] SL: Review 1
- [x] HC: Include SL Feedback Review 1
- [x] SL: Review 2
- [x] HC: Include SL Feedback Review 2
- [ ] LC: Review 1
- [ ] HC: Include LC Feedback Review 1

**Comment by VillageHubertChen** [comment]
# Problems to Solve (v1)
- Redundant data for _Config Articles_ and _Configurator_
- Markdown code is hard to read for writer
- Limited layout capabilities
- No _Revision Management_ for _Data_
- No _Approval Workflow_
- No _Parts Specs_
- No _Alternative Vendors_ for same _Part_
- No _Relational Data_
- No _Alternative Parts_ to same _Part Specs_
- No _Alternative Markets_

**Comment by VillageHubertChen** [comment]
# User Stories (v1)

**Comment by VillageHubertChen** [comment]
# Workflows (v1)

**Comment by VillageHubertChen** [comment]
# Alternative Sources for Parts (v1)
- keys for countries, market options, MOQ, availability, pricing
- Part search phrase for market places

## Relation Ships
- Part Specs --< Parts
- Part --< vendor parts
- Part Specs --< vendor parts (via parts) why

**Comment by VillageHubertChen** [comment]
# Layer Model (v1)
- [ ] Create Overview Table
- [ ] Fill out text in chapters below

## Range Config (High End, Mid Range, Entry Level)

## Model Config (ViPC-750, ViPC-1200, ViPC-1, ...)

## Revision Config (ViPC-750v1, ViPC-750v2, ViPC-1v1, ...)

## Customer Config (ViPC 750 v1-Sascha.Link)

## Market Options (Newegg, Amazon, Amazon de, etc ...)

**Comment by VillageHubertChen** [comment]
# Data Model and Usage (v1)
- [ ] Finish Data Model
- [ ] Finish Data Usage

# Data Model
- Config --< Part
  - Used in Configurator to load Configuration
- Base Config >-< Part Spec
- Part >-< Vendor
- Part Spec --< Part
- Range Config
- Base Config
- Config
- Part

# Data Usage

Benefit of this system is to have a singular place to store configuration specs and data versus to spread them across many places. We no longer differentiate between Apps, Web Apps and Web Pages. Every page is an Angular Web App now. Where needed the HTML is dynamically generated from the data in the JSON files.

## Range-Config.json
- Product Pages
- Spec Config
- Configurator (Pre Selection of Configs)

## Type-Config.json
- Data Sheet
- Product Pages
- Configurator
- Spec Pages

**Comment by VillageHubertChen** [comment]
# Apps (v1)

## How to work while Apps not ready

Each app outputs a specific json file. Until the app is ready the json file the shop admin need to edite this file by hand. Even this is a big improvement over now, as the json file is easier to edit the a complex markdown table (given you use a json editor). Another big improvement is that you need to enter the data only once, versus now you would need to do this in many places.

## How the app work
- The App is embedded within the Article on the same topic
  e.g. The Range Configuration App is in the Article: Range Configurations
- Look and Feel is exactly like the V²Configurator
- The Configurator loads an input json file (like in V²Configurator)
- The user manipulates the choices (like in V²Configurator)
- The Configurator generates a json text output that you copy to the clip board
- You open the corresponding json file on GitHub, paste the clipboard content, push to GitHub
- Reload the Web Page that reads that content and it will be using the updated json data
  - downstream web pages can be:
    - Product Pages on V²Site and ViSite
    - Shop Pages on V²Shop and ViShop
    - App Pages in this System

## Range Configurator
- User: Shop Admin
- Assists Administrator to edit the Range-Config.json file
- Output is text in clipboard, admin need to paste it into paste it manually into the Range-Config.json file and commit it to GitHub
- Before this Configurator is ready the admin need to edit the Range-Config.json file manually

## Model Configurator
- User: Shop Admin
- Assists Administrator to edit the Model-Config.json file
- Output is text in clipboard, admin need to paste it into paste it manually into the Model-Config.json file and commit it to GitHub
- Before this Configurator is ready the admin need to edit the Model-Config.json file manually

## Revision Configurator
- User: Shop Admin
- Discussion: ??? After introduction of Alternative Vendor Parts this may not be needed anymore?

## Custom Model Configurator
- User: Shop Customer
- This is the V²Configurator that the customer uses in the V²Shop
- Customer's configuration is automatically saved in the V²Shop with customer's order
  - we expect we can use client side script to store it in a custom field of Shopify

## Purchasing Optimizer
- User: Shop Purchasing
- Loads the Customer's PC Configuration
- Assists the Shop Owner / DIY Builder to find parts that are:
  - lowest cost yet completely fulfill the specs.
  - are in stock today, ready to order today to arrive tomorrow.

## B2B Order Assistant
- User: Shop Purchasing
- Loads the data from the Purchasing Optimizer
- Automatically (or semi-automatically) generates the cart with the market place
  0 first supported market place: Amazon US

## Shop Product Page Generator
- User: Shop Admin
- Select one PC Configuration from drop down list of ready made configurations
- Select the Generic ViPC description (Short / Middle / Long)
- Select the output shop format from drop down list: (V², Amazon)
- Press the generate button to generate the page, ready to be pasted into the new shop page

# Pages

## Ranges Configs

## Type Configs

## Revision Configs

## Customer Configs

## Vendor Configs

**Comment by VillageHubertChen** [comment]
# Compatibility Rules (v1)
- No Rules on Admin Level. Admin needs to know what he is doing
  Each configuration change on admin level should be double checked with a second expert
- Applied rules (although applied by a person) need to be documented by admin
  - this is the precursor to automate these rules in the corresponding app
  - Admin should write notes how later rules can be automated
- Customer Configurator has rules to protect customer
  - it is not expected that the customer is an expert
  - we already have implemented such a system
  - rules are entered into json 
  - if customer configures a non compatible configuration he is warned and the part choice is reset

**Comment by VillageHubertChen** [comment]
# Alternative Marketplaces (v1)

# First supported Market Place
- Amazon US

# List of Future Market Places
- Newegg US
- Newegg Taiwan
- Newegg China
- Amazon UK
- Amazon DE
- Atelco DE ?
- ???

**Comment by VillageHubertChen** [comment]
# Implementation / Technologies (v1)
- [ ] Finish writing of this comment

# Philosophy workflow Relational DB in JSON
- Write data into JSON file using JSON editor
  - Masks
  - Linting
- Use Angular App to generate the next layer JSON file
  - Copy paste result from App and save on GitHub
- Repeat process until final layer

# Data Structure just as in relational DB
- Data is stored in flat tables
- Each Data Type has one Table
- Each Row has keys, just as in relational DB

# Rapid Prototyping

I build in OpenOffice?

# Thinking the other way

Instead of thinking that working with JSON instead of SQL is a disadvantage, lets find advantages to this approach:

## This methods suits better writing Articles

# Why try hard to do with JSON

We are very proficient now to code, host and use the combination of JSON data and Angular App. It is most likely faster to develop a new complex app when you know the Hosting and Toosl. Develping a new kind of app and learning new tools the same time may be too hard and take too long.

# Full data base in the future

We all agree than a full database will be better. Given more time, more funding, more experience and more programmers we will make.
