### ISSUE TITLE
Add Open Source Logos

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#13]
## Hero Design
- **URL:** http://uber.demo.joomlart.com/index.php/blocks/clients
- **Style:** Clients - Image Gray
- **Key Features**
  - gray logo at first
  - hover shows logo with their colors and tool tips as per above
# Reference
- http://v-squared.github.io/
## CC-BY-4.0 Logo

![](https://i.creativecommons.org/l/by/4.0/88x31.png)
- http://creativecommons.org/choose/
## Open Source Initiative Logo
- https://opensource.org
## Open Source Hardware Logo
- http://www.oshwa.org/open-source-hardware-logo/
# Tasks
- [ ] HC: Remove MIT Logo → #24 
- [ ] HC: Find Logos
- [ ] HC: Process to size, gray and color version = 12 Logos
  - need to be PNG 24 with great alpha, because we use gray background
- [ ] @LukasChen  Change design according to "Hero Design". See above.

**Comment by VillageHubertChen** [comment]
HC: Remove MIT Logo → #24

**Comment by VillageHubertChen** [comment]
Added URLs to Logos
