### ISSUE TITLE
Shipment 001 V²Core → V²Shop-Midwest

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#131]
# Tasks
- [x] HC: Create Proposal of contents of shipment
- [x] TC: Please write your shipping address into the comment
- [x] TC, BC: Check if you want anything else, trigger BC and KC to check too
  - write the result into comment. This will trigger me to begin prepping the shipment
- [x] ML: Create Order in Taobao. Trigger HC approval before order
- [ ] ML: Prepare shipment, trigger HC for review
- [ ] ML: Ship to address TC posted in comment
- [ ] HC: Close this Issue. Create new Issue on Review this Shipment in Backlog
# Proposal of contents of shipment
- [x] ViCase Cooler L
- [x] ViCase Cooler XL
- [x] ViCase-Chroma (Strip, PSU, Remote Control. Could be the set we have)
- [x] ViCase-Control
- [x] Rubber Feet Samples (both types)
- [x] Rubber Grommets Samples
- [x] Screw Samples 
- [ ] ViPanel Dummy Sample
# About Screw and Rubber Samples
- Purpose is to let V²Shop check if there is anything not OK
- Package each sample into a small Zip Lock Bag. 5 pcs will be sufficient. No label needed.
# Separate Shipment !

As per vote V²Shop-Midwest wants to put priority to put ViCase Gold Sample to production. As such the best time slot to BTL (Bring to Life) ViPanel would be once we are waiting for samples to return from CNC Shops or from Anodizing. Since all other parts are available earlier, we will make two shipments. This is significantly more expensive, but is accelerating progress (and increases motivation) in V²Shop-Midwest.
# We removed the Aluminum Sample
1. Bobby already purchases one
2. It serves no function. We decided to manufacture ViCase in a different factory than ViDock. The sample of anodized aluminum BC bought will be as close to what ViCase sample will be as the ViDock sample
# We added ViPanel Dummy Sample

We already have all parts and PCBs to assemble ViPanel-V² & ViPanel-ATX. But we have no time to do it and BTL. So this is a compromise. We assemble a dummy sample of the ViPanel-V² and we add the 5.25" Bay so you can convert it to ViPanel-ATX. I believe there is value for you to hold it in hand and see that this is pretty much finished and how it will look and feel. You may get more excited to speed up your writing and get the V²Shop Midwest online and start selling this one. I have a feeling it is very cool.
# Note: This Issue was moved

by HC → [Original Issue](https://github.com/V-Squared/v2-Production/issues/46) on Mon Jun 06 2016

**Comment by bcaswelch** [comment]
Yep, these all look fitting for the first shipment. Will give lots to test out.

**Comment by VillageHubertChen** [comment]
@bcaswelch To speed up communication and to increase clarity: On top of your comment, please also tick the corresponding check box in the first comment. When doing so you will see it is adjacent to the task to paste the address. Please do that to then I can remove the gating label :-)

**Comment by tcaswelch** [comment]
1084 Aubrey Springs Ave.
Henderson, NV  89014-6817

**Comment by VillageHubertChen** [comment]
@ Tom, sorry to ask so stupid question. It has been a while I lived in the states. Is the full address:

Tom Caswelch
1084 Aubrey Springs Ave.
Henderson, NV 89014-6817
USA

Or do you have different formatting?

**Comment by bcaswelch** [comment]
Yes, this is the right formatting.

**Comment by VillageHubertChen** [comment]
@bcaswelch @tcaswelch Check the changes we made to shipping content. If you want to make any changes you need to rush with your comment. As soon as all parts arrive we want to make the shipment this week.

**Comment by bcaswelch** [comment]
This all works

**Comment by VillageHubertChen** [comment]
@bcaswelch Thanks for the reply.

@VillageMichaelLin Please prepare the shipment. Let me see the content before final packaging. Lets make packaging together to make sure it will arrive safely. Work with Xiao Mao for using best shipping forwarder rate. Once done, post comment once shipped. Once we have the tracking number, post the tracking information in here too.

**Comment by VillageHubertChen** [comment]
@VillageMichaelLin It seems this one slipped your mind. Discuss with me today where we are add. All parts should be in-house. Can you prep shipment today?
