### ISSUE TITLE
Evaluate HD-Plex PSU

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#132]
# Tasks
- [x] HC: List the PSU to buy
- [x] HC: Write project
- [x] @bcaswelch Please: 1) Ask Tom to accept the V² Invitation. 2) Ask him to work on this issue
- [x] TC: Buy above PSU (2 x AC, 2 x DC) from HD-Plex
- [x] ML: Make the snaps and put to this folder: `\\MINI-PC\Users\Mini\Documents\Production\ViCase\G2\ViCase\Case\Sample-Gold\Documentation\Snaps\RAW`
- [x] HC: Process the snaps and upload to this issue
- [ ] TC: After receiving the PSUs verify that all dimensions are exactly as per specs. Once done, report the result in a comment to this issue. This will trigger HC to review result and include into ViCase design. We plan to tape out ViCase for production around June 7. Follow the instructions in the comments below
- [ ] ML: Finalize the HDPLEX PSU drawings in your 3D CAD. Then close the issue.
# List of HDPLEX models to buy and test
## HD-Plex Online Shop

This is the preferred source to buy from. They are in LA. This purchase will begin for you to build a vendor / customer relationship. Once you buy more you can ask for a better price for two reasons:
1. Remove the EMI filter for the AC-DC Adapter. We have EMI filter build in and do not need it. This may shave of $5
2. Qty discounts
3. At a later point we will suggest a to work together on PSU standards and cross linking of both web sites
- [HDPLEX 80W AC-DC](http://www.hd-plex.com/HDPLEX-Internal-80W-AC-Power-Adapter-with-19VDC-Output-for-Intel-NUC-and-Thin-ITX.html) $32
- [HDPLEX 160W AC-DC w/PFC](http://www.hd-plex.com/HDPLEX-Internal-160W-AC-DC-Adapter-with-Active-PFC-and-19VDC-Output.html) $55
- [HDPLEX 160W DC-ATX](http://www.hd-plex.com/HDPLEX-160W-DC-ATX-Power-Supply-16V-24V-Wide-Range-Voltage-Input.html) $35
- [HDPLEX HiFi 250W DC-ATX](http://www.hd-plex.com/HDPLEX-250W-Hi-Fi-DC-ATX-Power-Supply-16V-24V-Wide-Range-Voltage-Input.html) $85
## HD-Plex @ Amazon

(Do not buy, just for your reference)
- [Amazon►HDPLEX 80W AC-DC](www.amazon.com/gp/product/B00QSRBPB2/) $32
- [Amazon►HDPLEX 16W DC-DC](http://www.amazon.com/gp/product/B00KVWHUXW/) $35
## 240W Dell Power Brick

(Must buy, needed for HDPLEX HiFi 250W DC-ATX)
- [Amazon►240W Dell Power Brick](http://www.amazon.com/240W-DellPSU-Brick/dp/B00AVMYMUG) $46
## Experience update ViPC-750 with SolidWorks

As you saw in the →  Video Review (0) V²Shop-Midwest #40  the design of ViPC in SolidWorks is fairly complex. You saw I could rotate the model smoothly. We had 60 fps updates, which is as smooth as it gets. If we were to remove the GTX750 and we were to use the integrated graphics there would be updates at 1 fps. Move the model around is almost impossible and very time consuming, let alone annoying. Having or not having a powerful GPU makes the difference in SolidWorks working fast in design view when loading complex designs. On simple designs there is no difference.

The second difference is the availability of real-view. Real view offer real time rendering versus waiting minutes to hours. We used it in the Phonix Article title graphics that you soon will see.

The GTX 750 is not natively supported by SolidWorks but we hacked it. Alternatively you can go with the workstation equivalent card.
# Images for Quick Ref
## 80W AC-DC

![](http://www.hd-plex.com/images/product/80WACDC/detailpicture.jpg)
## 160W AC-DC

![](http://www.hd-plex.com/images/product/160WACDC/detailpicture.jpg)
## 160W DC-DC

![](http://www.hd-plex.com/images/product/160WDCATX/detailpicture.jpg)
## 250W DC-DC

![](http://www.hd-plex.com/images/product/250WDCATX/detailpicture.jpg)
## 240W Dell Power Brick

![](http://ecx.images-amazon.com/images/I/41dRQenV7oL.jpg)
# How to report progress

Please copy the tasks which you have closed into a new comment and then tick them off. I will be notified and will transfer the tick to the overview checklist in the top comment. This way I stay in the loop of the progress. 
## Example:
- [x] @bcaswelch Please: 1) Ask Tom to accept the V² Invitation. 2) Ask him to work on this issue
- [x] TC: Buy above PSU (2 x AC, 2 x DC) from HD-Plex
# This issue was moved
- @VillageHubertChen commented on [Thu Jun 02 2016](https://github.com/V-Squared/v2-Production/issues/42)
- @VillageHubertChen commented on [Mon Jun 06 2016](https://github.com/V-Squared/v2-Production/issues/42#issuecomment-223907041)

**Comment by VillageMichaelLin** [comment]
# Checking the dimensions of the HD-Plex PSU

## Instructions how to check
- **Check every dimensions:** You need to measure every dimension of the real product. Please note any discrepancy.
- **Measure the one with Questions Mark twice:** We guessed these dimensions. So your measurement need to be extra careful, as they are the only reference with no double check.
- **Unit:** mm

## 80W AC-DC pictures

### Top View

![80w-ac-dc-topview](https://cloud.githubusercontent.com/assets/7278716/15862084/1a57f2b2-2d01-11e6-8670-95546426547b.png)
80W-AC-DC-TopView.png

### Side View

![80w-ac-dc-sideview](https://cloud.githubusercontent.com/assets/7278716/15862063/08d85a86-2d01-11e6-9804-b4bfb113b793.png)
80W-AC-DC-SideView.png

## 160W AC-DC pictures

### Top View

![160w-ac-dc-topview](https://cloud.githubusercontent.com/assets/7278716/15862445/463d961a-2d02-11e6-9641-eb8bbc096e86.png)
160W-AC-DC-TopView.png

### Side View

![160w-ac-dc-sideview](https://cloud.githubusercontent.com/assets/7278716/15862458/4ffe26e2-2d02-11e6-85a4-dfa57e94f04e.png)
160W-AC-DC-SideView.png

## 160W DC-DC pictures

### Top View

![160w-dc-dc-topview](https://cloud.githubusercontent.com/assets/7278716/15862473/641dbe4e-2d02-11e6-8f34-e65b12c15187.png)
160W-DC-DC-TopView.png

### Side View

![160w-dc-dc-sideview](https://cloud.githubusercontent.com/assets/7278716/15862570/ad6245a2-2d02-11e6-8650-458e439bf28d.png)
160W-DC-DC-SideView.png

## 250W DC-DC pictures

### Top View

![250w-dc-dc-topview](https://cloud.githubusercontent.com/assets/7278716/15862667/f6f177f6-2d02-11e6-9e68-d5cee2d75051.png)
250W-DC-DC-TopView.png

### Side View

![250w-dc-dc-sideview](https://cloud.githubusercontent.com/assets/7278716/15862699/073008bc-2d03-11e6-95f4-c22e25815ea4.png)
250W-DC-DC-SideView.png

**Comment by bcaswelch** [comment]
Will update these soon. The other 2 parts should be arriving any day.

**Comment by tcaswelch** [comment]
[HD_Plex_80W-AC-DC-SideView.pdf](https://github.com/V-Squared/V-Squared.github.io/files/310542/HD_Plex_80W-AC-DC-SideView.pdf)
[HD_Plex_80W-AC-DC-TopView.pdf](https://github.com/V-Squared/V-Squared.github.io/files/310543/HD_Plex_80W-AC-DC-TopView.pdf)
Finally got digital calipers functioning.

**Comment by VillageHubertChen** [comment]
1. I got the measurements for one part. When can you complete the measurements for the remaining 3 parts?
2. Can you please process the imaging the following way:
   1. Open the Image in Photoshop or Gimp
   2. Overwrite the measurement with a different color, so it is clear to see which one has been checked
   3. Convert the image to 8 bit PNG, 4 bit color depth = 16 colors is sufficient
      - this makes image sizes really small, such as < 10 kb
   4. Drag the images into the comment. They will automatically upload and generate markdown source code. 
   5. The result look like the comments with images I created. The benefit is that they are fast to read.

## Alternative workflow
1. Copy my comment with the drawings 
2. Under each drawing you add a table like so:

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 103 | 105.6 |
| 30 | 30.11 |

I actually think this method is faster for both ends.

**Comment by VillageMichaelLin** [comment]
I prefer the alternative workflow.

**Comment by tcaswelch** [comment]
![hdplex 160w dc](https://cloud.githubusercontent.com/assets/19661620/15995808/846a4ce0-30d5-11e6-9414-b8777e44bcaf.png)

**Comment by VillageHubertChen** [comment]
@VillageMichaelLin 
1. Transfer the dimensions of the PDF's already uploaded
2. Transfer the dimensions of the picture above
3. Create a new comment based on my comment with all your drawings
   - delete the drawings which you now have updated dimensions
   - for the drawings which dimensions you need to confirm, please place an empty table as per my example under it. All they need to do is fill in the table.

**Comment by VillageMichaelLin** [comment]
@VillageHubertChen Done

## 160W AC-DC pictures

### Top View

![160w-ac-dc-topview](https://cloud.githubusercontent.com/assets/7278716/15862445/463d961a-2d02-11e6-9641-eb8bbc096e86.png)
160W-AC-DC-TopView.png

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 150 | 147.95 |
| 131 | 132.5 |
| 52 | 51.95 |
| 33.30 | 39.80 (33.54) |
| 6 | 5.97 |
| 3.50 | 3 |
| 6 | 5.97 |
| 144 | 138 (143.03) |

### Side View

![160w-ac-dc-sideview](https://cloud.githubusercontent.com/assets/7278716/15862458/4ffe26e2-2d02-11e6-85a4-dfa57e94f04e.png)
160W-AC-DC-SideView.png

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 150 | 147.95 |
| 131 | 132.5 |
| 40 | 40.10 |
| 5 | 1.25 |

## 160W DC-DC pictures

### Side View

![160w-dc-dc-sideview](https://cloud.githubusercontent.com/assets/7278716/15862570/ad6245a2-2d02-11e6-8650-458e439bf28d.png)
160W-DC-DC-SideView.png

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 31 | 30.64 |
| 25 | 20.60 |
| 19 | 8.55 |

## 250W DC-DC pictures

### Top View

![250w-dc-dc-topview](https://cloud.githubusercontent.com/assets/7278716/15862667/f6f177f6-2d02-11e6-9e68-d5cee2d75051.png)
250W-DC-DC-TopView.png

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 150 | 149.97 |
| 122.12 | 122.14 |
| 51.50 | 51.29 |
| 3.70 | 3.65 |
| 6 | 3.36 |
| 43.29 | 43.72 |
| 4.10 | 4.31 |

### Side View

![250w-dc-dc-sideview](https://cloud.githubusercontent.com/assets/7278716/15862699/073008bc-2d03-11e6-95f4-c22e25815ea4.png)
250W-DC-DC-SideView.png

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 150 | 149.97 |
| 25 | 20.8 |

**Comment by VillageHubertChen** [comment]
@bcaswelch @tcaswelch In above comments we added the missing power supply templates with guessed dimensions. All you need to do now is to double check the dimensions and enter the measurements in the tables under the pictures. This should save you time over taking a picture and draw the dimensions. In case you can not edit and update the above comment due to permissions, you should be able still access the markdown source code and copy it into a new comment in which you modify the table entries.

**Comment by VillageMichaelLin** [comment]
## 250W-DC-DC-InputPowerPCB

### Front View

![250w-dc-dc-inputpowerpcb-frontview](https://cloud.githubusercontent.com/assets/14145153/16143426/53c66376-349f-11e6-90ed-3af30de6f791.png)

250W-DC-DC-InputPowerPCB-FrontView.png

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 11.20 | 10.94 |
| 20 | 20.01 |
| 4 | 4.47 |
| 5 | 5.38 |
| 32 | 31.55 |

### Side View

![250w-dc-dc-inputpowerpcb-sideview](https://cloud.githubusercontent.com/assets/14145153/16143442/683b8818-349f-11e6-9cec-840f234ad3aa.png)

250W-DC-DC-InputPowerPCB-SideView.png

| Drawn by V²Core | Measured by V²Shop |
| :-: | :-: |
| 10 | 11.08 |
| 23.5 | ? |
| 30 | 18.88 |

**Comment by bcaswelch** [comment]
Tracking updated today: scheduled to be delivered this afternoon. Will update for 250w dimensions.

**Comment by VillageHubertChen** [comment]
Thanks for the update! Please post a short note once done, so I can check if we have any other questions. Production is gated by these numbers and I want to make sure Michael can start on these first thing Monday morning.

**Comment by VillageHubertChen** [comment]
@VillageMichaelLin HDPLEX shipped the small type. Please change drawing accordingly. Bobby said they received the shipment. If by Monday morning you still do not see the updated dimensions, please let me know ASAP so I can trigger Bobby to deliver updated dimensions ASAP.

**Comment by bcaswelch** [comment]
Note- Some of the dimensions are inconsistent; the length on the right side may be a bit different from the length on the left side. Something to factor in and could be problematic.

**Comment by VillageHubertChen** [comment]
We can see the dimensions you measured and we will factor this in. If there is a concern in terms of dimensions that is not expressed with the measurements you made and posted in the tables above, then please spell it out in your comment.

**Comment by bcaswelch** [comment]
Were using a digital scale and these are the closest well get to the dimensions of what we have; the question is whether every single piece is going to be the same. So long that the design has some minor breathing room it should be fine.

**Comment by VillageHubertChen** [comment]
We are leaving several mm breathing room to the outside dimensions. The mounting holes need to be the same with tolerances of +/- 0.1 mm. But this would be a commonly agreed standard, as otherwise mounting holes would not work for the purpose of mounting. As such I think all is in the deep green ( as in very safe).

**Comment by bcaswelch** [comment]
okay, good to hear

**Comment by VillageHubertChen** [comment]
Did you now updated all dimension for all parts? Please confirm. If so your job is done here and we will take over from here. Thanks so much!

**Comment by bcaswelch** [comment]
Not quite yet, still have a couple to update. Going to do that now.

**Comment by VillageHubertChen** [comment]
OK. We will have our lunch now. When done, please ping on skype so I can check.

**Comment by VillageMichaelLin** [comment]
@bcaswelch Thanks for the update! I have three questions:
- [x] 1.In the top view picture of 160W AC-DC powersupply, Two measurements from you: 39.80 and 138 are about 6 mm different from the spec of HD-Plex. The spec of HD-Plex are 33.30 and 144. Can you double check these two measurements?
- [x] 2. In the side view picture of 160W DC-DC powersupply, the table is empty.Do you have any problem  for measuring? Or you will update this table?
- [x] 3. In the front view picture of 250W-DC-DC-InputPowerPCB, What is the meaning of the question mark? Do you have any problem to do this measurement? The meaning of the measurement is the distance between the center points of the two mounting holes. In the spec of HD-Plex, it is 20 mm. Can you update this measurement?

**Comment by bcaswelch** [comment]
@VillageMichaelLin 

Updated the tables. Thanks for catching the errors in number one, not sure how I didn't see those. The right number is in the ( ).

![img_20160619_233441903](https://cloud.githubusercontent.com/assets/16950279/16185186/d9e2a77a-3676-11e6-946c-d53173dc9ffa.jpg)

This is a top side view of the 160w AC-DC, just wanted to let you know that the screw mounts are open and not closed.

**Comment by VillageHubertChen** [comment]
@bcaswelch Thanks for the update. Michael has included all changes. He is posting today all reworked final drawings for you to double check.

**Comment by VillageMichaelLin** [comment]
@bcaswelch Here is the latest drawings. Please double check them, Thank you

## 80W-AC-DC

### Top View

![80w-ac-dc-topview-v2](https://cloud.githubusercontent.com/assets/14145153/16253755/c978906a-386b-11e6-9d01-8371f7ee535a.png)

### Side View

![80w-ac-dc-sideview-v2](https://cloud.githubusercontent.com/assets/14145153/16253782/fc5174c0-386b-11e6-911e-f4930ad77e89.png)

## 160W-AC-DC

### Top View

![160w-ac-dc-topview-v2](https://cloud.githubusercontent.com/assets/14145153/16253787/18bf0d98-386c-11e6-8995-7f94835b61d8.png)

### Side View

![160w-ac-dc-sideview-v2](https://cloud.githubusercontent.com/assets/14145153/16253773/e85f80b0-386b-11e6-9cef-89815e9925a6.png)

## 160W-DC-DC

### Top View

![160w-dc-dc-topview-v2](https://cloud.githubusercontent.com/assets/14145153/16253803/356aea02-386c-11e6-8d2a-267e5b123636.png)

### Side View

![160w-dc-dc-sideview-v2](https://cloud.githubusercontent.com/assets/14145153/16253823/58b56ae6-386c-11e6-935f-ec7167b67487.png)

## 250W-DC-DC

### Top View

![250w-dc-dc-topview-v2](https://cloud.githubusercontent.com/assets/14145153/16253839/711de9a0-386c-11e6-978e-704abc07cb55.png)

### Side View

![250w-dc-dc-sideview-v2](https://cloud.githubusercontent.com/assets/14145153/16253843/7923aba8-386c-11e6-8c42-71a6813d571e.png)

## 250W-DC-DC-InputPowerPCB

### Front View

![250w-dc-dc-inputpowerpcb-frontview-v2](https://cloud.githubusercontent.com/assets/14145153/16253848/9032cf7c-386c-11e6-8eaf-d89130fb16cc.png)

### Side View

![250w-dc-dc-inputpowerpcb-sideview-v2](https://cloud.githubusercontent.com/assets/14145153/16253852/9e8aa784-386c-11e6-86d0-e67d8e97b206.png)

**Comment by bcaswelch** [comment]
@VillageMichaelLin 

PIctures all appear to be in order!

**Comment by VillageHubertChen** [comment]
@bcaswelch Thank you for the quick response. I just found there was a big misunderstanding between Michael and me. Our drawing should represent the *_Standard_ Dimensions. Your measurements represent verification measurement demonstrating production tolerances, which should be in the range of +/- 0.1 mm. Michael will have to redo the drawings and check that all you measurements are within these tolerances and update the dimensions to the spec. Where you real world sample differ significantly, we will update accordingly.

@VillageMichaelLin Please read above and trigger me for review once you made the snapshots but before processing and uploading
