### ISSUE TITLE
V² > DIY > Parts > CPU

### ISSUE THREAD

**Issue by bcaswelch** [V-Squared/V-Squared.github.io#137]
# Tasks
## Create

Creating Infrastructure, Titles and Basic Article Content.

https://github.com/V-Squared/V-Squared.github.io/issues/141
- [x] [Create Article Issue](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224530286)
- [x] [Insert DIY Article Issue Template](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224551488)
- [x] [Set Title, Subtitle & Abstract](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224551124)
- [x] Copy article from → [Wiki Pages](https://github.com/V-Squared/v2-How-to-DIY-Mini-PC/wiki)
- [x] [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) by setting to _Create-Active_
- [x] [Cleaning Up Kramdown Code](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522530)
- [x] [Linking Issues to Articles](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522429)
- [x] [Link Article to Issue in Reference](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224544881)
- [x] Collect any writing Materials from other places to here
- [x] [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to:
  - **Create-Complete:** if you plan to stop working on this article at this time.
  - **Develop-Active:** if you will continue working on this article immediately hereafter.
## Develop

Develop the Article so that to the Developer and Editors think that it is complete.
- [x] [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to: **Develop-Active**
- [ ] **Table of Contents & Structure**
  - [ ] [Creating a Table of Contents](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522504)
  - [x] [Restructure Article](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224548669)
  - [ ] [Add Permalinks](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224549052)
- [ ] [Add Visual Placeholders](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224549597)
- [ ] **Develop** [Article Review](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224550285)
  - [ ] Trigger TC for Develop Review
  - [ ] TC: Develop Review
  - [ ] BC: Include Feedback Develop Review
- [ ] [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to:
  - **Beta-Active:** if you will actively pull in editor's comments
  - **Beta-Passive:** if you want to keep the Article published in this state for some time to see any comments coming in.
## Beta

Community Review
### Active Beta Testing

Push known editors to quickly provide reviews to move Readiness from Beta → Make
- [ ] If not done already, do → [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to: **Beta-Active**
- [ ] Trigger TC to _Beta Review_ by posting in comment: "# Request Beta Review" with @mentions
- [ ] TC: Beta Review. Then trigger author by comment: "# Review Complete" with @mentions
- [ ] Include review feedback
- [ ] Trigger HC to _Beta Review_ by posting in comment: "# Request Beta Review" with @mentions
- [ ] HC: Beta Review. Then trigger author by comment: "# Review Complete" with @mentions
- [ ] Include review feedback
- [ ] [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to: **Make-Complete**
### Public Beta Testing

Announce to community, then incorporate all feedback as it comes in. 
- [ ] If not done already, do → [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to: **Beta-Community:**
- [ ] Incorporate feedback as it comes in
- [ ] After 30 days set → [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to: **Make-Complete**
## Make

This Article is in Production and underwent extensive Reviews. We continue to incorporate community improvements.
- [ ] If not done already, do → [Setting Readiness Bar](https://github.com/V-Squared/V-Squared.github.io/issues/141#issuecomment-224522565) to: **Make-Complete**
# Specific tasks to this Article
# Reference
- [V²►Parts ►CPU](https://v-squared.github.io/diy/parts/cpu/)

**Comment by VillageHubertChen** [comment]
# Bobby reported problem of Table formatting

I fixed the two problems. It is very easy to do:

## Problem 1: Table does not render like table but as messy text

You must have a leading empty line in front of the table, see Code Example.

## Problem 2: Table Styling is not nice

You need to add a class to the table, see Code Example.

# Code Example

### Bad Kramdown

```
### CPU Benchmarks
|CPU Name         |Benchmark|
|----------------:|:--------|
|Sempron-2650|900|
|Athlon 5350|2600|
```

### Good Kramdown

```
### CPU Benchmarks

{:.uk-table.uk-table-hover}

|CPU Name         |Benchmark|
|----------------:|:--------|
|Sempron-2650|900|
|Athlon 5350|2600|
```

**Comment by VillageHubertChen** [comment]
# Please give feedback to Tasks

@bcaswelch I created a template for tasks for an Article. It is very structured, helping everybody (Author, Editor, Reader, Agile Team Member) to keep an overview of where the progress is on the _Article_. It also ensures that certain tasks won't be forgotten.

Please give me either an OK or a _Change List_ in your comment. Then I will use this as template for all other issues.

**Comment by VillageHubertChen** [comment]
# Can you tick task boxes?

@bcaswelch Please test and report to me if you can tick the boxes in tasks in the top comment?

**Comment by bcaswelch** [comment]
Yes I can tick the boxes

**Comment by VillageHubertChen** [comment]
@bcaswelch Great! Thanks for letting me know.

I realized that I can combine workflow, task list and documentation in a simple yet powerful way. Please see above the Task List as a prototype. Once this workflow / to do list is completed the instructions on how to do a task are only one click away. And once you remember how to do things the instructions are always out of the way.

This was too much work to finish today, I will complete it tomorrow. Once done you should have all instructions that you need to know to finish writing an Article from beginning to end.

Please review what I already completed, especially regarding if steps are missing.

**Comment by VillageHubertChen** [comment]
@bcaswelch I changed assignments, as your work is finished for now and I am working full time on the Task-Workflow-Docu Hybrid on this one.

**Comment by bcaswelch** [comment]
@VillageHubertChen 

Updated article, Could you do a quick review for how its looking so far? I still need to fix some formatting but want to know how the content is.

**Comment by bcaswelch** [comment]
Information updated, still need to update the table of contents and images. Rest is done.

**Comment by bcaswelch** [comment]
Updated and ready for your review, the TOC is still a work in progress (shows usable in classeur but on on the website).

**Comment by VillageHubertChen** [comment]
# Parked Notes

For when we continue writing here:
- Write new Introduction: Consider new situation & V²Shop
- Create [Manual Table of Content](https://v-squared.github.io/plan/flow/publishing/appetizing/#manual-toc)
- Add Art Space Holder
- Write new Jumbotron. Turn this into a White Paper Used in Reference with Configs and Configurator
