### ISSUE TITLE
V² > DIY > Intro > Custom-PC

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#139]
# Tasks
## Create
- [x] Create issue to this article with _Path_ in issue name
- [x] Copy article from → [Wiki Pages](https://github.com/V-Squared/v2-How-to-DIY-Mini-PC/wiki)
- [x] Set _Readiness_ to _Create_
- [ ] Clean up Kramdown Code
  - [ ] Add lines between headings
  - [ ] Add lines in front of code blocks, such as tables
  - [ ] Change URL in tables to use _Referenced Links_
- [x] Link Issue to Article
- [x] Link Article to Issue in Reference
- [ ] Collect any writing Materials from other places to here
- [ ] Set _Readiness_ to _Develop_
## Develop
- [ ] **Table of Contents & Restructuring**
  - [ ] Add automatic _Table of Contents_
  - [ ] Restructure writing if need be
  - [ ] Add manual anchors and switch _Table of Contents_ to manual anchors
- [ ] **Update content**
  - [ ] If we reference to parts, find up to day parts
  - [ ] If ViCase or our philosophy changed, update it
- [ ] **Visual Placeholders**
  - [ ] Add text placeholder for graphics using _Code Block_ 
  - [ ] or find suitable placeholder graphics on the internet and edit to size: 853 x 480 px
  - [ ] Set Readiness to _Beta_
## Beta
- [ ] Trigger HC to _Beta Review_ by posting in comment: "# Request Beta Review"
- [ ] HC: Beta Review
- [ ] Include review feedback
- [ ] Finalize graphics as per feedback
## Make
- [ ] Trigger HC to _Make Review_ by posting in comment: "# Request Make Review"
- [ ] HC: Make Review
  - [ ] HC: Get feedback from at least one external editor
- [ ] Include review feedback
- [ ] Trigger HC to _Final Review_ by posting in comment: "# Request Final Review"
- [ ] HC: Make Final Review
- [ ] HC: Set _Readiness_ to _Make_
# Specific tasks to this Article
# Reference
- [V²►Compare►Custom-PC](https://v-squared.github.io/diy/compare/custom-pc-comparison/)

**Comment by bcaswelch** [comment]
Looks good, I'll work on adding more writing to the article.

**Comment by VillageHubertChen** [comment]
@bcaswelch Thanks. I wish you smooth writing. I will finish the project of Epic►015►Parent: Compile Know How►Writing Articles #141 first and when done will create all Article Issues and equip them with the new Task List and trigger you to set the check box ticks accordingly. This will be your (very fast and efficient) handover to you for my reviewing your writing.

**Comment by bcaswelch** [comment]
Okay
