### ISSUE TITLE
Epic > 015 > Parent: Compile Manual > Writing Articles

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#141]
- [x] Create Workflow Compiling Know How
- [x] Find the spot where to publish → #82 
- [x] Create Linked List of Articles
- [ ] Keep writing know how in here, until we are ready to publish
- [ ] Move this Article Series to its final resting place:
  -  V²►Plan►Flow►Articles►Task-Template
- [ ] Rework existing tasks to update links to new location of documentation
# Workflow Compiling Know How
- Each article is filed in a separate comment, this makes editing manageable
- This comment contains a linked _List of Articles_, this keeps an overview
- Once we a) create V²Spreading and b) have completed compiling we move these comments to Articles in the final resting Place →  V²►Spreading►Know How►Writing Articles → #82 
# Shortcut to Learning
## Manually now, Automated Later
# List of Articles on Writing Articles
- [Create Article Issue](#issuecomment-224530286)
- [Insert DIY Article Issue Template](#issuecomment-224551488)
- [Set Title, Subtitle & Abstract](#issuecomment-224551124)
- [Linking Issues to Articles](#issuecomment-224522429)
- [Link Article to Issue in Reference](#issuecomment-224544881)
- [Styling Tables](#issuecomment-224522457)
- [Creating a Table of Contents](#issuecomment-224522504)
- [Cleaning Up Kramdown Code](#issuecomment-224522530)
- [Setting Readiness Bar](#issuecomment-224522565)
- [Text Includes for Redundant Text](#issuecomment-224522593)
- [Using Referenced URL](#issuecomment-224528850)
- [Restructure Article](#issuecomment-224548669)
- [Add Permalinks](#issuecomment-224549052)
- [Add Visual Placeholders](#issuecomment-224549597)
- [Article Review](#issuecomment-224550285)
# Reference
- → https://github.com/V-Squared/V-Squared.github.io/issues/117

**Comment by VillageHubertChen** [comment]
# Linking Issues to Articles

**Comment by VillageHubertChen** [comment]
# Styling Tables

**Comment by VillageHubertChen** [comment]
# Creating a Table of Contents
- [ ] LC: Turn on Automatic Table of Contents in the Article → [V²►DIY►CPU](https://v-squared.github.io/diy/parts/cpu/)
- [ ] LC: Document in here all steps on how to do just that

# Reference
- → [kramdown►Automatic “Table of Contents” Generation](http://kramdown.gettalong.org/converter/html.html#toc)
- → [stackoverflow►Customize ToC in Jekyll](http://stackoverflow.com/questions/20890654/customize-automatically-generated-toc-on-jekyll-kramdown-site)
- → Automatic Table of Contents Generation #130

**Comment by VillageHubertChen** [comment]
# Cleaning Up Kramdown Code
- [x] Add lines between headings
- [x] Add lines in front of code blocks, such as tables
- [ ] Change URL in tables to use _Referenced Links_

# Difference between Kramdown and GitHub Markdown

## Reference

# Rules to make both Markdown Dialects Happy

**Comment by VillageHubertChen** [comment]
# Understanding Readiness Bar

At this point (and for 

# Setting Readiness Bar

## Location

## Purpose

## Logic

## Tooltips

# States of Readiness Bar

## Scheduled

## Create-Active

## Create-Complete

## Develop-Active

## Develop-Complete

## Beta-Active

if you will actively pull in editor's comments

## Beta-Passive

Keep the Article published in this state for some time to see any comments coming in.

## Make-Active

**Note:** Items which requite ongoing activity in production will be set to _Make-Active_. Example would be hardware products, such as ViCase. If you were to set the ViCase product page to _Make-Complete_ you would indicate that it has reached its end of life.

## Make-Complete

**Note:** Items which only require a one time activity to put it into the _Make_ state forever will be set to _Make-Active_. Example would be publication of an article on our site.

**Comment by VillageHubertChen** [comment]
# Text Includes for Redundant Text

**Comment by VillageHubertChen** [comment]
# Using Referenced URL

**Comment by VillageHubertChen** [comment]
# Create Article Issue

# Workflow
1. Get Mating Issue Name
   - Open Article
   - Press Clipboard 1 Icon to copy the Article Path
2. Create Issue
   - Open → [V²►V-Squared.github.io►Issues](https://github.com/V-Squared/V-Squared.github.io/issues)
   - Create New Issue
   - Paste Article Path in Issue Title
   - Paste Issue Template in "Leave a comment"
3. Classify Issue
   - Set Labels
   - Set Milestone
   - Set Assignee
4. Submit new issue

## Quality Check
- Article Path and Issue Title Match
- All Labels, Milestone, Assignee set

# How does this Fit into the Big Picture

## Assist Writer

## Assist Editor

## Assist Reader

## Assist Searching

**Comment by VillageHubertChen** [comment]
# Link Article to Issue in Reference

**Comment by VillageHubertChen** [comment]
# Restructure Article

**Comment by VillageHubertChen** [comment]
# Add Permalinks

**Comment by VillageHubertChen** [comment]
# Add Visual Placeholders
- [ ] **Visual Placeholders**
  - [ ] Add text placeholder for graphics using _Code Block_ 
  - [ ] or find suitable placeholder graphics on the internet and edit to size: 853 x 480 px

**Comment by VillageHubertChen** [comment]
# Article Review
- [ ] Trigger TC for Develop Review
- [ ] TC: Develop Review
- [ ] BC: Include Feedback Develop Review
- [ ] Set Readiness to _Active Beta_

# Preflight Checklist

**Comment by VillageHubertChen** [comment]
# Set Title, Subtitle & Abstract

**Comment by VillageHubertChen** [comment]
# Insert DIY Article Issue Template
