### ISSUE TITLE
Epic > 016 > Parent: Developing V²Flow

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#147]
# Tasks
- [x] Find GitHub Flow Help Page → https://guides.github.com/introduction/flow/  ← Great Read!
- [ ] Read (Write first) → My experience GitHub Flow versus others → Define: Making contribution easy for anyone! #149 (Link to here once the writing is done)
- [ ] Create V²Flow in V²Plan
  - [ ] Possibly move V²Art into V²Plan > V²Flow > V²Art, as it is mostly workflow information
  - [ ] Create → Add Article-Group to Navigation (V²Flow, V²Art, V²Agile)
# Reference
- →  Define: Making contribution easy for anyone! #149
