### ISSUE TITLE
Define: Making contribution easy for anyone!

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#149]
# Tasks
- [x] Spell out definition for: V²Site is a GUI for Developing on GitHub
- [x] Find GitHub Flow Help Page → https://guides.github.com/introduction/flow/  ← Great Read!
- [x] Review with BC and TC
- [ ] HC: Write my experience GitHub Flow versus others (Write as separate comment)
- [ ] Link this to the Introduction of V²Home Page. Make this a feature in the feature section.
- [ ] Spell out changes due to this new concept

---
# Definition
- **Title:** Making contribution easy for anyone!
- **Subtitle:** The V²Site is a GUI on top of GitHub to simplify and guide community development.
# Sub Items
## V²Plan

The plan of our V² community. A system that extracts from the far away True North Target down to what to do today by a process of 7 layer expansion.
## V²Agile

Agile Development and Production System for GitHub Organizations. It's features begin where GitHub features end.
## V²Template

V²Template powers V²Site and delivers fully responsive design so that you can develop on any device and screen size any where. Written in Liquid for Jekyll compatible to GitHub Pages web hosting.
## V²Flow

Workflow system to guide development of know how and standard articles. Simplify collaboration while increasing consistency of a large body of work.
# Hero Pages
## https://github.com/
- need to be logged out
- → Welcome home, developers
## https://github.com/open-source
- → Join the community
## https://github.com/business
- → Tailored for enterprise
# Reference
- → Developing V²Flow #147

**Comment by bcaswelch** [comment]
Will keep an eye on it

**Comment by VillageHubertChen** [comment]
@bcaswelch Hi, actually nice you have an eye on this one. I will talk to you in the daily meeting :-)
