### ISSUE TITLE
Add Article-Group to Navigation

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#153]
# Tasks
- [x] HC: Write → Function of Article Group → below
- [x] LC: Implement by → [Grouping V²Plan System Articles](https://github.com/V-Squared/v-squared.github.io/issues/54#issuecomment-225423662), then trigger HC for testing
- [x] HC: Test
- [x] Write / update documentation → [YAML file for Book-Bar](https://github.com/V-Squared/V-Squared.github.io/issues/47#issuecomment-218051115)
# Gating What

 V²Flow.Art & V²Flow can not be created without Article Groups
# Function of Article Group
- Groups Articles in the Article Bar
- Function is described in References below
# References
- Epic►005►Parent: Compile Know How►GitHub Template #48 
- Epic►001►Navigation Bar System v3 #47 
- Library Metaphor for V² Navigation #44
