### ISSUE TITLE
Restructure & Rename V²Agile System

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#155]
# Gated by:
- [ ] LC: Implement new structure
  - [ ] LC: [Grouping V²Plan System Articles](https://github.com/V-Squared/v-squared.github.io/issues/54#issuecomment-225423662)
  - [ ] LC: →  Add Article-Group to Navigation #153 
# Tasks
- [ ] Double check article titles
- [ ] Update links to new article locations
- [ ] document how to do in →  Epic►005►Parent: Compile Know How►GitHub Template #48
