### ISSUE TITLE
Epic > 018 > Parent: Cowrite DIY Articles

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#156]
# Specific Tasks to this Article
- [x] BC: Create Titles and Abstract for each Book Intro Page
- [ ] HC, ML: → Epic > 018: Create Title Graphics for all DIY Books #187
- [ ] HC: → Epic > 018: Create all Book Introduction Pages #188 
- [ ] LC: → Epic > 018: Automatically generate Index to DIY Books #189 
- [ ] HC: Break out the Generic Tasks into independent issues
# Generic Tasks for this Board
- [ ] Edit BC's writing
- [ ] Brainstorm on improving the Article
- [ ] Brainstorm if current structure is the best
- [ ] Brainstorm on where to put which kind of visuals, edit visual place holders
  - [ ] Use Code Text Made fields. If do not know how, ask HC to create an example
- [ ] Replace Text Place Holders with Internet Place Holder Images
  - [ ] Find placeholder images on the internet
  - [ ] do crop / scale to size and aspect ratio
  - [ ] upload into comment of corresponding Article Issue
  - [ ] pick markdown reference to uploaded image and place it into Article in final position
- [ ] Research Competition
  - [ ] Check if the models from my original market research are still the latest models
    - [ ] Update if needed. Also check if new competition with even better models showed.
  - [ ] Update competition pricing
  - [ ] Add or update links to competition (their online shop and their spec pages)
- [ ] Perform reviews for stages: Create, Develop, Beta. Bump Article Readiness accordingly
- [ ] Add cross links in Article Series where appropriate.
  - My guess is that in average one Article may have 5 cross links to other Articles in this series
- [ ] Read Article Series in one sitting using the eyes of a new reader
  - [ ] How does the series flow? We are not assuming know how that we only introduce later ?
  - [ ] Is structure of series logical?
- [ ] When doing research, write down places on the internet where we could go in and announce one or several articles. This is an important list that we need start promoting the article series. The idea is that a certain amount of traffic will convert into (pre) sales, once the V²Shop-Midwest is online.
# Synergies

All Know How in these Articles are very useful if not needed to assemble ViPC and to answer basic questions to a ViPC customer in the V²Shop-Midwest. American customers will appreciate almost instant answers. As such it is not expected that Bobby will be able to answer customer's questions in the shop. After you co-wrote these Articles you should be able to answer 95% of questions. You will answer in the following way:
1. Find the relevant place in our DIY Articles
2. Check it has an anchor. If not, add the anchor
3. Check it answers the customer's question. If not modify or add to writing until it does
4. Reply customer with link to the place answering his question

This workflow has the following benefits:
1. Our DIY Articles will grow with use
2. Every customer asking question is pointed to the DIY Articles. Chances are some will start reading and stop asking more questions. Those customers who start reading are likely to buy a PC
3. Customers who are of the true DIY type will find these Articles useful and possibly tell others. This is the begin of the viral marketing fishnet function of these articles.
4. Filtering function of trouble customers. Those customers who keep asking questions which are easy to find the answer in the articles are possibly customers who will drive you nuts after you sold them a ViPC. This procedure will help you to develop feelings for which customers to sell to and which one to pass up, as chances are the ViPC will come back anyways with complaints on top.
# Notes on Marketing DIY Article
- Google Advertisement
- Quora
## \- Lightworks Forum
# Reference
- → [V² > DIY](https://v-squared.github.io/diy/)
