### ISSUE TITLE
V² > DIY > Intro > Workstation

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#157]
# Specific Tasks
## Bar Graphs
- [x] HC, BC: Brainstorm on developing expressive bar graphs
- [x] BC: Create expressive bar graphs → GREAT JOB !
- [ ] BC: Create chapters to use the expressive bar graphs (see below)
- [ ] LC: Replace rendered bar graphs with automated bar graphs, once LC completes →  Automated / Automatic Bar Graph in Articles #173 
## Update competition models and pricing
- [x] Research if models of competition are still their latest → nope, they changed
- [x] update pricing
- [x] add or update links to their Shop Page and their Spec Page
- [x] Create snapshots of their configurations
- [x] @bcaswelch The price percentage of [ViPC 1200 vs HP Z1 G3](https://v-squared.github.io/diy/compare/workstation-comparison/#vipc-1200-vs-hp-z1-g3) is not correct
## Good looking / fast to ingest comparison tables
- [x] LC: Build a rapid prototype for table to color good = red, bad = no
- [x] BC: Give feedback to HC on above table styling
  - discuss options to keep tables HTML to put into YML front matter
- [ ] HC: Write final specs on table styling
  - pick exact highlight color
  - make list of all colors: {bl}, {rd}, {gn}, {or}, {yw} {gy}
  - combine with advanced styling of rest of table
  - mobile layout: Scroll bar
- [ ] LC: Implement table styling, trigger HC for review
## New Structure
- [x] HC: Create new structure
  - Comparison Summary (Highlights of Spec, Price, Usability Compare + grand conclusion)
  - Spec Comparison
  - Price Comparison
  - Usability Comparison <- Our key impact
  - Technical Background (i7 vs Xeon)
- [x] HC: Review new structure GI → Approved. Feedback already updated in above structure
- [x] HC: Review new structure SL → Approved. Feedback already updated in above structure
## Styling
- [ ] LC: Advanced table styling. See above.
- [ ] HC: Add accordion folding for Configurator Screen Snaps (Talk to HC on specs)
## Write Usability Comparison Chapter
- [x] HC: Write template, considerations and example → [V2 > DIY > Compare > AiO Comparison #192](https://github.com/V-Squared/V-Squared.github.io/issues/192#issuecomment-228505115)
- [ ] BC: Write this chapter based on above template. Modify content so to apply to Workstations. Then Trigger HC for review
- [ ] HC: Review new "Usability Comparison Chapter"
- [ ] BC: Include HC's feedback
## Write Conclusion
- [ ] BC: Create 4 Sections of this Chapter:
  - Spec Comparison Conclusion
  - Price Comparison Conclusion
  - Usability Comparison Conclusion
  - Grand Conclusion
- [x] Each section gets one key graphics
  - Either colored bar graph
  - colored feature comparison table (very few if not one feature only, create new composite feature)
- Grand Conclusion is short text, written very high level. According to current research it would be appropriate to say: In terms of Performance, ViPC can be configured to match various workstation performances 100%. As for price it is slightly lower cost. But as for usability ViPC is head and shoulders ahead of the competition. It's aggressive innovative design introduce lots of new features or re-introduces features that were available in yesteryear but seems to be forgotten in the industry. Things as simple yet profoundly useful such as a carry grip.
## Visuals
- [ ] BC: Convert tables to Lucas' new format
- [ ] BC: Create placeholders for visuals. Use the style as in → [V2 > DIY > Compare > AiO Comparison #192](https://github.com/V-Squared/V-Squared.github.io/issues/192#issuecomment-228505115)
- [ ] HC: translate placeholders to our internal create graphics process
- [ ] ML: Render visuals
- [ ] HC: Process visuals, upload and include in article
## Misc
- [ ] BC: Add Table of Contents
- [ ] LC: Create Accordions for Configuration Snapshots
## Tasks after first Review
- [x] BC: Split this Article into two Articles
  - [x] Desktop Workstation Comparison
  - [x] AiO Workstation Comparison (new) 
  - → [ ] BC: Read: [Adding Articles](https://v-squared.github.io/plan/flow/writing/adding-articles/)
  - → [x] BC: Create Issue: V2 > DIY > Compare > AiO Comparison #192 
- [x] BC: Add bar graph for size in Liters
- [x] BC: Add bar graph for power density in Liters
- [x] BC: Create Key Feature section on top of Article
## New Key Feature Section
- Best Balance
- Price: Bargraph (order in cost, color red, yellow, green)
- Power: Density  (Power [W] / Liters)
- Fluid Formfactor
- Portability
- Clean Wiring / Clean Table
- Power Protection & EMI
- Easy Access
# Reference
- [V² > DIY > Compare > Workstation](https://v-squared.github.io/diy/compare/workstation-comparison/)

**Comment by VillageHubertChen** [comment]
@bcaswelch @tcaswelch 

Please complete this Article First. We had a meeting on it and I spelled out the tasks already.

Bobby: Please make sure that Tom gets notifications. Check with this one. Show him how to use. Please clean up the issue: #118 in this regards. If Tom can not get or use notifications, work will be lost.

**Comment by bcaswelch** [comment]
## Single table workstation comparison

The idea is to have one single table instead of piles of tables in the page. This keeps the article shorter and gives the important info all in one area. 

The idea is to half a similar looking table, but tabs within one table that switch each of the competing workstations. So the ViPC specs would stay the same but people could switch tabs between other computers to see how it compares.

**Comment by VillageHubertChen** [comment]
I am not sure it is important to make the Article shorter. If the content is interesting to the reader he will continue scrolling down. He will reach the end of an even very long Article, **if** he finds it interesting all the way. 

From that perspective my approach is to increase interest. And to make it very fast to capture the ideas. This way the reader can skim through the article the first time and recognize that there are many graphics he can understand instantly. Then he would go back to read a second time. 

As per your request, Lukas can possibly program a table like that. The best way is that you find us a table that is exactly what you want with the behavior you want. Then we can copy that design and provide it to you.

Another approach is to search the internet for comparison articles you like. See how they are doing it. Check with others which article structure and visual representation is liked best by most. Then take this design and redo it with our content.

If you have candidates, please post URLs in the comment. I can cast my vote which one I like and I can give you feedback which features and behaviors we can and which one we can not do.

As for your idea with the tabbed table: What we can do for sure is give you tabs for content. So you can put in each tab one table with three columns: 1) Features, 2) ViPC, 3) Third Party. The first three columns always stay the same. The third column changes with the PC. Below the table you could than have the specific comparison text, which changes for each third party as well.

This approach could have a benefit over long scrolling, as that you can switch back and forth between different third party PCs.

This all will go smoother if you have example pages you can show.

I am tiered as hell, but I will try hard to stay awake until 9 am your time. Is there a chance you could post me Tom's phone number? So in case next time you oversleep or forget that I can reach Tom and he can get you in front of skype? Would that work?

**Comment by bcaswelch** [comment]
![workstationgraph](https://cloud.githubusercontent.com/assets/16950279/16318048/1a881440-3942-11e6-9660-f5e78d60d0e7.png)

![workstationcomparison2](https://cloud.githubusercontent.com/assets/16950279/16318055/23b4897c-3942-11e6-97ff-ebf0e0983634.jpg)

**Comment by bcaswelch** [comment]
![workstationimages3](https://cloud.githubusercontent.com/assets/16950279/16323492/0a93acf2-3960-11e6-9c70-d3b707ad490f.png)

**Comment by bcaswelch** [comment]
Hmm these take up a ton of space.. Any tips on shrinking them?

![dellconfig](https://cloud.githubusercontent.com/assets/16950279/16324912/ba4c6050-396d-11e6-937c-ded51b253e34.png)
![hpg3specguide](https://cloud.githubusercontent.com/assets/16950279/16324913/ba4d0532-396d-11e6-99d3-b0182ed3d936.png)
![hpz240config](https://cloud.githubusercontent.com/assets/16950279/16324914/ba4dc198-396d-11e6-8e94-47675b1eaf01.png)

**Comment by VillageHubertChen** [comment]
# Discussion on shrinking arm long Config Snaps

@bcaswelch 

## Idea 1: Accordion

Under each workstation is a horizontal accordion menu. Folded is says: Configuration of xyz workstation. Unfolded it keeps the title, but it shows the entire snapshot. This works best to keep each reference close to each workstation occurrence.

## Idea 2: Reference Tabs
- **Name of Tabs:** "Configuration Snaps", "HP xyz", "Apple 123", "Dell abc", ...
- **Configurations Snaps:** This tab is short and gives intro to content of all other tabs
- **Remaining Tabs:** Each tab contains the arm long snap shot of the workstation's config
- **Each tab has deep link:** Thanks to some serious coding of Lukas each tab has a deep link anchor. Meaning under each workstation Article you have a link: "Verify the workstation configuration". Once clicked the article will: 1) Scroll down to the Reference Tabs 2) Open the corresponding tab

Let me know which idea you like or if you have a better one. I will then ask Lukas to implement it.

**Comment by bcaswelch** [comment]
@VillageHubertChen Idea 1 works with me, its a simple implementation and people can briefly open and close it with one click.

**Comment by bcaswelch** [comment]
![litersize](https://cloud.githubusercontent.com/assets/16950279/16327515/a6561f48-3984-11e6-802a-33b1d8b2c26d.png)
![pricecomparisonvipc](https://cloud.githubusercontent.com/assets/16950279/16327516/a6569022-3984-11e6-8330-97e1c22e4f35.png)

**Comment by bcaswelch** [comment]
![workstationpower](https://cloud.githubusercontent.com/assets/16950279/16353986/7251ea04-3a3a-11e6-9974-63c0ce74a915.png)

**Comment by VillageHubertChen** [comment]
Great job on the comparison charts! Huge compliments from Sascha too!

**Comment by VillageHubertChen** [comment]
@bcaswelch I completely updated the task list in the top comment. Please work it down. Ask questions when it is not clear. In the evening your time I usually answer your questions on skype within minutes..

Please be so kind to tick a task once completed. This helps you and me to keep the overview.

**Comment by bcaswelch** [comment]
@VillageHubertChen 

Added several of the new table layouts, will finish when I wake up.

**Comment by VillageHubertChen** [comment]
@bcaswelch 

Very good. We started documenting the advanced tables. We may finish tonight. As is it should already be useful → [Advanced Formatting](https://v-squared.github.io/plan/flow/writing/advanced-formatting/)

Update: We pretty finished. What is missing is listed in → #204 

We changed the syntax of the table in the yml front matter. Please refer to → [Advanced Formatting](https://v-squared.github.io/plan/flow/writing/advanced-formatting/). You will need to change your tables in here accordingly. Sorry about that. Upside is added control and features and improved layout. Please note the footer is not rendered yet, but you can start using it.
