### ISSUE TITLE
Automated / Automatic Bar Graph in Articles

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#173]
# Tasks
- [x] HC: Write User Story
- [ ] LC: Check if Made Mistakes uses generated graphs?
- [ ] LC: If no to above, search the internet on automated graphs in Jekyll and Markdown. I saw articles like these before
- [ ] LC: Pick 3 solutions and let HC proof read and help you to make final choice
- [ ] LC: Make a test implementation, show HC for review
- [ ] HC: Review. Once passed, write documentation, then hand over to BC, then close issue
# User Story

As **Author of DIY Articles** I need a lot of bar graphs to illustrate comparison of various performance values. This new features saves a lot of time. This is obvious when comparing my steps
## Steps before Automated Bar Graph
1. create a separate excel file
2. Enter the values
3. Generate the graph
4. Style the graph
5. Create a snap shot
6. Process snap shot
7. Then for publication I needed to create a folder structure in V²Art
8. Upload excel file and illustration
9. Link get the URL and link to the image in the Article
10. Proof read
11. ... 20 Find what I did wrong, curse and do it all again
## Steps now
1. Enter values in Front Matter
2. Enter markdown code at where the graph should show up
3. Save Article and Reload Page
4. Proof Read
5. Find what I did wrong, smile and fix it in the YML front matter. Done!
