### ISSUE TITLE
V² > Plan > Flow > Writing Articles > Intro

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#176]
# Tasks
- [x] Create Issue
- [x] Create Article
- [x] Create Title / Subtitle / Abstract
- [x] Enter Issue No in Article
- [x] Add Link to Article in Reference of this Issue
- [x] Automatically generate index → #191 
- [x] Trigger review
- [x] Include review feedback
- [x] set readiness to make
# Reference
- [V² > Plan > Flow > Writing Articles > Intro](https://v-squared.github.io/plan/flow/writing/intro/)
