### ISSUE TITLE
V² > Plan > Flow > Publishing > How-To Task-Templates

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#177]
# Tasks
- [x] Create Issue
- [x] Add Link to Article in Reference of this Issue
- [x] Create Article
- [x] Create Title / Subtitle / Abstract
- [x] Enter Issue No in Article
- [ ] Write Article
- [ ] Add cross references
- [ ] Trigger review
- [ ] Include review feedback
# Reference
- [V² > Plan > Flow > Writing Articles > How-To Task-Templates](https://v-squared.github.io/plan/flow/writing/how-to/)
