### ISSUE TITLE
V² > Plan > Flow > Mechanical Design > Intro

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#179]
# Tasks
- [x] Create Issue
- [x] Add Link to Article in Reference of this Issue
- [x] Classify Labels, Milestone & Assignee
- [x] Create a Take-Out of ViDrive CAD-CAM-CNC → `C:\Users\Mini\Pictures\Art\V²\Plan\Flow\mechanical`
- [x] automatically generate index → #191 
- [x] Create Title / Subtitle / Abstract
- [x] Enter Issue No in Article
- [x] Trigger review
- [x] Include review feedback
# Reference
- [V² > Plan > Flow > Mechanical Design > Intro](https://v-squared.github.io/plan/flow/mechanical/intro/)
- Take-Out of ViDrive CAD-CAM-CNC → `C:\Users\Mini\Pictures\Art\V²\Plan\Flow\mechanical`
