### ISSUE TITLE
Accordion Portfolio in V²Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#18]
# Benefits
- Easier to navigate on a mobile (scrolling is too long with home page as is)
- Easier to keep Overview on Mobile
  It also will improve to keep an overview on big screen
- Same code as with V²Configurator
- This type of folding navigation can become one of our trademarks
- On big screen it can be used in harmony with Site Bar Table of Contents
# Features
- **Help:** Explain how it works / different use models. Help as in V²Configurator
- **Collapse All / Fold All Button:** Toggle button, placed on top right beside Help Icon
- **Color Theme:** as in V²Configurator
- **Fold Icon:** as in V² Configurator
- **Unfold new closes old:** When unfolding new Section: 1) unfolding animation 2) scrolling up animation 3) previous section is closed (while being off screen). This greatly reduces scrolling.
- **Accordion is off on big screen:** → #19 Instead we are using Navigation Side Bar
# Hero Pages
1. [Plastics Unlimited►Hero Page Accordion on Home Page](http://www.plasticsunlimited.com/capabilities)
2. https://www.microsoft.com/de-de/server-cloud/products/windows-azure-pack/Features.aspx
3. http://v-squared.github.io/v2-Configurator/
# Tasks
- [x] SL: Prepare concept and propose to HC. Find Hero Page.
- [x] HC: Create issue
- [ ] @LukasChen Create first implementation, then get HC feedback. We go from there.

**Comment by georgillies** [comment]
+1

**Comment by VillageHubertChen** [comment]
# Changing to Tabbed Slide Show

We are abandoning the Accordion Navigation after we implemented the Integration with the Puzzle. The reason is that the User Experience was too confusing due to too much scrolling and searching. For more details on this problem and the solution to it, please refer to →  #35  Changing Accordion to Tabbed Slide Show
