### ISSUE TITLE
V² > Plan > Flow > Mechanical Design > Choosing CAM Software

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#180]
# Tasks
- [x] Create Issue
- [x] Add Link to Article in Reference of this Issue
- [x] Classify Labels, Milestone & Assignee
- [x] Create Article
- [x] Create Title / Subtitle / Abstract
- [x] Enter Issue No in Article
- [ ] Write Article
- [ ] Add cross references
- [ ] Trigger review
- [ ] Include review feedback
# Reference
- [V² > Plan > Flow > Mechanical Design > Choosing CAM Software](https://v-squared.github.io/plan/flow/mechanical/pick-cam-app/)
