### ISSUE TITLE
V² > Plan > Flow > Mechanical Design > Workflow CAD → CAM → CNC

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#181]
# Tasks
- [x] Create Issue
- [x] Add Link to Article in Reference of this Issue
- [x] Classify Labels, Milestone & Assignee
- [x] Create Article
- [x] Create Title / Subtitle / Abstract
- [x] Enter Issue No in Article
- [x] Write Article
- [x] Add cross references
- [x] Trigger review
- [x] Include review feedback
# Reference
- [V² > Plan > Flow > Mechanical Design > Workflow CAD → CAM → CNC](https://v-squared.github.io/plan/flow/mechanical/pick-cam-app/)
