### ISSUE TITLE
V² > Plan > Flow > Mechanical Design > How-To Task-Templates

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#182]
# Tasks
- [x] Create Issue
- [x] Add Link to Article in Reference of this Issue
- [x] Classify Labels, Milestone & Assignee
- [ ] Create Article
- [ ] Create Title / Subtitle / Abstract
- [ ] Enter Issue No in Article
- [ ] Write Article
- [ ] Add cross references
- [ ] Trigger review
- [ ] Include review feedback
# Reference
- [V² > Plan > Flow > Mechanical Design > How-To Task-Templates](https://v-squared.github.io/plan/flow/mechanical/how-to/)
