### ISSUE TITLE
V² > Plan > Flow > Intro

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#183]
# Tasks
- [x] Create Issue
- [x] Add Link to Article in Reference of this Issue
- [x] Classify Labels, Milestone & Assignee
- [x] Create Article
- [x] Create Title / Subtitle / Abstract
- [x] Enter Issue No in Article
- [x] automatically generate index cards → #189 
- [x] Trigger review
- [x] Include review feedback
# Reference
- [V² > Plan > Flow > Intro](https://v-squared.github.io/plan/flow/)
