### ISSUE TITLE
Epic > 018: Create Title Graphics for all DIY Books

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#187]
# Gated

We first want to start using the image ML already created in V²Plan. Once we have experience using them and possible make a list of enhancements for the next lot, we will render this series.
# Tasks
- [x] BC, HC: Create initial description for Title Graphics of each Book → comment
- [ ] HC: Fine tune → Descriptions of Book Title Graphics
- [ ] ML: Render Images
- [ ] HC: Process and Upload

**Comment by VillageHubertChen** [comment]
# Descriptions  of Book Title Graphics

DIY PC: Vector Graphics of ViPC

Configs: Phoenix Logo with Screw Driver

Optimize: Circle of arrows

Cooling: Top of side view of cooling fan

Assemble: Explosion drawin of ViPC assembly

AIO: AIO PC with keyboard and mouse

Install: Arrow download icon to ViCase PC

Fixing: Screw driver to ViCase

QA: Phoenix with Magnifier glass on ViCase

Parts: Phoenix with Vector of a memory stick & Card

Tools: Phoenix Logo in front of tool board

Comparison: Phoenix Logo with bar graph
