### ISSUE TITLE
Epic > 018: Create all Book Introduction Pages

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#188]
# Tasks
- [ ] HC: Edit Titles and Abstracts for each Book Intro Page and add Sub Titles
- [ ] HC: Transfer Titles, Subtitles and Abstracts to each Book Intro Article
- [ ] HC: Make sure each Title also says: "Book Introduction"
- [ ] HC: Make sure each article has a cross linked article issue
- [ ] HC: Add the Title Graphics from → #187
