### ISSUE TITLE
Epic > 018: Automatically generate Index to DIY Books

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#189]
# Tasks
- [x] HC: Write Card Design, User Stories, specs to Lukas →  Epic > 021 > Parent: Automatically 
- [ ] LC: Implement, then trigger HC for testing
- [ ] HC: Test Implementation
# Reference
- Page to generate Index → [Index of V² DIY Workstation Books](https://v-squared.github.io/diy/)
- →  Epic > 021 > Parent: Automatically generate all Index Pages #191
