### ISSUE TITLE
Epic > 021 > Parent: Automatically generate all Index Pages

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#191]
# Tasks
- [x] HC: Specify Card Design → below
- [x] HC: Write User Stories → below
- [x] HC: Write: → This is the first of many such automated Index Pages → below
- [x] HC: Create the four Article Group Pages of Agile
- [x] LC: Implement following User Stories and specs below, then trigger HC for testing
- [x] HC: Test Implementation
# User Stories
## Reader of V²DIY

As a **New Reader** of V² DIY I very much appreciate the Index pages. They give me a quick and intuitive overview of what to find in the next lower hierarchy level. This is helpful to quickly find what I am looking for.
## Author of V²DIY

As a **Author of V² Articles** I appreciate the automatically generated index pages. For me it means one less thing to do. In the past after adding a new Article or Book I needed to also create the entry in the Index Page. Same for updating the Article Title, Subtitle, Abstract, Image or Readiness. But now all updates are automatically transcribed to the index page. Great time save for me.
# Card Design
- Portrait Cards as typical in modern UI
- Content: Title-graphics + Readiness + Title + Subtitle + Abstract. 
- Behavior:
  - Hover: Highlight card
  - Click: Go to linked Article
- Article Groups are shown too. If not sure how to layout grouping, ask HC
# All Index Page content will be automatically generated

We will use this method of automatically generated index pages for:
- Board Index Pages
- Book Index Pages
- Article Group Index Pages
# About Index Pages
## Misc
- Some index pages are already generated by hand and entered in book-bar.yml
- Some page references in the article-bar are generated by Lukas code
  - Some corresponding page have been created by hand already, but the link the Article-Bar is broken. Example → https://v-squared.github.io/plan/agile/getting-started/
- Some of those Index Pages have already a ToC created by hand
  - When final implementation is done, we will have no ToC as per design. The already generated ToC will need to be removed
## Index Pages can also be Intro or Overview Pages
- **Example:** → [V² Plan Introduction](https://v-squared.github.io/plan/#key-elements)
  - Under "Key Elements of V²Plan" we add an include, that will generate the index cards
- The remainder of the page we can fill with markdown as we see fit. In this case we add more information to give an overview to V²Plan.
# How to code it
- The page itself will be generated by hand
- the content of body the system.md page will be automatically generated
- LC will code an include template, that is included with markdown in the page
- we will give it as parameter the book-bar.yml file with pointer to system folder
- All content is pulled out of YML front matter of the articles
- the include-template will then generate the page as described below:
# List of all Index Pages implemented now
- → Epic > 018: Automatically generate Index to DIY Books #189 
- → https://v-squared.github.io/plan/flow/
- → https://v-squared.github.io/plan/flow/writing/
- → https://v-squared.github.io/plan/flow/mechanical/
- → https://v-squared.github.io/plan/agile/
- → https://v-squared.github.io/plan/agile/getting-started/
- → https://v-squared.github.io/plan/agile/fundamentals/
- → https://v-squared.github.io/plan/agile/developing/
- → https://v-squared.github.io/plan/agile/reference/

**Comment by VillageHubertChen** [comment]
@LukasChen GREAT WORK! Fast, focused, error free, inspiring. I am looking forward to see more like this :-) :+1:
