### ISSUE TITLE
V2 > DIY > Intro > AiO Comparison

### ISSUE THREAD

**Issue by bcaswelch** [V-Squared/V-Squared.github.io#192]
# Generic Tasks
- [x] BC: Create Issue
- [x] BC: [Create Article](https://v-squared.github.io/plan/flow/writing/adding-articles/)
  - [x] HC: Unstuck BC on how to create article → read the text too, not only look at images
- [x] BC: Add Link to Article in Reference of this Issue
- [x] BC: Classify Labels, Milestone & Assignee
- [x] BC: Create Title / Subtitle / Abstract
- [x] BC: Enter Issue No in Article
- [x] BC: Write Article → see my comments below
- [x] BC: Add cross references
- [x] BC: Trigger review
- [x] BC: Include review feedback
# Specific task
- [x] BC: Please spell out yourself. The tasks are very similar to → #157 Copy their specific tasks to here and adapt them. Then work down the tasks.
- [x] BC: Create photo formats
- [ ] BC: Add emotion to writing
- [x] BC: Finish creating page
- [x] BC: Move issue writing to article
- [x] BC: Add Art Placeholders
- [x] BC: Add references
# Restructure
- [x] HC: [Restructuring Usability](#issuecomment-229836265)
- [x] HC: Add Table of Contents
- [x] HC: Create example table of the first of the 16 Usability Summary tables
# Tasks after Review
- [x] BC: Read →  [Restructuring Usability](#issuecomment-229836265) to understand motivation and target of Restructuring Usability
- [x] BC: Create again Portable including anchor {#portable}
- [x] BC: Keep Open Modular Formfactor
- [x] BC: Move content of "Open Modular FOrmfactor" to "Portable" (This is where it belongs)
- [x] BC: Write conten of "Open Modular Formfactor"
  - You buy an All-In-One. Later you change your mind. You change AiO to Mini PC without buying a new PC. OPen Modular Form Factor is the renamed prior feature of "Fluid Formfactor", previously named "Convertible Form Factor"It is changing form factor without buying a new PC. The Trafitional Monolithic AiO would force you to buy a new one.
- [x] BC: Clean up inconsistencies in Spec Comparison Details. E.g. Heading says: "ViPC 620 vs Dell XPS 27" and Table Title says: "ViPC 1200 vs HP Z1 G3"
- [x] BC: Adjust Spec Comparion Tables so the be a 1:1 comparison
  - if they have a consumer GPU, keep matching workstation GPU. Make their GPU red. Give it a Footnote. Explaining that a consumer GPU will not accelerate Workstation Applications, as they require a Workstation GPU
  - Add: "Disk Data Rate". Two disk RAID: 300 MB/s, Single Disk: 150 MB/s
  - "Data Disk" Check if they mention which disk. Are they workstation class, like Western Digital Red or Gold or are they consumer class, like western digal Black, Grenn, blue?
- [x] BC: Convert each small Usability Table same way as I converted the first table in "AiO Open Modular Display"
- [x] BC: Create a Bar Graph for "Spec Comparison". This need to be done after you created matching side by side configurations. ViPC is set to 100%. Give percentage ratings to other workstations based on how they compare. Here are the handicaps: No RAID HDD, -20%, no Workstation GPU: -30%, no nVME, -20%
- [x] BC: Create Subtitle
- [x] BC: Create Abstract
- [ ] BC: Polishing. After all above is done, sit side by side with your father. You are doing a table read to him. Anything stick out will be smoothed by both of you.
- [ ] BC: Try to add emotional impact to writing, as I have described in feedback in Issue for Workstation Comparison. The idea is to write in a way that the reader feels how this will change his work life. If possible tell the feature in story, where having the feature saved the day. Not sure if this need to be an additional chapter or can fit in writing we have now. This is delicate. Some people will want at least the feature explained netral before reading emotional impact.
- [x] BC: Please check if you transferred all your writing from Issue to Article. If so, can you delete the original writing in this comment, so the clean it up?
- [x] BC: Add a note under price comparison bar graph: **Note:** Price comparison not final. Pricing will change. Image is here for _Art Place Holder_ purpose at this time.
- [x] BC: Split 16 Usability topics into two groups of about equal size:
  - Usability (Smile on face during the day)
  - Open Modular (Saving Money / save planet in the long run)
- [x] BC: Update Table of Contents to reflect above changes
- [x] BC: Update Summary to reflect above changes
# After Bobby implement above
- [ ] HC: Create Pencil Drawings for _Art Placeholders_
- [ ] HC: Try to add emotional impact to writing
- [ ] HC: Consistency Rewrite
- [ ] HC: Review with GI
- [ ] HC: Review with SL
# Reference
- [V2 > DIY > Compare > AiO Comparison](/compare/aio-comparison/)

**Comment by bcaswelch** [comment]
@VillageHubertChen 

Going to revamp the tables, make them similar to the ones from the workstation article. You can review the writing thats currently here.

**Comment by VillageHubertChen** [comment]
@bcaswelch 

# Article Creation
- [ ] Do together: 1) HC learn how to improve so it becomes self explanatory: [Adding Articles](https://v-squared.github.io/plan/flow/writing/adding-articles/) 2) BC learns how to Add / Create an article

# Rewriting first Chapter

## Notes

### Sitting on your giant shoulders

I enjoyed reading your writing very much. I missed it. Thanks for letting me have it again :-) I have rewritten it and placed it below. Please do not take this as criticism at all. I am merely sitting on your giant shoulders, making small improvements on your achievement. When I am writing myself, I am doing the same thing of writing first version, then let it sit for a week and then completely rewrite it. Only now I do not need to wait a week to get distance from the first version.

### Fast versus short

Your version is much shorter. My versions is much longer. Yet I am certain my version is faster to skim through and get the message. I put all key messages in headings, item lists and colored tables. These are the outstanding layout elements the reader's eye will jump to when skimming through a document. Many rules of good writing are still from days of paper, where distributing longer text was more expensive. But today's internet is not limited by the cost of sharing, it is limited by the cost of reading. My writing is written to reduce the reader's cost (read time) to get the message.

### Important to always keep the same order of comparison

You started by first write about traditional, then write about new (us). It is very important in every instance of text, graphics or table to keep this order. Or for some people this message will get confused and points that we earned will be mistakenly scored to the opposing team.

### Story telling

For eons humans sat around the camp fire and traded stories. Only recently we started trading data sheets and feature tables. Not surprisingly a told story still sticks better. I started rewriting each feature as story. Starting with a cartoon.

### Repeated story telling

A minister was once asked what was the secret that his sermons could be remembered, versus the sermons from the other ministers were forgotten soon. He smiled and replied:
- First: I tell them what I am going to tell them
- Second: I tell them
- Third: I tell them what I told them

This works and this is how I did that:
- First: Cartoon
- Second: Story
- Third: Comparison Table

### Scent for the hunter

We have been hunters all our evolution. We still have not shaken our instincts. In today's world we do not hunt for deer, we hunt for bargains. This article is leaves traces on where to find the bargain: The Open Modular AiO. Once the buyer picks up the scent, he will follow the traces to the shop.

### Thank you for triggering me

I tried last night to write something up. But my mind was so deep into what I am working on here, that I could not. Even trying was exhausting me. Instead your article simply opened the flood gates. Effortlessly I wrote all this in just an hour. I am enjoying this greatly. I hope you do too and we will keep this as a successful working method. :-)

# Open Modular AiO vs Closed Monolithic

## Screen Options

```
**Art Place Holder***
- Layout: 3:1, whole width, under paragraph title
- two line art illustrations demo Closed vs Open, vs is bold and highlight color
- *Open:* 
   - ViCase Stand plus Display as two parts explosion drawing
   - Additionally a matrix of 2 x 2 displays, all different size
      - inside each display the words: IPS, 4k, 120 Hz, 30 bit
   - Phoenix with smile
- *Closed:*
  - iMac outline
  - Stick man with frown
```

### Closed Monolithic AiO

Traditional all-in-ones have the display infused with the entire chassis.

**Closed AiO limits your choice of:
- Screen size
- LCD type
- Quality ...

... to what the manufacturer decides on. Some give certain flexibility in the size or screen type, but with hundreds of factors to take into account for monitors, this simply means you are limited in finding the best screen for you. All-in-ones also have no upgrade or repair options to the screen post-purchase, meaning you must buy a whole new machine.

### Open Modular

ViPC AiO lets you choose any monitor you want, including the one you already own. Made possible by utilizing the open modular industry standard of VESA mount. The Display is the single most important interface between you and your computer. This is even more true for practitioners of the visual arts, such as photographers and designer. Resolution, size, density, color accuracy, viewing angle are all factors where the _open modular AiO_ gives you full control to optimize features versus your budget.

And because the screen is separate from the components, you can upgrade the screen without changing the rest of the components while still enjoying the benefits of the all-in-one form factor.

### Comparing Screen Options

| Feature | Open All-In-One | Closed All-in-One |
| --: | :-: | :-: |
| Choice | Vast {gn} | Limited {rd} |
| Upgrading | Yes {gn} | No {rd} |
| Fix it | Yes {gn} | No {rd} |

# Portable vs Chained to Desk

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Portable vs. Chained, vs is bold and highlight color
    - _Portable:_ 
       - Moving ViPC AiO in in between desk to table
       - Remote start shown
          - carry grips shown
       - Phoenix with smile
    - _Chain:_
      - Traditional AiO connected to several cables
      - Lockdown symbol
      - Stick man with frown

In todays world, being mobile is vital for almost every situation. Collaboration has been a growing criteria for businesses and schools, making sharing your work important for all parties. Currently, you have to choose between power or mobility. Traditional desktops / all-in-ones are designed to be kept in a single spot; transporting them is awkward and difficult. Laptops are easy to transport, but leave much in terms of performance. Many people have both a laptop and desktop, but this leads to differences between workflow. 

ViPC AiO is designed to be carried around easily throughout a workplace or home. By incorporating all of the standard peripherals into the case itself, the computer can easily be brought around without causing any headaches. Grips are another point many computers don't include, so we made sure to add grips for pain-free transportation.

| Feature | ViPC AiO | Traditional AiO |
| --: | :-: | :-: |
| Carry Grip | yes {gn} | no {rd} |
| Keyboard Bay | yes {gn} | no {rd} |
| One cable only | yes {gn} | no {rd} |

# Desktop Parts vs Mobile Parts

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _Desktop:_ 
       - Large Graphics card, racing wheels
       - Phoenix riding it?
    - _Mobile:_
      - Small mobile graphics, normal wheels with smoke coming from top
      - Stick man riding with frown

### Closed Monolitic AiO

Many all-in-ones use mobile variations of components to keep power usage and size small. Mobile parts have less power consumption, lower clock speeds, and smaller coolers, acting as gimped versions of desktop parts. While useful for devices such as laptops, having mobile parts on an all-in-one limits performance and upgradeability.

### Modular AiO

ViPC uses standard desktop parts for all of its components, running at the intentional speed that item was given. Desktop parts are overclock-able, offer more performance-per-value, and are much easier to replace/upgrade. Some desktop parts such as the CPU cooler and graphics cards are larger than their mobile counterparts due to heat, but ViCase manages to fit these components all in a 6-liter housing.

| Feature | Desktop Parts | Mobile Parts |
| --: | :-: | :-: |
| Max performance | higher {gn} | lower {rd} |
| Cost | lower {gn} | higher {rd} |
| User replaceability | higher {gn} | lower {rd} |

# Fix vs Trash

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _Open:_ 
       - ViPC AiO, parts hovering above with arrows pointing towards machine
       - new parts being upgraded
    - _Closed:_
      - iMac outline
      - image in landfill, 

### Closed Monolithic AiO

Many all-in-one components are fused into the chassis as non-standard parts, such as the screen, power supply, and motherboard. This means that when the time comes to upgrade components, you must replace the entire machine, costing more funds and decreasing the life of the device. Most manufacturers will let you send the product back for repairs, but this costs time and money.

### Modular AiO

Using standard parts around an open computer chassis means your computer can last you as long as you want. Everything in the machine is user replaceable, such as standard ITX motherboards or FLEX ATX power supplies. This also means less waste, and repairing or upgrading the machine can be done yourself with little experience needed. ViPC firmly believes in an open system, so we made sure we incorporated this mindset when it came to the longevity of ViPC.

| Feature | Open Modular | Closed Monolithic |
| --: | :-: | :-: |
| Any part user replaceable | yes {gn} | no {rd} |
| Average repair / upgrade cost | low {gn} | high {rd} |
| Average down time | short {gn} | long {rd} |

# Carry on vs Shipping

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _carry on:_ 
       - Phoenix bringing ViPC through airport security
       - carrying with or in a carry on bag
       - Phoenix with smile
    - _Closed:_
      - shipping in large box, dents on box
            -money sign above
      - Stick man with frown

### Closed Monolithic

Shipping a computer is expensive, time consuming, and potentially harmful to the machine. To get away from doing this many people will buy a laptop for travel, but this introduces two problems; a laptop isn't going to have the same performance as a desktop computer and its another machine you have to manage.

### Open Modular

There are many reasons you would want to travel with your computer. Students going home for the holidays, spending the week at a convention, or travelling for business are a few. Being without your main computer for such trips can be difficult, so we made ViPC as travel-friendly as possible. ViPC is small enough to fit into carry on luggage, saving you time and money by not having to pack it separately. This also mitigates the need for a laptop for travel, making your life much easier by just needing one computer.

| Feature | Carry ViPC | Shipping Other |
| --: | :-: | :-: |
| Cost | $ 0   {gn} | $ 100 {rd} |
| Time without workstation | zero {gn} | days {rd} |
| Risk of loss or damage | slim {gn} | considerable {rd} |

# Clean Desk vs Mess

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _clean:_ 
       - Clear desk, keyboard mounted
       - Sketch paper on desk?
       - Phoenix with smile
    - _mess:_
      - Desk with usb hub, wires all over, keyboard on desk
      - Stick man with frown

### Closed Monolithic AiO

Keeping your computer desk clean can be a difficult task. From your keyboard or drawing tablet to the stacking pile of soda cans, managing desk space isn't easy. Many all-in-ones do a good job of minimizing space below the desk by taking the traditional desktop tower out of the equation, but you still have to manage all of the peripherals on the desk.

Cable messes have always been a nightmare for computer desks. Look behind a desk and you will likely find piles of cables stuffed behind, all tangled and messy. You need power surge protectors, plugs for a monitor, USB hubs, and more. 

###Modular AiO
Managing your keyboard while not in use is a problem many face. Some people unplug it from their computer or flip it on it's side on a ledge, but everyone shares the common problem; where can I put my keyboard for easy storage? We solved this issue by doing the most logical approach, incorporate a keyboard stand into the AiO chassis for storage and transportation. Now, you can simply place your keyboard underneath the screen to sketch some new designs or work in your textbook. 

To battle the famous cable mess issue that computer desks face, we incorporated many common peripherals into the case itself to keep everything in one place. 

| Feature | ViPC | Other |
| --: | :-: | :-: |
| Need external Power Distribution | no {gn} | yes {rd} |
| Need external USB Hub | no {gn} | yes {rd} |
| Cable Organizer | yes {gn} | no {rd} |

# Workstation vs Consumer

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _Workstation:_ 
       - ViPC with clock floating above, fully colored green
       - Phoenix with smile
    - _Consumer:_
      - Traditional AiO with only 4 hours of clock  filled in
      - Stick man with frown

Everyone uses their computer differently. Some use it mainly for gaming or 3D modeling, while others use it for programming or video rendering. With this, certain configurations are going to be better for working day and night or just light work every couple of hours. Parts like hard drives or power supplies are rated for use, and are important factors to take into regard. If using a computer for heavy work, you'll want gold + rated power supplies and hard drives that are rated to be used continuously. These will cost more and aren't needed if you don't need the amount of reliability, but are a must buy if you do. ViPC configurations use workstation grade components, rated to keep up with your workload without failing.

| Feature | Workstation | Consumer |
| --: | :-: | :-: |
| Duty Hours | 24 h {gn} | 2h {rd} |
| GPU type | Quadro {gn} | GTX {rd} |
| Eco footprint | low {gn} | big {rd} |
| 100% load capable | yes {gn} | no {rd} |

# Safety

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _Open:_ 
       - 
       - Phoenix with smile
    - _Closed:_
      - 
      - Stick man with frown

With every computer,additional safety peripherals are needed to keep everything in check. For workstation computers, sudden electrical surges can be detrimental, causing many delays if your computer isn't properly protected. Up until now, people had to buy separate surge protectors to keep the components safe in case of electrical failure. ViCase has surge protection and an EMI filter built in, meaning your PC will always be protected no matter where you take it. The built-in DC port also keeps your monitor protected and lessens what you have to plug into the wall.

| Feature | ViPC | Other |
| --: | :-: | :-: |
| Surge Protection | yes {gn} | no {rd} |
| EMI Filter | yes {gn} | no {rd} |
| Power Monitor | yes {gn} | no {rd} |

# Cleaning

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _Open:_ 
       - ViCase cover in dishwasher next to other plates
       - Phoenix with smile
    - _Closed:_
      - Traditional AiO, dust all around 
           -red heat arrows radiating off computer
      - Stick man with frown

For computers, dust is their worst nightmare. Dust build-up makes your components run hotter, lessens the life of fans, and covers the shiny exterior of your PC. It can be a hassle to clean PCs, as its an important step to take in keeping your computer running cool and quiet. ViPC not only has high quality dust filters all around the case for great cooling, but the top cover and dust filters are 100% dish washer friendly. A common mistake many people do is use compressed air to blow dust off their computer. While this gets the dust off in the short run, all of that dust doesn't magically disappear; now its floating all over your room. Our filters and cover can be thrown in the sink for true cleansing, keeping the airflow in your PC dust free.

| Feature | ViPC | Other |
| --: | :-: | :-: |
| Magnetic Quick Snap | yes {gn} | no {rd} |
| Washable | yes {gn} | no {rd} |
| Quiet PC due to regular cleaning | yes {gn} | no {rd} |

# Easy Access

 **Art Place Holder***
    - Layout: 3:1, whole width, under paragraph title
    - two line art illustrations demo Closed vs Open, vs is bold and highlight color
    - _Open:_ 
       - Slightly off center top down view of ViPC AiO, all ports of motherboard shown
       - Phoenix with smile
    - _Closed:_
      - hand reaching to back of AiO, fumbling around plugging in USB
      - Stick man with frown

For many, once you buy a PC you can leave it without opening it up. Many all-in-ones are designed like this, making self repairs / upgrades nearly impossible for the average user. For ViPC, we wanted to give easy access for every aspect of the computer, from turning it on to plugging in peripherals. 

The power button on PCs have always been a pain to use. Most of the time you have to reach way back behind the screen or for tower PCs, underneath the desk. Not everyone is going to have their computer set up the same way, so we decided why not let the user choose where to power on their ViPC? We include a remote power button that can be placed on the desk or taped to a wall for easy access no matter where the PC is placed.

Similarly to power buttons, getting to your ports can be difficult. For ViPC AiO, we give you the option to orient the direction of your ports however you want; face them up or down, left or right. For easy access, facing them upwards gives you every port you need just by standing up and looking down at your computer. Facing them downwards will hide any cables sticking out in case you value looks over function. And you can change the orientation any time you want. 

| Feature | ViPC AiO | Traditional AiO |
| --: | :-: | :-: |
| Quick Snap Top Cover | yes {gn} | no {rd} |
| Fluid Port Placement | yes {gn} | no {rd} |
| Remote Power On | yes {gn} | no {rd} |

# Smile on your Face

This is

**Comment by bcaswelch** [comment]
@VillageHubertChen 

Hi, could you check how the writing is so far in terms of the direction I'm going? Getting a bit of a brain fart for the last couple so I'll finish it in the morning

**Comment by VillageHubertChen** [comment]
@bcaswelch Your writing is going in the right direction. However the story and emotional component is missing. I am too tiered too to have an idea if you could rewrite what you wrote and add the story component to it, or if this need to be an extra paragraph. In any event keep writing. 

When running out of ideas, continue on the Workstation Comparison.

Once you have a complete writers block, do mechanical work, such as creating the All-In-One Article page.

**Comment by VillageHubertChen** [comment]
@LukasChen 

Please put all small tables in YML and format cell colors

**Comment by bcaswelch** [comment]
![aiopricecomparison](https://cloud.githubusercontent.com/assets/16950279/16481653/35f91d18-3e61-11e6-8f10-a41f8776632a.png)

**Comment by VillageHubertChen** [comment]
# Notes on Restructuring Usability

## Before Restructuring

Usability Table and Usability Writing have been inconsistent. Topics of both listed below:

### Usability Table (before rewrite)
- All-In-One Conversion
- 3 Chamber Airflow or better
- Portable
- Surge Protection
- Clean Desk Cabling
- Custom Configuration
- Open Configuration
- DIY Option
- I Fixit Option

### Usability Writing (before rewrite)
- Screen Options
- Portable vs Chained to Desk
- Desktop Parts vs Mobile Parts
- Fix vs Trash
- Carry on vs Shipping
- Clean Desk vs Mess
- Workstation vs Consumer
- Safety
- Cleaning
- Easy Access

## Unified Table & Writing of Usability
- Open Modular Displays
  - Your Dream Display or Not
- Open Modular Upgrading
  - Long Service Life vs Short
- Open Modular Configuration
- Open Modular Formfactor
- Portable
  - Portable vs Chained to Desk
- Desktop Parts
  - Desktop Parts vs Mobile Parts
- I Fix It Option
  - Fix vs Trash
- DIY Option
- Carry On Compliant
  - Carry On vs Shipping
- Clean Desk
  - Clean Desk
- Workstation Class
  - Workstation vs Consumer
- Surge & EMI Protection
- Easy Clean
- Easy Access
- Save Planet

# Ideas for Future

We are trying to be able to put links into table cells. If we can the user can click on a topic in the table and the page scrolls to the detail explanation.

**Comment by bcaswelch** [comment]
![specomparison](https://cloud.githubusercontent.com/assets/16950279/16537617/4acffcc8-3fbc-11e6-9ca3-6ceb635d8d26.png)

**Comment by bcaswelch** [comment]
@VillageHubertChen 

The open-modularity url is broken, not sure how to fix it.

**Comment by VillageHubertChen** [comment]
# Fixed broken link in ToC

@bcaswelch 

I fixed the Open Modular URL like so:
1. Removed "tab" in the URL, which is a reserved word for routing deep link tabs.
2. Give it a unique anchor name, not coinciding with auto generated anchors (You have a sub title Open Modular)
3. Add the hashtag in the anchor (you put it in all other anchors, but you forgot it in this one.)
   - wrong: Open Modular {open-modular-details}
   - right: Open Modular {#open-modular-details}

**Comment by bcaswelch** [comment]
![dellopticonfig](https://cloud.githubusercontent.com/assets/16950279/16634327/fbae0468-4381-11e6-8527-953d1ff45ad9.png)

**Comment by bcaswelch** [comment]
@VillageHubertChen 

Regarding the intro, I'm thinking of replacing grand summary with a more intriguing article head (such as Breaking New Ground). Draws the reader in with a compelling headline and doesn't make the article seem as bland (has some flair to its titles). Let me know your thoughts on the change.

**Comment by VillageHubertChen** [comment]
# Breaking new Ground

@bcaswelch 

I like that! This allows us at the beginning of the Article to focus on what is special on ViPC. Then we have the traditional Summary at the bottom, where the reader expects it. I will restructure the article accordingly. Great idea :-)
