### ISSUE TITLE
V² > Plan > Road Map > Next 2 Years

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#193]
# Tasks
- [x] Create Article
- [x] Create Issue and link Issue to Article
- [x] Link Article to Issue
- [x] Set Labels, Milestone, Assignee
- [x] Update Article to new Front Matter
- [x] Add Milestone: "GitHub.V-Squared.Create"
- [x] Add ToC
- [x] Write Abstract (Moved into Article in this case due to better reading flow)
- [x] Set readiness to _Make_ (The content was already reviewed when it was part in *_Intro_. This page as newly created to absorb this content when we created automatic Index Pages)
# Reference
- → [V² > Plan > Road Map > Next 2 Years](https://v-squared.github.io/plan/road-map/next-2-years/)

**Comment by VillageHubertChen** [comment]
# Adding Visuals / Improve Message / Funding

## Total 4 Graphs
- **Graph1:** 10 Year Time Line
- **Graph 2:** Alternating Life Cycles
- **Graph 3:** Detailed Life Cycle V²Case
- **Graph 4:** 4 Ways of Funding

## Graph1: 10 Year Time Line
- 2011-2016 Foundation
- 2016-2018 Introduction
- 2018- Mainstream

## Graph 2: Alternating Life Cycles
1. Developing
2. Trailblazing
3. Standard
4. Mainstream

## Graph 3: Detailed Life Cycle V²Case

![](https://raw.githubusercontent.com/V-Squared/V-Squared.github.io/master/images/illustrations/v2-road-map/v2-road-map-2016-next.png)

## Graph 4: 4 Ways of Funding
1. Trailblazer Products
2. Referrals
3. Donation
4. Kickstarter Campaigns

**Comment by VillageHubertChen** [comment]
# Opened to Improve Graphics

@tcaswelch @bcaswelch 
- See graphics above
- Make them interactive
- Add new chapter matching new content to new graphics

**Comment by VillageHubertChen** [comment]
# Splitting? → Standard Life Cycle

After recent restructuring of Road Map I am considering to split above content into two articles:
1. Overview Road Map
2. Standard Life Cycle

# Removed from Menu:
- next-2-years.md -> Currently not used, all contents transferred
- menu: Next 2 Years
  - url: /road-map/next-2-years/
- issue 193

I still need to clean up this issues!
