### ISSUE TITLE
V² > Plan > Road Map > How it Works

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#194]
- [ ] Create Article
- [x] Create Issue and link Issue to Article
- [ ] Link Article to Issue
- [x] Set Labels, Milestone, Assignee
- [ ] Add Front Matter
- [ ] Move content from Index 
  - (it was intro, now this page serves this function after introducing Auto Index Cards)
- [ ] Add ToC to Front Matter
- [ ] Set readiness
- [ ] Trigger Structure Review GI
- [ ] Include feedback GI
- [ ] Add Title Graphics
