### ISSUE TITLE
V² > Plan > Intro

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#195]
# Tasks
- [x] Create Article
- [x] Link Issue to Article
- [x] Link Article to Issue
- [x] Set Labels, Milestone, Assignee
- [x] Update Article to new Front Matter
- [x] Add abstract and subtitle
- [x] Add ToC to Front Matter
- [x] Set readiness
- [x] Move writing from Index to here. (It hosted the former intro page, but now becomes the page for the automatically generated index)
- [x] ML: Render Title Graphics
- [ ] HC: Edit and publish Title Graphics
# Reference
- → [V² > Plan > Intro](https://v-squared.github.io/plan/intro/)
