### ISSUE TITLE
Add & Clean up Index & Intro Pages in V² > DIY

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#199]
# Tasks Index & Intro Pages DIY
## Intro Page
- [ ] Create Intro Page after Index
- [ ] Move Sub Title & Title to Intro
- [ ] Body
  - [ ] Compendium to Forums
  - [ ] Promote Open Modular V² PC & All-In-One
  - [ ] Extension of V² True North
## Index Page
- [ ] Remove Subtitle and Abstract from Index
## Compare Intro
- [ ] Create Intro Page after Index
- [ ] Move Sub Title & Title & Body from Index to Intro
## Compare Index
- [ ] Remove Subtitle and Abstract from Index
- [ ] Set front matter -> articleBar = 'no'
## Parts Intro
- [ ] Create Intro Page after Index
- [ ] Move Sub Title & Title & Body from Index to Intro
- [ ] add auto index
## Parts Index
- [ ] Remove Subtitle and Abstract from Index
- [ ] Set front matter -> articleBar = 'no'
- [ ] add auto index
