### ISSUE TITLE
Visuals V² Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#2]
# Title Graphics
- Mashup Graphics
- Desktop Parts → V²Case
- V²Case Form Factors: Mini, Behind Display, VESA Display, All-In-One
# Trailblazer Products
- [ ] HC: Create visuals from the rendered product photos
# For Maker
- [ ] HC: Create place holder from Star Trek blueprints. Gauge feedback to the blueprint approach. If positive we will create blueprints with V² products.
# For DIY
## V²Configurator
- **Key idea:** list choices on a transparent wall
  - CPU: i3, i5, i7
  - Mem: 4 GB, 8 GB, 16 GB
- **Styling:** Icons and look and feel as in http://v-squared.github.io/v2-Configurator/
- **Gesture:** Phoenix looks at configuration thinking about it 
## V² How to DIY Mini PC
- **Key Idea:** Step by step instructions are symbolized by blue numbered steps. Step 1 is shown in detail, steps 2, 3, 4, 5 are hinted by listing them on the bottom
- **Styling:** Icons and look and feel as in http://v-squared.github.io/v2-Configurator/
- **Setting:** Phoenix is in the Instruction
- **Gesture:**  Phoenix inserts memory into motherboard. Red arrow indicates movement.
# Marketing
## Promotions & Spread the Word
- **Key Idea:** Two Phoenix.
  - One shows "The Early Bird catches the discount (sales)" same as we used before
  - Second one shouts out through a red megaphone 
## Shop
- **Key Idea:** Phoenix push shopping cart with ViCase in it
## Milestones
- **Key Idea:** Phoenix looks at a 3D Gantt Chart at invisible glass wall
- **Colors:** Primary, Secondary and Tangerine for bars, green for check, grey for box
### Details

![](http://psdblast.com/wp-content/uploads/2013/01/3d-check-box-icon.jpg)
- Design check mark  and check box like above, but use dark gray for check box
# Organization
### Ideas for Visual
- Our Team Illustration from Indiegogo Campaign
- Hands put together
- Search words: Team, Community
## Blog
# Misc
## V²Art
- 3D Rendering
- Phoenix Logo + Brush + Painter's Frame
## V²Docu
- 3D Rendering
- Phoenix Logo + reading Book
## Milestones
- 3D Rendering
- Phoenix Logo + colored progress Bars floating in front, arranged as Gantt Chart
## Vision / True North
- 3D Rendering
- Phoenix Logo + looking at a compass, pointing north, or looking at a direction to North
## Social Media
- 3D Rendering
- Phoenix Logo + looking at a bill board of social media
# Instructions
## Rendering
- All is white
- No shadows (need to be painted in later)
- Phoenix Color: Primary Color
- Primary color :  RGB (3,155,229)
- Secondary Color : RGB (3,124,183) (for other things to highlight)
- Highlight Color: RGB (255, 127, 0) (for spot highlights)
- uikit green : #8cc14c
- Gray (for supporting things)
### Making visuals with white background look good
- [ ] LC: Give every visual a gray border. We start with 0.7 pt #ccc
# References
- https://opensource.org/
- http://www.oshwa.org/definition/
- https://opensource.org/osr
- Temp Folder: Markting/v2-Site/Snaps
# Tasks
## First Round
- [x] @villagehubertchen: Create first brainstorming list for discussion
- [x] @villagehubertchen: Finalize list of first round, split into two lists for ML and HC
- [x] @VillageMichaelLin: Render Images as per above lists. 
- [ ] @villagehubertchen: Make remaining visuals and image processing, publish to V²Art
- [ ] @villagehubertchen: Upload to GitHub, share links to Lukas
- [ ] @LukasChen: Add Images to Home Page
- [ ] @villagehubertchen: Colect feedback
- [ ] @villagehubertchen: Final review of Home Page. Close Project.
## Second Round
- [ ] @villagehubertchen: Finalize list of second round, split into two lists for ML and HC
- [ ] @VillageMichaelLin: Render Images as per above lists. 
- [ ] @villagehubertchen: Make remaining visuals and image processing, publish to V²Art
- [ ] @LukasChen: Add Images to Home Page
- [ ] @villagehubertchen: Final review of Home Page. Close Project.
