### ISSUE TITLE
Rewrite V² Home Page to fit "All pieces of the puzzle" Metaphor

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#20]
# Metaphor
### Delivering all pieces of the puzzle

V² is much more than "The Missing Standard" for Mini and All-In-One Computer. Hover (tab) the puzzle pieces to explore how each contributes to the whole.
# All pieces of the Puzzle
## The Missing Standard

_All missing standards to find parts, build, upgrade and repair a modular Mini / All-In-One PC._
### V² Parts Standards

Building a modular Mini or All-In-One Computer was difficult if not impossible in the past due to missing key components. And even for those components in existence key specs were not standardized, making it hard to predict compatibility prior to purchase. The V² Parts Standards define specs for missing parts and where necessary append specs to existing standards.
### V² Use Standards

**V² Silent:** Measurement and Classification of PC noise **V² Easy-Upgrade:** Specs for easy upgrading **V² Easy Repair** Specs for easy repairing. **V² Easy Clean:** Specs for easy cleaning. **V² Easy Assembly:** Specs for easy assembly.
### V² Compatibility  Logo

 V² Logo is a tool to assist consumers in their buying process and at the same time to assist makers and retailers in their sales efforts. We believe the V² Logo Program is a community service. As such it is developed within the community and we are making licensing as transparent and straight forward as possible. All at zero cost.
## For Consumer: Trailblazer Products & Logo

_Real products available early on, showing what you can build with V² Standards. Buy today what is to become mainstream tomorrow._
### ViCase

Modular, scalable, quiet, Mini-PC Case for Desktop Parts with standardized Accessories compliant to the V²Case standard and compatible to ViDock graphics or storage booster. 
### ViAccessories

Accessories for any V²Case such as VESA brackets, feet, All-In-One Stand, Arduino Module, Remote Access, etc ... Compliant to the V²Case standard.
### ViPC & ViBare

Ready build custom PCs and bare bones ranging from Entry Level to High End based on V²PC configurations. Covering custom configurations for Personal Use, Game PC and Workstations. Compliant to V²Case and V²PC standards.
### ViPanel

PC I/O Panel with Remote Power On, 4 USB Ports, Head Set Ports, Arduino compatible MCU for extensive Fan and RGB Lights Control. V²Case or ATX Case options. Compliant with V²Case standard.
### ViDock

Graphics or storage booster for your V²PC with data rates of up to 4000 MB/s. Connect a full sized desktop GPU or four disk RAID.
### V² Logo

The V² Logo makes it easy to identify compatible products and parts. The V²PC Logo makes it easy to classify features and performance of a build PC or to find instructions for building, upgrading or repairing.
## For Makers

_Everything you need to develop your new products faster at lower cost_
### Standards

Products compliant to a standard always sell better and have lower development and manufacturing costs versus products based on proprietary solutions. V² is for Mini and All-In-One Computer what the ATX Standard was for the Desktop. 
### Trailblazer Products

New standards and specs on the web are one thing; having a final product in hand very early on is quite another. Test V² features before you develop your product with it. Give it into your customer's hand to test their feedback before you build it. This is one purpose of V² Trailblazer products to clear the path to your mass production.
### RDK & Blueprints

Rapid Development Kits give your development team a running start. Blueprints are Rapid Manufacturing Kits, ready to go to production. 
### No Gate Keepers

No membership approval, no proprietary parts, no long lead time parts, no certification process that can hold off production. V² mission is to get out of your way. We care about the maker, as they have been part of this community developing V² since the beginning. Alongside with consumers, retailers and press.
### Maker Kits

It is our mission and we are proud that we can enable you to build V² products that are licensed to carry the V² Logo without you ever talked to us or having paid a single dollar to us. But we hope you check out our Maker Kits where we offer additional services and products in an effort to help you to speed up your time to market.
### V² Logo Program

Make it easy for your customers to identify compatible products and parts. To find PCs with the features and performance they are looking for. We make it easy for you (or your customers or the press) to self-test compliance of your products or to contract an approval agency. Once passed you can use the V² Logo at zero costs to increase sales.
## For DIY

_PC Know How & Tools_
### V² How to DIY Mini PC

How-to Articles on custom building your own DIY Mini or All-In-One Computer. 
### V² PC Configurations & Logo

Ready made PC Configurations ranging from Entry Level to High End. Covering custom configurations for Personal Use, Game PC and Workstations. The V² PC Logo program makes it easy to find compatible parts or benchmark reports of the final build PC.
### V² Configurator

Easy to use PC Configurator Web App. Pick a V² PC Configuration as your base config and then customize to your needs. Supports sharing of your custom Configuration in social media to get feedback.
## For Retail

_Lower your cost and increase computer sales_
### Better Cash Flow & Availability

In order to keep enough configurations of traditional Mini and All-In-One PCs in stock to be attractive to the buyer the Retailer needs significant cash flow. Instead V² Mini and V² ALl-In-One PC require only a fraction of that cash flow. Thanks to their modular nature they can be configured while the customer is in the shop.
### New Markets

V² Mini and All-In-One PCs cover the traditional markets. In top of it they add the markets for personal (creative) workstations, professional workstations and game console upgrades. 
### V² Logo to help sales

Computer with V² Logo are quiet, portable, modular, easy to upgrade and repair. Their standardized accessories are cross vendor compatible and can be kept in use when changing the V²PC. Features important to the buyer. The V²Logo makes it easy to communicate it.
## Spreading the Word & Products

_How to tell the story of a smaller, quieter, more modular and upgradable PC and how to get it into the hands of the user_
### Social Web

We are on Facebook, Twitter, YouTube and GitHub Issues. We share what we are working on V² Blog, giving you a chance to give feedback or get engaged early on. And we are creating projects with other DIY Forums and DIY Websites who share the same interests of a Mini / All-In-One DIY PC.
### Computex

We will show V² Modular PC at Computex Taipei May 31 ... June 4. Make an appointment, just visit us or help to spread the word.
### Press

V² modular PC saves the environment and the user's money. It breathes new life into the Desktop and delivers faster, quieter and more portable PCs. Help to spread the word. Find Press Releases, White Papers and more ...
### Stage 1: V² Trailblazer Products

V² Gamma Sample Products ship in June, Trailblazer Products ship in August. Enjoy the benefits of V² Modular PC before they become available through OEM offerings, or be one of the first to write about it. The first 100 orders will enjoy a 25% discount. Help to spread the word to reach our 200 pcs stretch goal to get a free Arduino.
### Stage 2: V² Shops

**1)** Listing of all shops selling V² Products. **2)** Tutorials on how you can build your own V² Community online shop. (e.g., Computer Clubs and DIY forums to offer a service to their members that saves their money and at the same time generates income.) **3)** How you can add custom build Mini and All-In-One Workstations to your existing shop.
### Stage 3: V² Consumer Products

OEMs have the power to make the V² Mini and All-In-One PCs mainstream, to put them into the shop around your corner. It is our Mission to provide everything that an OEM need in Open Source and to remove all gate keepers. We expect V² OEM products to become available at the end of 2016 / beginning 2017.
## Apps

_V² Open Source Web Apps simplify experiencing or building V² PCs_
### V² Configurator

Easy to use PC Configurator Web App. Pick a V² PC Configuration as your base config and then customize to your needs. Supports sharing of your custom Configuration in social media to get feedback.
### V² Form Factors

Interactive Web App shows how to convert a V²PC from Mini PC to various All-In-One Form Factors. How it will look, how it works with 1, 2, or 3 displays and which V² Accessories are needed.
### V² Base.Compliance

Web App Database that is listing compliant products, that can use the V² Logo. Classified for the following product types: PCs, Cases, Panels, Motherboards, CPU Cooler, Power Supplies, Remote Access, All-In-One Stands, VESA-Brackets. Anyone can suggest additions via GitHub Flow. 
## Plan

Our Plan, shared in Open Source on GitHub. Check out why it will work or how you can help.
### True North

We will draw an image how the world will look like in 2021 after the successful introduction of V². It is a list of User Stories written in the perspective of: PC User, Journalist, Developer, Manufacturer, Retailer, Standard Community, so it is easy for you to find yourself and what V² will do to improve your life.
### Road Map & Milestones

The **Road Map** shows the way to reach True North with key releases for each Quarter. **Milestones** breaks each quarter down into release targets for each month. 
### Projects

Finally each target is broken down into projects, that are manged in **GitHub Issues**.
## Organization

_About the people, process and legal stuff creating the V² Open Standards_
### About

History, Mission, Board / People, Operations, Bylaws, Logo, White Papers
### Contributing

Fix Bugs, Projects in search of Owner, Workflows, Joining ongoing Projects, Become a member. Workflow and Tutorials on how to contribute to V². List of resources such as style guides, images, etc ...
### Logo License

As a Standard Organization our V² Logo is the key tool to assist consumers in their buying process and at the same time to assist makers and retailers in their sales efforts. We believe the V² Logo Program is a community service. As such it is developed within the community and we are making licensing as transparent and straight forward as possible. All at zero cost.
# Tasks
- [x] SL: Inspire the idea to rewrite the entire V² Home Page to match the new "All pieces of the puzzle" metaphor
- [x] HC: Rewrite Home Page as per above
- [x] BC: Feedback in table read
- [x] GI: Feedback in table read
- [x] SL: Feedback in table read
- [x] HC: Add "The Missing Standard Section"
- [x] HC: Merge "Spreading the Word" and "Spreading the Products" 
- [x] @LukasChen : Transfer to JSON
- [x] @villagehubertchen: Final Review / tuning of text
  - Check that Lukas transferred all correctly
  - V² Use Standards to V² Usability (Rewrite the standard texts)
  - Consider to replace Computex with DIY Forums
  - Shorten Text to fit portrait view in our 8" tablets, 3 folio boxes per row
  - Update the status bar for each item

**Comment by VillageHubertChen** [comment]
- [x] HC: Add "The Missing Standard Section"
- [x] HC: Merge "Spreading the Word" and "Spreading the Products"

**Comment by VillageHubertChen** [comment]
I reopened the issue. Lukas: You overlooked that still this task was not finished: Update the status bar for each item. Additionally the review of Georg create a Change Request List.

**Comment by VillageHubertChen** [comment]
# Change Requests (Review by Georg)
- [x] @LukasChen Change the following entries in JSON

### Better Cash Flow & Availability

In order to keep enough configurations of traditional Mini and All-In-One PCs in stock to be attractive to the buyer the Retailer needs significant cash flow. Instead V² Mini and V² ALl-In-One PC require only a fraction of that cash flow. Thanks to their modular nature they can be configured while the customer is in the shop.

### New Markets

V² Mini and All-In-One PCs cover the traditional markets. In top of it they add the markets for personal (creative) workstations, professional workstations and game console upgrades. 

### Stage 1: V² Trailblazer Products

V² Gamma Sample Products ship in June, Trailblazer Products ship in August. Enjoy the benefits of V² Modular PC before they become available through OEM offerings, or be one of the first to write about it. The first 100 orders will enjoy a 25% discount. Help to spread the word to reach our 200 pcs stretch goal to get a free Arduino.

### Stage 2: V² Shops

**1)** Listing of all shops selling V² Products. **2)** Tutorials on how you can build your own V² Community online shop. (e.g., Computer Clubs and DIY forums to offer a service to their members that saves their money and at the same time generates income.) **3)** How you can add custom build Mini and All-In-One Workstations to your existing shop.

### V² Base.Compliance

Web App Database that is listing compliant products, that can use the V² Logo. Classified for the following product types: PCs, Cases, Panels, Motherboards, CPU Cooler, Power Supplies, Remote Access, All-In-One Stands, VESA-Brackets. Anyone can suggest additions via GitHub Flow.

**Comment by LukasChen** [comment]
Done :tada:

**Comment by VillageHubertChen** [comment]
Hi Lukas,

Thank you for you diligent work and letting me know. Sadly, some mistakes got in and you did not caught them. Please check out the section: "Spreading the Word & Products".

It is very important on a work like this, that you put your final work on one side and the original spec on the other and then compare side by side, piece by piece. This is tedious but necessary to ensure no errors are made in a copy paste work, such as this one. Please fix above errors. Please check the whole page for additional errors and then trigger me again for final review!

**Comment by VillageHubertChen** [comment]
Hi @LukasChen , great job on your second double checking. All was perfect this time! :congratulations:
