### ISSUE TITLE
Test all CNC primitives CAD → CAM → CNC

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#202]
# Tasks
- [x] HC, ML: Write to do list
- [x] ML: Do one primitive completely, then let HC review
- [x] HC: Write change list based on review
- [x] ML: Redo first one, let HC double check
- [x] ML: Redo all others. Trigger HC it is done in comment.
- [ ] HC: Move all this into one Article
# Procedure
1. CAD
   1. Draw Primitive in SolidWorks
   2. Export to DXF and STL 
2. CAM
   1. Import to CAMBAM to Reference Layer
   2. Redraw in CAMBAM. Split into 4 layers: Drilling, Cut Out, Pockets, Tabs
      - snap back to grid 
   3. Generate G-Code
      - manually check G-Code: a) No nonsense b) coordinates in Grid?
3. Verification
   1. Import G-Code
   2. Simulate
   3. STL Compare
      1. Import STL file
      2. Run Compare
      3. Check if any red or yellow
# List of Primitives
1. Drilling
   - 11 Drill Hole
   - 12 Drill Pattern (Not tested now)
2. Cut Outline 
   - 21 Cut Rectangle with sharp corners
   - 22 Cut Outline Rectangle Rounded Corners
3. Cut Pocket Rounded Corners
   31 Standard Pocket
   32 Fast Pocket (Not tested now)
4. Holding Tab (Not tested now
# Writing Procedure
1. Write down all steps in a comment below
2. Make Snap Shots. 
   - Put into folder. Give Snapshot a good name. Refer to it in Article. Leader nn numbers in file
   - make rough cut of snapshot, save as png. use skitch, give file name as per below:
   - examples
     - 01-draw-primitive-sw.png
     - 02-export-dxf-settings.png
     - 03.export-stl-settings.png
   - optimize display width and layout to best use 853 px wide (give or take)
   - optimize height as little as possible
# What to save per Tested Primitive
## Items
1. Snap Drawing SW
2. Snap Import CamBam
3. Snap Drawing CamBam
4. g-code file
5. Snapshot compare in CutViewer
## Managing Files
- File Name: Index No + Item No + PrimitiveName + ItemName
- Example: 11-1-DrillHole-DrawingSW.png

**Comment by VillageMichaelLin** [comment]
# Verification Procedure
1. Draw Primitive in SolidWorks. 
2. Export to DXF
3. Export to STL
4. Import the DXF to CamBam and rename the layer to Reference
5. Add new layer for Drawing and redraw the primitive to snap back to grid
6. Generate G-Code and manually check G-Code
7. Import G-Code to CutViewer
8. Simulate G-Code in CutViewer
9. Run STL compare

**Comment by VillageMichaelLin** [comment]
@VillageHubertChen  When testing "22 Cut Outline Rectangle Rounded Corners" and "31 Standard Pocket". I have the same error message "Invalid floating point operation" when running STL compare

**Comment by VillageMichaelLin** [comment]
@VillageHubertChen  The four Primitive tests is done
