### ISSUE TITLE
V² > Plan > Flow > Mechanical > NC Codes

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#203]
# Tasks
- [x] HC: Write Specs and Example
- [x] LC: ASAP create page. Let ML and HC know when done. So they can start using it
- [x] ML: Test all primitives you need. Compile a list below
- [x] HC: Title, Subtitle & Abstracts
- [x] HC: Cross Link Article and Issue
- [x] LC: Add G-Codes in Table
- [ ] LC: Add M-Codes in Table
- [ ] HC: Add Name and Description to Tables
- [ ] HC: Write courtesy and recommendation for CNC Simulator. This is only an abstract.For full list see → ...
- [ ] HC: Add other links to good G-Code and M-Code articles
- [ ] HC: Write Abstract, Title, Subtitle
# List of all primitives
## G Code
- G0
- G1
- G3
- G17
- G21
- G40
- G64
- G80
- G81
- G90
- G91.1
- G98
## M Code
- M3
- M5
- M6
- M30
# Specs Creating Table
- Create Page: V² > Plan > Flow > Mechanical > NC Codes
- Transfer
  - all G Code Help Content to here
  - all M Codes
  - all graphics:
    - In a sub folder. → [example adding articles](https://github.com/V-Squared/V-Squared.github.io/tree/master/plan/flow/writing)
    - give code name to graphics, e.g. g00.png, h01.png, etc
    - look in "Adding Articles" source code how I added path to images
- Formatting of Tables
  - split into G Codes and M Codes Tables  
  - Only two columns: Code + Explanation
    - No need column Machine Type
    - Merge Explanation + Format + Example
  - Use straight forward markdown. See example
  - style table nicely with your style
# Example of Finished Table

| G-code | Explanation |
| :-: | :-- |
| ![g01](http://cncsimulator.info/OnlineHelp/lib/NewItem438.png) | Go rapidly (with maximum traverse rate) to the X/Y/Z position. This code is used for position and not for actual machining.<br>**Format:** G00 [X#][Y#][Z#]<br>**Example:** G00 Z100 |
| ![g01](http://cncsimulator.info/OnlineHelp/lib/NewItem439.png) | Travel in a straight line using the programmed feed rate (F). This code is used for machining.<br>**Format:** G01 [X#][Y#][Z#][F#]<br>**Example:** G01 X2.5 Y4.1 F200 |
# Reference
- [V² >  Plan > Flow > Mechanical Design > NC Codes](https://v-squared.github.io/plan/flow/mechanical/nc-codes/)
- http://cncsimulator.info/OnlineHelp/OnlineHelp.html

**Comment by VillageMichaelLin** [comment]
@VillageHubertChen  @LukasChen I updated the G-code and M-code I used in above comment
