### ISSUE TITLE
Accordion Folding in Article Group

### ISSUE THREAD

**Issue by LukasChen** [V-Squared/V-Squared.github.io#207]
# Tasks
- [x] Copy UI bootstrap accordion to V²Site
- [x] Minify it
- [x] Specify custom template via text/ng-template
- [x] We use Angular UI Bootstrap for Accordion Menu
  - [x] We use it as is with no modifications
- [x] We change the structure of our book-bar.yml to accommodate it
  - [x] New structure: Split into Group & SubItems
- [x] Step1: Make Demo in CodePen, 3 Levels Accordion, No Liquid
  - [x] Learn how to use Accordion of Angular UI Bootstrap
- [x] Step 2: Make same code to work in Local V²Site, but hand coded page
  - **Note:** It was working before, if it does not work now, it must be a conflict
  - [x] Debug any conflicts of Demo Code with V²Template / V²Site
  - [x] Implement Accordion on Article-Bar for one Page
  - [x] Implement Accordion in Off-Canvas for one Page
- [x] Put into V²Template with Liquid
  - **Note:** If does not work, all you need to debug is to get same HTML code in the page
  - [x] Implement Accordion on Article-Bar for all Pages
  - [x] Implement Accordion in Off-Canvas for all Pages
  - [x] CSS Styling
# Fixing Bugs after first release
- [x] **Intro in Off Canvas:** 1) Rename to Index 2) currently shows 404 error
- [x] Contents-Bar does not show → https://v-squared.github.io/plan/road-map/how-it-works/
- [x] Fix issue that on unfolding the footer may overlap the Article Bar
- [x] https://v-squared.github.io/plan/agile/ shows content in Article-Bar but not in Off-Canvas Menu
