### ISSUE TITLE
V² > Plan > Flow > Publishing > Intro

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#213]
# Generic Tasks
- [x] Create Issue
- [x] Add Link to Article in Reference of this Issue
- [x] Classify Labels, Milestone & Assignee
- [x] Create Article
- [x] Create Title / Subtitle / Abstract
- [x] Enter Issue No in Article
- [x] Write Article
- [x] Add cross references
- [x] Trigger review
# Specific Tasks
- [x] rename "Writing Articles" to "Publishing"
# Tasks for Tom
- [x] Review / edit title, subtitle & abstract
- [x] Edit the entire article. Especially clean out my Ginglish (German English)
- [ ] Create the [Manual Table of Contents](https://v-squared.github.io/plan/flow/writing/advanced-formatting/#manual-toc)
- [ ] Add missing content
- [ ] Check the flow. Fix if broken.
- [ ] Once you are done write a comment to trigger me to review your work
# Reference
- [V² > Plan > Flow > Writing Articles > Intro V²Flow.Publishing](https://v-squared.github.io/plan/flow/publishing/intro/)

**Comment by VillageHubertChen** [comment]
# Review of Tom's edit
- [ ] You need to work down your to do list. Your job is done after you ticked all boxes.
- Great edit. I truly enjoyed and learned
- I created: [Frequently Made Mistakes](https://v-squared.github.io/plan/flow/publishing/mistakes/)
  - [ ] please check it out and give your comment in its article issue
- [ ] Please conform you want to keep the sentenc: "For those for whom the above chapters were too much prose – here come the hardcore benefits:" It does not sound right to my ears.
- "How it works" paragraph was an exceptionally nice rewrite! Well done!
- [ ] please trigger me for final review and bumping readiness to "Make" by making a comment after you ticked all boxes.
