### ISSUE TITLE
Refactoring Tabbed Slide Show on V² Home Page (aka Big Picture)

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#216]
# Tasks
- [x] Research that all parts of angular you want to use do not turn on routing
- [x] Publish a list below of all parts that turn on angular routing for future reference
- [ ] Write documentation on the new tabbed slide show
- [ ] Trigger HC to review documentation
- [ ] Code the new tabbed slide show
- [ ] Trigger HC to test on local machine
- [ ] Push to V²Site, trigger HC for immediate testing
- [ ] Fix bugs if needed. Repeat until all is well.
# Why refactoring became necessary

The current version was based on $location. This angular object automatically turned on Angular Routing. In turn this broke anchors on a page based on hashtag. This is discussed in detail in → [Ben Nadel > Using Anchor Tags And URL-Fragment Links In AngularJS](http://www.bennadel.com/blog/2869-using-anchor-tags-and-url-fragment-links-in-angularjs.htm).

To fix → Bug: Stop Angular from Rerouting Hashtag #154 we had to turn off angular routing. As such we needed to remove $location. In turn we broke the _Tabbed Slide Show_ on the Home Page. And that is why we need to refactor it.
# Replacing $location with Angular Scroll Service

??? Lukas, do explain!
# Order of initialization (least to most important)
1. On startup open the first tab
2. Specify attribute with two way data binding
3. Look at the URL and select the tab according to hashtag
# References
- [V² Home Page](https://v-squared.github.io/) Scroll to tabbed slide show.
- The Big Picture of V² (Part of V² Home Page) #35
- Refactoring V² Home Page #123
