### ISSUE TITLE
Epic > 021 > Parent: DIY Portable All-in-One

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#217]
# Tasks
- [x] HC: Create → [Part List](#issuecomment-234144624)
- [x] BC, TC: Initial shopping. Find real parts as in check what will be available
- [x] ML: Draft Design Computer in Solidworks Assembly. Trigger HC for review
- [x] HC: Review, Trigger Review with TC & BC
- [x] HC: Write ECL for Michael
- [x] ML, HC. Create → [Preview on the Design](#issuecomment-234238591)
- [x] BC: Shop all parts on Amazon
- [x] HC: Write → [Engineering Change List v2](#issuecomment-234436618)
- [x] ML: Create Design v2
- [x] HC: Get feedback on Design v2 from GI, SL, TC, BC
- [x] [Engineering Change List v3](#issuecomment-234526804)
- [x] ML: Finalize Drawings according → [Engineering Change List v2](#issuecomment-234436618)
- [x] HC: Write Article 'V² DIY All-in-One'
  - [This Article](https://v-squared.github.io/diy/aio/portable-diy-aio/)
  - Create List of Drawings
  - Create List of all Snaps
  - Write Purpose Chapter (As slide show with title and subtitles showing features / use)
  - Write Assembly Steps (Same style as using in Instructables)
- [x] ML: Create all files according to above lists
- [x] HC: Process all images for Features. Then upload to GitHub sub directory.
- [x] HC: Add all files to articles
  - [x] Images
  - Design files using download links
- [x] HC: Review with Tom on his morning walk
- [x] HC: Review and include feedback GI
- [x] HC: Review and include feedback SL
- [x] HC: Transfer all items in shipping list present in issue but not yet in article.
# Reference
- [This Article](https://v-squared.github.io/diy/aio/portable-diy-aio/)

**Comment by VillageHubertChen** [comment]
# Part Lists

## Shopping List Mechanical Parts
- [Wood Shelving / Common Board Pin Wood actual 0.75" x 11.25](http://www.lowes.com/pd/Pine-Board/1000070173)  (minimum 4 feet long)
- [Brass Spacer, threaded M3, hex shape, height 25 mm or 1 inch](https://www.amazon.com/Brass-Threaded-Spacer-25mm/dp/B013G1H6HO/)
- 3/4" quarter round molding
  - Nailed on edge of floor board. Prevent keyboard to slide out of the keyboard shelf
- card board, single flute, micro flute, about 3 mm thickness, strong hard paper, maybe 200 gsm or better. Brown or black color. About 3 ft x 3 ft
- 25 mm Ø wood drill. Type: "Flat Spade" or "Forstner" for hand grip
- 20 mm Ø wood drill. Type: "Flat Spade" or "Forstner" for AC Socket
- VESA Wall Mount. → Luxury ViCase-Stand #126
  - pick one that has 4 mounting holes to the wall. 2 will not be enough using wood screws.
- Cable Ties that can open many times. Screwed to base board
  - Either same type as we used in ViCase / ViCase-Stand
  - Wood screws plus copper wire 0.8 mm, single strand
- Wood paste
- Lacquer Spray Can, fast dry, red (Choose color to your taste. Red may go well with cardboard brown)
- Lacquer Spray Can, fast dry, transparent
- Black Grill / Mosquito Net

# Parts you may already have
- HSS Metal Drill Bits: 
  - 1.5 mm Ø (drill holes in hard wood profile for thin nails to avoid splicing the wood)
  - 3 mm Ø (drill holes for M3 screws, core holes for W5 screws to avoid splicing wood)
  - 5 mm Ø (Drill holes in Base Board and Back Board to connect with W5 screws )
  - Countersunk Drill Bit
- Small wood nails. About 1.5 mm Ø, about 20 mm long
  - To nail the hard wood profile to the foot board
- Rubber Grommet, 3 mm interior Ø ( we will find on amazon, optional)
- M3 Screws, Pan Head, PH2 or PZ 2 drive
  - 10 mm (Mounting Motherboard to Brass Spacer)
  - 25 mm (for HDD in case above not long enough and for mounting Spacer)
  - 30 mm (in case the wood was thicker than anticipated)
- M4 x 10 mm, Pan Head, PH2 or PZ2, (for mounting VESA bracket to Display)
- M3 washer, to shorten the M3 screws for HDD without actually cutting them
- Wood screws, 5 mm Ø, countersunk, PH2 or PZ2
  - 20 mm (thin bracket material with countersunk hole), (mount VESA Bracket to Base Board)
  - 25 mm (in case of bracket to be of thicker material)
  - 40 mm (Connecting Boards: 1) Base to Side 2) Side to Back
- Wood screws, 4 mm Ø, Pan Head or better Flat Head, PH2 or PZ2, black
  - 10 mm (screw card board housing to base board)

# Tools & Glue
- Wood file
- Sand paper: 90, 180, 360, 600
  - try to find linen based versus paper based, not critical but better for sanding hand grip.
- Wood glue

# Cut List
- Floor Board: 300 x 300 mm (natural width, cut to 300 mm length, cut need 90° precisely)
- Base Board: 300 x 550 mm (natural width, cut to 550 mm length, cut need 90° precisely)

**Comment by bcaswelch** [comment]
# Amazon Shopping List
- 1 x [Intel i3 6100](https://www.amazon.com/dp/B015VPX2EO/) $125
- 1 x [Asus B150 Mini ITX WiFi](https://www.amazon.com/dp/B01AZ7N31A/) $125
- 2 x [Kingston 4 GB DDR4 memory](https://www.amazon.com/dp/B00TY6A56U/) $54
- 1 x [Samsung 850 EVO 250 GB](https://www.amazon.com/dp/B00OAJ412U/) $92
- Windows 10 
- [Brass Spacer, threaded M3, hex shape, height 25 mm or 1 inch](https://www.amazon.com/Brass-Threaded-Spacer-25mm/dp/B013G1H6HO/)
- [HDPLEX 160W AC-DC](http://www.hd-plex.com/HDPLEX-Internal-160W-AC-DC-Adapter-with-Active-PFC-and-19VDC-Output.html) $55
- [HDPLEX 160W DC-DC](http://www.hd-plex.com/HDPLEX-160W-DC-ATX-Power-Supply-16V-24V-Wide-Range-Voltage-Input.html) $35

# Important Notes
- [x] Why did you added a WiFi Adapter when the Mobo already has one? → Mistake
  - [Wifi adapter](https://www.amazon.com/Panda-Wireless-PAU06-300Mbps-Adapter/dp/B00JDVRCI0/ref=sr_1_4?s=pc&ie=UTF8&qid=1469079506&sr=1-4&keywords=usb+wifi+adapter) $20
- [x] By choosing 2 x 4 GB you get 200% the speed of 1 x 8 GB → Got that
- [x] Want 200 % SSD speed for less money than 100% ? 2 x 120 GB → Will not make experiment now, see below comments
  - [120 GB Kingston SSD](https://www.amazon.com/dp/B00A1ZTZOG/) 2 x 43 = $86 < $92

**Comment by VillageHubertChen** [comment]
# Preview on the Design

![vicase-aio-diy-front-right](https://cloud.githubusercontent.com/assets/7278716/17022575/5b16858c-4f81-11e6-8045-fc660dc99ba1.jpg)

![vicase-aio-diy-side-left](https://cloud.githubusercontent.com/assets/7278716/17022584/69e20d52-4f81-11e6-9c60-4f334346bc78.jpg)

![vicase-aio-diy-rear-left](https://cloud.githubusercontent.com/assets/7278716/17022595/780d19d0-4f81-11e6-8a89-c80d5981926c.jpg)

![vicase-aio-diy-rear-right](https://cloud.githubusercontent.com/assets/7278716/17022603/817c8884-4f81-11e6-80fd-901d77ce7672.jpg)

![vicase-aio-diy-rear-open](https://cloud.githubusercontent.com/assets/7278716/17022609/88a6cfa2-4f81-11e6-9381-3446f48f2843.jpg)

**Path to Images:** `C:\Users\Mini\Documents\Marketing\ViCase-ViPC\ViCase-AiO-DIY\Web-Ready`

**Comment by bcaswelch** [comment]
1) Regarding the Kingston V300, this is an entry level SSD with slow read/write performance compared to the samsung 850 EVO. If I was buying a workstation computer, I would not want to buy a low end solidstate and would spend the extra money on a proven and fast disk. New firmware in the V300 also shows a huge decrease in performance for the drive (http://www.anandtech.com/show/7763/an-update-to-kingston-ssdnow-v300-a-switch-to-slower-micron-nand)

**Comment by VillageHubertChen** [comment]
@bcaswelch 

If the Kingston has questionable firmware then do not touch it. I have seen computer performance to collapse due to firmware and driver issues. I never heard of such issues regarding Samsung SSD. So go with the safe choice. The last thing we want to do now is to build another unreliable computer for Tom.

But at a later time we should research and test an SSD RAID 0 configuration and add it to our configs. I know people who are using SSD RAID 0 and feel a significant boost in real life over single SSD. We may just need to go with better drives. It was a pity Samsung had removed the 120 GB SSD? Or was it just in that place?

**Comment by bcaswelch** [comment]
@VillageHubertChen 

Samsung still has a 120gb 850 EVO drive, but for $70. For testing how RAID works, I think thats a price point worth going for. Two 120gb EVO drives would be very strong performance wise.

Also forgot to mention in my first comment but I love the design mockup! Gives me a very clear idea of how to make it and I'm looking forward to doing some old-fashioned prototyping :)

**Comment by VillageHubertChen** [comment]
But 2x $70 is not really a bargain vs 1 x $90. Plus the 120 GB is slower than the 240 GB. So value as in speed for money could be worse for the RAID 0 and not better. So we will need to look out for the right combo. Maybe today need be a 2 x 240 GB SSD, as then it is same price as a 1x 500 GB SSD. It looks we are at a point where the 250 GB is no longer sweet spot for RAID 0, but 500 GB is now.

**Comment by VillageHubertChen** [comment]
# Engineering Change List v2

This is the Engineering Change List (ECL) for above design, after thorough review:

# Overview
- [x] Add CGND and DGND wiring (Earth and Digital Ground)
- [x] Add AC wiring so Power Supply (PSU) and Display are powered with only one C13 socket
- [x] Change AC wiring to be made up of ready made parts, all of which are UL approved.
- [x] Write Parts Definition
- [x] Write AC Wiring
- [x] Write Ground Wiring
- [x] Write Computer Cable Wiring
- [x] Write Assembly Process
- [x] Create new Snap Shots

# Oversights:
- We need Extension Cord / Splitter in the AiO to make it a one plug experience
- Ground wiring
- Research: Earth / Ground Terms
- We need a schematic for wiring
- Use a Conduit Strap aka steel two hole strap. to fix the AC S
- C13 Y Splitter Cable, mounted with Conduit Strap to Floor Board
- Base Board
- Bottom Board
- Side Board

Earth wiring with Terminal Wire

Yellow wire with Ring Terminals 

Wiring code of colors

Gauge AWG 18 or 16

# Notes
- https://www.amazon.com/dp/B00UKUDEN0/
- Connecting all C-Grounds: two stand offs 10 mm, connected in the middle, connecting all Ring Terminals. 

Y- Splitter

https://www.amazon.com/Tripp-Lite-IEC-320-C20-IEC-320-C13-P032-002-2C13/dp/B003N380E4/ref=pd_sim_sbs_23_6?ie=UTF8&dpID=412gkosPJCL&dpSrc=sims&preST=_AC_UL160_SR160%2C160_&psc=1&refRID=K6MHX5Q84Y1XPNBYJJWM

Brass Stand Offs
https://www.amazon.com/Hilitchi-120pcs-Female-Standoff-Assortment/dp/B018C19KJ0/ref=sr_1_2?ie=UTF8&qid=1469155098&sr=8-2&keywords=male+female+brass+spacer

Topic Tom next morning. Understand his photography experience
Lighting & Backgrops

**Comment by VillageHubertChen** [comment]
# Parts Definitions

| # | Name | Function |
| :-: | --: | :-- |
| 1 | Back Board | Holding Display, Motherboard, Disks, Power Supply |
| 2 | Base Board | Base / Foot of case |
| 3 | Side Board | Connects Base Board to Back Board |
| 4 | Socket of Y-Cable | C14 Socket of AC Y Cable. (We did not draw the cable) |
| 5 | AC Socket of PSU | C14 Socket of AC Input Cable of Power Supply Unit (We did not draw the cable) |
| 6 | VESA Display Mount | Connects Display to Base Board |
| 7 | Conduit Strap | Mounting C14 sockets to Base Board |
| 8 | Reopen able cable tie | Organize all cables within the case |
| 9 | Bracket for Remote Switch |  |
| 10 | Remote Switch | Status LEDs, Power On Switch, USB ports |

# Reference
- https://en.wikipedia.org/wiki/IEC_60320#C14

**Comment by VillageHubertChen** [comment]
# Electrical Wiring

## AC Wiring
- [x] [C14 - C13 Y Splitter](https://www.amazon.com/dp/B00UKUDEN0/) $7
- [x] [Computer Extension Cord C14 C13 4ft](https://www.amazon.com/dp/B000067RRX/) $3
- [x] [Spacer / Screw Assortment](https://www.amazon.com/dp/B018C19KJ0/) $12

## DC GND Wiring
- The Grounding cable of the HDPLEX AC-DC PSU is screwed in between two 10 mm Brass spacer
  - one spacer is male-female, other space is male-male. Ring terminal goes in between their mating
  - ATX cable of DC-DC PSU plugs into motherboard and connects DC GND
  - DC Ground is connected to mounting holes of motherboard
  - Motherboard is connected with M3 screws to spacer, one of which is connected to GND of AC-DC PSU 

## Images

### Grounding Cable Assembly

![Grounding Cable Assembly](http://customcable.ca/wp-content/uploads/2012/01/Grounding-Cable-Assembly-With-Terminal-Lugs.png)

### Galvanized Conduit Strap

![Galvanized Conduit Strap](http://www.essentialhardware.com/media/catalog/product/4/1/410264.jpg)

**Comment by VillageHubertChen** [comment]
# Aura Lighting

The Asus board has "Aura Lighting". We shall investigate this feature. ViCase is already designed to accommodate LED lighting strips. It may be very easy to plug them in.

**Comment by VillageHubertChen** [comment]
# Additional Amazon Parts
- [x] [Adjustable Cable Holder](https://www.amazon.com/dp/B00WW6ZFTQ/)
- [x] [Power Switch & Status LEDs](https://www.amazon.com/dp/B00LQAUIKA/)

**Comment by VillageHubertChen** [comment]
# Engineering Change List v3
- [x] Change connection method of Side Board to other board using small L-Brackets
- [x] Change to 28" Display
- [x] Add small [speaker bar](https://www.amazon.com/usb-speaker-bar/dp/B01B6197JG/), mounted to back board, behind display
- [x] Add [goose neck microphone](https://www.amazon.com/goose-mic/dp/B00UZY2YQE/) mounted to Back Board. Balance space for microphone & speaker.
- [x] Head set holder: Hook, screwed into side of Back Board. Hang Headset to it
- [x] Add shoulder strap with holes + carabiner
- [x] Search the original AiO drawing. Review with HC anything else Missing
- [x] Add airflow arrows
- [x] Switch mounting of VESA bracket to M4
- [x] Import Pinochio for a snapshot carrying the Portable Workstation
- [x] Add side walls to keyboard shelf. Talk to HC on break out design for keyboard.
- [x] Mouse Placement in Keyboard Shelf. Check that both fit
- [x] Add Pencil and Eraser in Keyboard Shelf
- [x] Create three Drill Templates: 1) Top Grip, 2) Mobo + Disks, 3) AC-DC and DC-DC PSU
- [x] Create Updated snapshots
- [x] Create updated cardboard. Including fold marks. Spread screws evenly. Cosmetics over 5 cm grid.
