### ISSUE TITLE
Board Structure: V² > Standards

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#219]
# Tasks
- [x] Create Page Structure
- [x] Write Front Matter for each Intro Page
- [x] Rename all related issues to carry "Board Structure" in their title
- [x] Cross link all "Board Structure" Issues
- [x] Get feedback SL
- [x] Rewrite according to feedback
- [x] Trigger BC to edit the writing in place
- [x] Get feedback SL → approved with flying colors
- [x] Get feedback GI, include feedback.
- [ ] Update the Tab of Standards in the tabbed slide show on homepage
- [ ] Create issue to create the Standard Section. Then create it.
- [ ] Create Issue to move V² > Plan > Flow and then move it.
- [ ] Create Issue to move V² > Plan > Agile and then move it.
# Problems this V²Standard structure solves
- Deliver respectable content in Standard board of V² Site
- Solve double content problem of V²Plan. Now it is all about "The Plan", nothing else.
- Show growth and schedule of standards, consistent with Road Map in Plan.
- Schedule of creation of standards is spread out to be realistic in terms of delivery
# Page Structure of V² > Standards

```
V² Home Page
     ├ Standards
     │     ├ V² White Paper
     │     │     ├ Missing Standard
     │     │     ├ 3rd Evolution Open Source
     │     │     ├ Portable All-in-One
     │     │     ┊
     │     │     └ Markdown Publishing
     │     │
     │     ├ V² Workflows
     │     │     ├ V²Publishing
     │     │     ├ V²CAM
     │     │     ├ V²Agile
     │     │     └ V²Art
     │     │
     │     ├ V² Modular PC
     │     │     ├ V²PC-Feet
     │     │     ├ V²PC-Bracket
     │     │     ├ V²PC-Access
     │     │     ├ V²PC-Stand
     │     │     ├ V²PC-Lights
     │     │     ┊
     │     │     └ V²Case-Duino
     │     │
     │     ├ V² PC Usability
     │     │     ├ V²Repair
     │     │     ├ V²Noise
     │     │     ├ V²Clean
     │     │     ┊
     │     │     └ V²Upgrade
     │     │ 
     │     ├ V² Compatibility Logo
     │     │     ├ V²Logo-White Paper
     │     │     ┊
     │     │     └ V²Case-License     
     │     │
     │     └ V² Data Models
     │           ├ V²Configurator App
     │           ├ V²Config Model
     │           ┊
     │           └ V²Config Data
     │
     ├ Products
     ├ Makers
     ├ DIY
     ┊
```
# Front Matter Intro Pages
## V² White Paper
- **title:** V² White Paper
- **subtitle:**  Purpose, theory, and analysis of V² standards, products, and projects.
- **abstract:** Our white papers analyze the needs, provides theoretical backgrounds, and finally compares our V² solutions with existing ones.
## V² Workflows
- **title:** V² Standardized Workflows
- **subtitle:**  Missing Standardized Workflows for our community and others.
- **abstract:** To make the V² Modular PC movement a success we need lots of high quality content. Common problems on creating a large body of work with many contributors have inconsistencies of all kinds; they frustrate the reader and eventually drive him away. This is what standardized workflows are for. V² Workflows delivers the missing workflows, guiding contributors with step by step instructions to deliver production ready contribution without requiring time consuming reworks by the editor / curator or manager. These workflows are open source and licensed under creative commons. They may be useful to other teams as well.
## V² Modular PC
- **title:** V² Modular PC
- **subtitle:**  The Missing Standards for Modular Mini & All-in-One PCs
- **abstract:** Building a modular Mini or All-In-One computer was difficult, if not impossible in the past, due to missing key components. And even for those components in existence key specs were not standardized, making it hard to predict compatibility to a mini case. The V² Modular PC standards solve these problems. These standards will be published when we officially announce availability of V² Modular PC standards at Computex Taipei in June 2017.
## V² PC Usability
- **title:** V² PC Usability
- **subtitle:**  Classifying and quantifying PC user experience.
- **abstract:** Making V² Modular PCs more enjoyable in daily operations is good for the user and as such is a good sales point too. We provide design guides, design requirements, measurement procedures, classifications, user manual templates all on concrete topics of usability, providing a measurable improved user experience. The usability standards will be published somewhat after the  initial publication of V² Modular PC standards. 
## V² Compatibility Logo
- **title:** V² Compatibility Logo
- **subtitle:**  Improving the shopping and assembly experience of V² Modular PC user.
- **abstract:** V² Logo is a tool to assist consumers in their buying process and at the same time to assist makers and retailers in their sales efforts. We believe the V² Logo program is a community service. As such, it is developed within the community and we are making licensing as transparent and straight forward as possible, all at no cost. The V²Compatibility Logo Program will be published after Computex 2017. Examples of successful logo programs would be USB (TM), HDMI (TM), etc ...
## V² Data Models
- **title:** V² Data Models
- **subtitle:**  Standardizing Data Models, APIs, and Apps for Configurations
- **abstract:** Creating a PC configuration, data sheet, upgrade instructions, and product configurator are all repetitive and tedious tasks that are all best left to a computer application. V² Data Models delivers standardized data models, APIs and even working applications to assist the web programmer of a shop or a computer manufacturer. They are all open source licensed under Creative Commons. They are simple, yet shorten development time and simplify business-to-business (B2B) interfacing.
# Reference

Board Structure: V² > Standards #219
Board Structure: V²►Products #113 
Board Structure for V²►Plan #78 
Board Structure of V²►Organization #80 
Board Structure for V²►Spreading #82 
Epic►011►Parent: Board Structure for V²►DIY 2016W23 #122
