### ISSUE TITLE
Cleaning up V² Plan > Road Map

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#221]
- [ ] HC: Restructure Articles → below: New Road Map Article Structure
  - [x] create new structure, reorganize existing articles, upload and link
  - [ ] clean up inconsistencies, repair broken links if any
  - [ ] restructure content of linked issues
  - [ ] Create Article "Standard Life Cycle", restructure content, restructure issue, rename linked issue
    - unused article: next-2-years.md →lifecycle.md / issue 193
  - [ ] Write Avalanche Partnering
  - [ ] Simplify Titles, Subtitles, Abstracts
  - [ ] Plan Overview Article: Same tabbed slide show as from home page
- [ ] Create all Titles for all Road Map Articles
  - [ ] Try the new method of generating 3D text in LibreOffice and compose in GIMP
- [ ] True North Illustration
  - [ ] Create Issue for Bobby to add 3 Pages
  - [ ] Clean out old writing from Article
  - [ ] Add True North & You are here to all 3 relevant Articles
- [ ] Simplify titles of all Road Map Articles, so they read very easy on _Index Page_
- [ ] Write a simple Avalanche Partnering Concept
# New Road Map Article Structure
- Index (no change)
- Overview (old name: How it works)
  - Content of Article "Next 2 Years" is also copied to here
- Avalanche Partnering (old name: 2011-2021) 
  - New content about how a campaign escalates in reach like an avalanche incorporating bigger partners
- Campaign 1
- Campaign 2
- Campaign 3
- to be deleted: "Next 2 Years" but first:
  1. Move content
  2. Close related issue and explain what happened on close
# Pyramid Image
- `\V-Squared.github.io\images\illustrations\v2-flow-pyramid`
- [ ] Set up ArtBrief with linked issue, format of normal article, but stand alone at this time)
- [ ] Set up related Issue
- [ ] Tasks for Bobby
  - Add 3 Boxes for:
    - True North: Where we want to be
    - Road Map: Lead the way
    - Dashboard: Organize our daily development
- [ ] HC: You are here!      True North: Where we want to be. 
- [ ] HC: V² Agile Layer Model need to be Image Title! (all three pages)
# Reference
- Cleaning up V² Plan #222
