### ISSUE TITLE
V² > Products > ViStand > Features

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#225]
## Create
- [x] HC: Create Issue
- [x] HC: Create Article in Classeur, cross link issue vs article
- [x] HC: Share with co-writers
- [x] HC, TC: Create Outline
- [x] HC: Set Progress Bar to "Create-Complete"
## Develop
- [x] HC: Set Progress Bar to "Develop-Active"
- [x] HC, TC: Fill in Content to Outline
- [x] HC, GI, TC: Develop Art Briefs
- [x] HC: Create Structure in V² Art / Move Art Briefs to V² Art
- [x] ML: Create Images
- [ ] Image Processing & Linking Images to article
- [x] HC: Set Progress Bar to "Develop-Complete"
## Beta
- [x] HC: Set Progress Bar to "Beta-Active"
- [x] HC: Trigger TC, BC, SL to review Article and to create change requests via V²Flow
- [ ] TC: Include all change requests that you can
- [ ] TC: Trigger reviews by shops, MUG, schools, universities
- [ ] TC: Include all change requests that you can (text)
- [ ] HC, LC: Include remaining change requests (art, coding)
- [ ] TC: Write post to announce beta testing of this article in our Blogs
- [ ] HC: Set Progress Bar to "Beta-Complete"
## Finishing the page
- [ ] LC: Change in YML: layout: feature
- [ ] LC: Change: "Universal VESA Computer Mount" → vertical tabs with cards.
- [ ] HC: Image Processing, clean up structure in V² Art, Clean up cropping, etc ...
- [ ] HC: Create a page for legals and trademarks, move last item to there
## Make
- [ ] HC: Set Progress Bar to "Make-Active"
- [ ] Read the Article in context of navigation. Fix any inconsistencies
- [ ] Read the Article in context of related articles. Fix any inconsistencies
- [ ] Read Article cover to cover. Fix flow if not smooth.
- [ ] HC: Set Progress Bar to "Make-Complete"
- [ ] TC: Write post to announce this article in our Blogs
## Open Sales
- [ ] Complete buy pages in shop
- [ ] TC: Post stripped article in Quora, linked to here
- [ ] BC: Post DIY Articles on instructables
