### ISSUE TITLE
Navbar Rendering Issue on Mobile

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#27]
# Two Bugs

![nav-bar-problem-on-mobile](https://cloud.githubusercontent.com/assets/7278716/14096579/922b0ea6-f59c-11e5-8cd2-f69f6595576c.png)
## Bug 1: Cut Navbar on Mobile

Top of Navbar is cut, see the screen shot
## Bug 2: Double Highlight

Sometimes during navigation two sections are highlighted the same time, see screen shot
# Tasks
- [x] @LukasChen Reproduce issue in Simulation
- [x] @LukasChen Fix Issue, upload to GitHub, Trigger Bobby to test
- [x] @bcaswelch Test the new version when triggered by Lukas. Close issue when fixed

**Comment by VillageHubertChen** [comment]
Issue was closed by accident when Lukas attached Issue number to commit. I reopened it. We need Bobby's confirmation that issue is fixed. Then he will close it.
