### ISSUE TITLE
Better separation of Sections in Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#28]
# Problem

When fast scrolling the [V² Home Page](http://v-squared.github.io/) it is easy to overlook when changing sections.
# Suggested solution

Bobby, please report here your ideas or trigger chat to brainstorm
# Tasks
- [x] @bcaswelch Report issue
- [x] HC: Reproduce issue: Agreed!
- [ ] @bcaswelch Suggest a solution, if you have no idea, start chat in comments on this issue, trigger me on skype
- [ ] HC Document proposed solution, then trigger LC to implement
- @LukasChen Implement solution
- @bcaswelch Test if fixes the issue. If so, close issue.
