### ISSUE TITLE
Timeline in Introduction

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#30]
# Heading and Copy

→ #23 
# Coding Interaction with SVG [LC]
## Tooltips
- Works the same as with Puzzle SVG → #22 
- HC will specify the Tooltips
## Pan and zoom control
- [Pan and zoom control](http://www.petercollingridge.co.uk/interactive-svg-components/pan-and-zoom-control)
## SVG graphics
- it will be very wide and not high. This is why we need zoom and pan for mobile.
- SVG graphics provided by HC
## Tooltips
- HC will list the Tooltips here ???
## Reference
- [Pan and zoom control](http://www.petercollingridge.co.uk/interactive-svg-components/pan-and-zoom-control)
- [Using Javascript to control an SVG](http://www.petercollingridge.co.uk/data-visualisation/using-javascript-control-svg)
- [Interactive SCG Components](http://www.petercollingridge.co.uk/book/export/html/437)
# Drawing the SVG [HC]
- C:\Users\Mini\Pictures\Art\Illustrations\Time Lines\ViDock G6 Early Time Line
- Convert from Vertical to Horizontal
- Move detailed text into this issue under "Tooltips"
# Tasks
## Coding Interaction with SVG [LC]
- [x] @LukasChen Test if [Pan and zoom control](http://www.petercollingridge.co.uk/interactive-svg-components/pan-and-zoom-control) works on our tablet → It does. The UI Controller need to be bigger to be usable with touch screen.
- [ ] @LukasChen Adopt and port the  [Pan and zoom control](http://www.petercollingridge.co.uk/interactive-svg-components/pan-and-zoom-control) to our V² Home Page into the section "Timeline" in Introduction. Use the SVG of that example, but make it work within the responsive design of our page and make it work on a mobile. Then Trigger HC for testing.
- [ ] @LukasChen Replace the "Australia" SVG with our final "Timeline" SVG. Then Trigger HC for testing.
## Drawing the SVG [HC]
- [ ] HC Move detailed text into this issue under "Tooltips"
- [ ] HC Draw Timeline, then upload to GitHub and trigger LC to implement
