### ISSUE TITLE
Closing V² Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#33]
# Page Structure
1. Site & Page Navigation
2. Jumbotron
3. Feature Intro
4. Portfolio
5. Footer
# Site & Page Navigation
- The Side Bar Navigation is removed. We love it, but it clashes with Section Heading background
- Site and Page Double bar: [Hero Page](http://www.avira.com/en/avira-phantom-vpn)
  - 1st Row: Site Navigation w/o Mega Menu
  - 2nd Row: Page Navigation with Breadcrumbs:
- Behavior Big Screen
  - Both rows show at first
  - When scrolling down page Navigation is sticky
- Behavior Small Screen
  - Only Site Navigation shows first. It only shows Phoenix Logo and Menu Icon
    - Menu Icon opens off canvas menu
    - We move off canvas menu back to left side, as we have removed Side Bar Navigation
  - Not sticky
  - Page Navigation is accomplished with Accordion
- Middle Sized Screen
  - We will define behavior after making behavior for big and small screen
# Jumbotron
- Use the Team on Stairs picture
- Process to have lower contrast, make it duotone
- [Hero Jumbotron Background](http://www.avira.com/en/free-antivirus-windows)
- Update new, shorter text
- Design ideas for Jumbotron
  - https://training.github.com/
  - https://www.codeschool.com/?utm_source=github&utm_medium=codeschool_option&utm_campaign=trygit
# Feature Intro
## Publish new text of Feature Intros
- Copy from this Issue → ???
- Layout: LC show Hero Page ???
- Finish remaining visuals
## Puzzle
- Replace SVG with final drawing
- Add Tooltips
## Road Map
- Finish SVG drawing
- Add tooltips
- Add Pan and Zoom for mobile support
# Portfolio
### Colors
- Each section has its own color, consistent with the Puzzle (rainbow)
- Background color is middle tone of section color
- Text and puzzle piece are strong tone of section color
- Section background color is light tone of section color
- Ordering of sections will be in order of rainbow color (check to have same order in puzzle)
- Puzzle piece is shown left of container
### Folding
- Same Arrow and same folding as in V²Configurator
- Open one fold, close the other. Scroll to top of unfolded section.
# Images
- Process Images already rendered
- Draw design place holders, get approval from Bobby / Sascha
- Render Images
- Image Processing
- Add to home page
# Tasks
## Monday Lukas
- [x] Double Navigation Bar
- [x] Remove Side Bar
- [x] Add Jumbotron
## Tuesday Lukas
- [x] Copy text of Feature Intro, make simple feature layout with image place holder → #23 
- [x] Add Site Map to Footer → #26 
## Wednesday
- [x] Add Tooltips to Puzzle,  → #22 
## Thursday
- [x] test is puzzle tooltips work on tablet  → #22 → Yes, works great!
- [x] make puzzle centered puzzle → #22 
- [x] make puzzle responsive → #22 
## Friday
- Add final puzzle svg
- Change color theme of puzzle & Portfolio Titles
- Finalize Layout of Introduction
- Add Value Proposition to Introduction

**Comment by VillageHubertChen** [comment]
The purpose of this issue was to guide us to crate the V² Home Page into a stage where its design intent is directly recognizable and no longer needs description to tell the developer where we want to go. This has been accomplished. As such we are closing this issue.
