### ISSUE TITLE
Epic►004►Parent►Hackathon V² Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#41]
# Tasks already Completed
- [x] Cleaning up to park v2-Tab Repository. Leave Issues Open
- [x] @LukasChen Cleaning up to park v2-Tab Repository. Leave Issues Open
- [x] Create content of V² Home Page Features (Meeting with Georg) → #23 
- [x] Finish writing on Features
- [x] @LukasChen  Prepare a list of Material Design Template
- [x] HC, LC: Pick a Material Design Template
- [x] @LukasChen Adapt Material Design Template to V² Jekyll
- [x] @LukasChen Apply the design to the V² Home Page
# Final leg on this Hackathon
- [x] Creating References with all Issues related to V² Home Page
- [x] Assign all open V² Home Page issues to Sprint Next
- [ ] LC: Do → Refactoring V² Home Page #123 
- [ ] LC: Make V² Big Picture Slideshow work on Mobile #172 
- [ ] HC: Complete → V²Plan on Home Page #103 
- [ ] HC: → Draw Illustration: "V² Big Picture" aka "V² Puzzle" #38 
- [ ] HC: Draw → Timeline in Introduction #30 
- [ ] HC: Do → Draw V² Icons #171 
- [ ] HC: Add one more Feature → Making contribution easy for anyone! #149 (Use V²Icons)
- [ ] HC: → Add Links on V²Home to Repositories #6 
- [ ] HC: → Better separation of Sections in Home Page #28 
- [ ] HC: → Visuals V² Home Page #2 
- [ ] HC: → Full Review Home Page #17 
## Hero Layout
- http://electron.atom.io/
- [x] Find the other issue where we spell out the feature section of home page
  → https://github.com/V-Squared/V-Squared.github.io/issues/23
## Targets
- All sections in list look finished enough, are fully functional, work on all screen sizes. They look great in all sizes!
- Use Google Material Design. Benefit from their templates as much as possible.
  - https://developers.google.com/schemas/now/cards#a-flight
- Puzzle SVG is final design and final color code
- Use consistent colors on Puzzle, Tab and Boards
# References
## Open Issues
- → Make V² Big Picture Slideshow work on Mobile #172 
- → Complete V²Plan on Home Page #103 
- → Visuals V² Home Page #2 
- → Draw Illustration: "V² Big Picture" aka "V² Puzzle" #38 
- → Timeline in Introduction #30 
- → Refactoring V² Home Page #123 
- → Define: Making contribution easy for anyone! #149 (One Feature in Introduction)
- → Full Review Home Page #17 
- → Better separation of Sections in Home Page #28 
- → Add Links on V²Home to Repositories #6 
- → Define: Making contribution easy for anyone! #149 
- → Draw V² Icons #171 
## Closed Issues but needed as Reference
- → V² Home Page #1 {March 7, darn we are at this for a long time!} still useful read
- → Write Introduction to V² (Features of V² Home Page) #23 
- → Closing V² Home Page #33
- →  Write Introduction to V² (Features of V² Home Page) #23 
- → Add Abstract to Home Page #10 
- → Add Footer to V² Home Page #26 
- → How the V² Home Page works #21
- → Add Jumbotron to V² Home Page #12 
- → The Big Picture of V² (Part of V² Home Page) #35 
- → Rewrite V² Home Page to fit "All pieces of the puzzle" Metaphor #20 aka Big Picture
- → Add "All pieces of the puzzle" #22 
- → Add Progress Batch to V²Home Page #8 
- → Redesign Portfolio Section of V² Home Page for Tabs #39 
- → Site Navigation Bar #36
