### ISSUE TITLE
Make 7 remaining Board Menu Items work

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#49]
- [ ] Start this after → #5 is complete, so we can benefit from that experience
- [ ] Tune → [v2-Site Repository](#issuecomment-218140984)
- [ ] Do → [Refactor Code in v2-Nav-Bar Repository](#issuecomment-218141168)
- [ ] Do → [Refactor in Plan and Organization](#issuecomment-218141409)
- [ ] HC: Do → [Tune Repos for  7 remaining Board Items](#issuecomment-218141844)
- [ ] Prepare 7 remaining repositories for Jekyll
- [ ] HC: Create → [7 Single Page Structure and Statements](#issuecomment-218142151)
- [ ] Publish the Nav-Bar System and Single Page as per above description
- [ ] HC: Test navigation

**Comment by VillageHubertChen** [comment]
# Tune v2-Site Repository

# Tasks
- [ ] Tune Repo [v2-Site](https://github.com/V-Squared/v2-Site), gh-pages only, Jekyll Git Ignore
  - [ ] Description: Powerful
- [ ] Add README.md
- [ ] Create LICENSE.md
- [ ] Create Demo

# Purpose
- One place for most updated code base of our Navigation Bar System
  - We will use it in several other web sites. Next Site Project: www.villagetronic.com
  - We need to copy it from here to each board repository for V²Site, which are 9 boards 
- Central place of improving code base and testing it. First improvement is to refactor the code so that the local repository copies load as much code as possible from this central location to minimize copy paste on code changes
- Focal point of community contribution to improve code base of v2-Nav-Bar
- Documentation for this Project

# Demo

## V²Site Demo Content is Documentation
- Same style as Joomla Template Documentation is presented by Template
- Full documentation to Users, Programmers and Maintainer

## Suggestions for Board Bar Items
- Features
  - Library Metaphor
  - 5 Level Navigation System
- Programmer's Guide
- Maintainer's Guide
- Versus CMS
- Contributing
- 5 Level Demo
- Use Cases

## Transcribe Articles ...
- from → [Compile Know How for Org►Contributing►V²Site](https://github.com/V-Squared/V-Squared.github.io/issues/48)

**Comment by VillageHubertChen** [comment]
# Refactor Code in v2-Nav-Bar Repository

for external JS & CSS

**Comment by VillageHubertChen** [comment]
# Refactor in Plan and Organization

**Comment by VillageHubertChen** [comment]
# Tune Repos for  7 remaining Board Items
- [ ] Create table first as per below tasks, then double check, then execute
- [ ] List repositories that already have 1:1 match
- [ ] Rename repositories that exist with right content but wrong name
- [ ] Create missing repositories
- [ ] Create gh-Pages Branch, Delete Master Branch, Set Git Ignore to Jekyll

**Comment by VillageHubertChen** [comment]
# 7 Single Page Structure and Statement
