### ISSUE TITLE
Restructure Plan & Org Repos to fit new V² Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#5]
- [ ] Restructure Plan
  - [x] Create → [Page Structure for V²►Plan](https://github.com/V-Squared/v2-Plan/issues/29)
  - [x] @LukasChen Initialize Repo for Jekyll
  - [x] Create all empty Articles according to → [Page Structure for V²►Organization](https://github.com/V-Squared/v2-Plan/issues/29)
  - [ ] Fill Articles with initial content
- [ ] Restructure Organization
  - [x] Create → [Page Structure for V²►Organization](https://github.com/V-Squared/v2-Organization/issues/2)
  - [ ] @LukasChen Initialize Repo for Jekyll
  - [ ] @LukasChen Create all empty Articles according to → [Page Structure for V²►Organization](https://github.com/V-Squared/v2-Organization/issues/2)
  - [ ] Fill Articles with initial content
# Reference
- [Page Structure for V²►Spreading](https://github.com/V-Squared/v2-Spreading/issues/19)
- [Page Structure for V²►Plan](https://github.com/V-Squared/v2-Plan/issues/29)
- [Page Structure for V²►Organization](https://github.com/V-Squared/v2-Organization/issues/2)
