### ISSUE TITLE
Epic►002►Article Front Matter and its Styling

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#50]
- [x] HC: Develop → [Proposed new Front Matter](#issuecomment-218359009)
- [x] HC: Write Specifications. Where needed develop specs together with LC.
- [x] Write Manual → [# How to Create a New Page](#issuecomment-218960578)
- [x] Implement → [Proposed new Front Matter](#issuecomment-218359009) in [Golden Page](http://v-squared.github.io/v2-Plan/system/)
- [x] Implement → [GitHub-Bar](#issuecomment-218717265)
- [x] Implement → [Article Jumbotron](#issuecomment-218729028)
- [x] HC Update Front Matter YAML in this Issue
- [x] HC: Change all Front Matter in all other Articles in V²Plan same way as in [Golden Page](http://v-squared.github.io/v2-Plan/system/)
- [x] Update book-bar.yaml definition in Issue►Navigation Bar System v3→ #47
- [x] Do → [New Progress Bar](#issuecomment-222288188)
# Reference
- Navigation Bar System v3→ #47

**Comment by VillageHubertChen** [comment]
# Proposed new Front Matter

## Golden Page
1. LC Implement in → [Golden Page](http://v-squared.github.io/v2-Plan/system/)
2. HC sign off → [Golden Page](http://v-squared.github.io/v2-Plan/system/)
3. HC changes all other pages following → [Golden Page](http://v-squared.github.io/v2-Plan/system/)

## New Front Matter

``` yaml
---
layout: page
title: {Article Title: Max. 30 char}
subtitle: {Article Subtitle: Max 100 Chars}
visualURL: {URL as used in browser URL bar}
abstract: {Short introduction what the Article is about. Max 300 Chars}
issueNo: {Number of Issue as it is listed in your-name.github.io repository}
readiness: {Values: 1...4, reflect the ready states: (1=Create, 2=Develop, 3=Beta, 4=Make)}
contents: {Table of Contents of the Article. Usually all H1. We use manual anchors}
  - name: {max 30 Chars}
    url: {short and specific. Example: "#dogfood"}
  - name:
    url:
---
```

## What has been removed
- **order:** now in YAML file by method of order in YAML file
- **menu:** now in YAML file
- **breadcrumbs:** now in YAML file, read from menu:
- **source:** This can be included in the corresponding GitHub Issue

## What I changed
- **description:** → "subtitle:"

## About using Manual Names & Anchors
- **Manual Names:** We need to shorten the names to 30 chars or less to fit in the side bar!
- **Manual Anchors:** Changing wording of heading will not break external links!

**Comment by VillageHubertChen** [comment]
# GitHub-Bar

## Implementation
- [x] HC: Draw Mock Up
- [x] Read values from Article Front Matter 
  - [x] Golden Reference Article → http://v-squared.github.io/v2-Plan/system/
  - [x] If not done yet, implement → [Proposed new Front Matter](#issuecomment-218359009)
- [x] Implement → [Readiness Indicator](#ref-ready)
- [x] Implement → [Styling](#ref-styling)
- [x] Implement → [Behavior](#ref-behavior)

## Readiness Indicator <a name="ref-ready"></a>
- Exact same function and design as Readiness Indicator in 9 Slides in V²Home Page
- Adjust size. Make text under squares small and gray. Kill it if it does not fit
- Same tooltips

## Styling <a name="ref-styling"></a>
- **Order of Items:**
  1. Readiness
  2. Edit this Article
  3. How to Edit this Article
  4. Issue of this Article
- **Placement:** Right side of Article, most top (above Contents-Bar)
- **Layout Style:** Same as Article-Bar, but with Icons
- **Icons:**
  - **Edit:** Edit Icon of Google Material Design
  - **Info:** Info Icon of Google Material Design (used for "How to Edit this Article")
  - **Issue:** Issue Icon of GitHub
  - Place Icons in front of text. See mock-up design 
- **Vertical Alignment:** Align all baselines of all Headings of: (Article-Bar | Article | Reference-Bar)
- **Stickiness:** Not sticky. Scrolling down the page scrolls the Reference-Bar out.
- **Colors:**
  - **normal:** #666
  - **indexed:** #000
  - **hover:** #666

## Behavior <a name="ref-behavior"></a>
- **No Stick:** As described above
- **Tooltips on Readiness:** As described above

**Comment by VillageHubertChen** [comment]
# Article Jumbotron

## Implementation
- [x] HC: Draw Mock Up
- [x] Read values from Article Front Matter 
  - [x] Golden Reference Article → http://v-squared.github.io/v2-Plan/system/
  - [x] If not done yet, implement → [Proposed new Front Matter](#issuecomment-218359009)
- [x] Implement → [Styling](#jumbo-styling)
- [x] Implement → [Edit Button](#jumbo-edit)
- [x] Implement → [Behavior](#jumbo-behavior)
- [x] Add V² to Bread Crumbs → V² > Plan > Road Map > Campaign 2 

## Styling <a name="jumbo-styling"></a>
- **Order of Items:**
  1. Box
  2. Article-Title
  3. Article-Visual
  4. Article-Subtitle
  5. Article-Breadcumbs (outside of Box, under Box, small font, grey)
- **Placement:** Top of Article.See Mock Up drawing.
- **Layout Style:** See Mock Up drawing.
- **Edit Icon:** 
  - Edit Icon of Google Material Design
  - Place Icon center on imaginary crossing of vertical right text border and jumbotron box bottom border. See mock-up design.
- **Vertical Alignment:** Align all baselines of all Headings of: (Article-Bar | Article-Title | Reference-Bar)
- **Stickiness:** Not sticky. Scrolling down the page scrolls the jumbotron out.
- **Colors:**
  - **background color:** Board Theme Color @ weight 100
  - **text color:**Board Theme Color @ weight 900
  - **Icon:** #f70 (accent color)
- **Image:** 
  - **Default size:** 360p → 640 x 360 Pixels in 16:9

## Edit Button <a name="jumbo-edit"></a>
- Styling is described above
- Link the button to the _githubURL:_ of Article _Front-Matter_

## Behavior <a name="jumbo-behavior"></a>
- **No Stick:** As described above
- **Tooltips on Readiness:** As described above
- **Edit button opens Article on GitHub <> Code

**Comment by VillageHubertChen** [comment]
# How to Create a New Page

## Step by step instructions

### Step 1: Title

Decide on a Title of the Article: E.g. "V² Plan System" (max 30 Char)

### Step 2. Menu

This is the name listed in the Menu Item: e.g. "System" (max 13 char in Book-Bar, max 26 char in Article-Bar). In this case we choose: "System".

### Step 3: File Name

Generated from Menu name. In this case: "system.md"

### Step 4: book-bar.yaml

Open the book-bar.yaml file:

``` Yaml
- menu: Target
  url: /target/
- menu: Road Map
  url: /road-map/
```

### Step 5:  Add the new file

(order in here determines order in menu)

``` Yaml
- menu: Target
  url: /target/
- menu: Road Map
  url: /road-map/
- menu: System
  url: /system/
```

### Step 6. Paste Front Matter Template

``` Yaml
layout: page
title: {Article Title: Max. 30 char}
subtitle: {Article Subtitle: Max 100 Chars}
visualURL: {image URL}
abstract: {Short introduction what the Article is about. Max 300 Chars}
issueNo: {Number of issue. E.g. "25"}
readiness: {Values: 1...4, reflect the ready states: (1=Create, 2=Develop, 3=Beta, 4=Make)}
contents: {Table of Contents of the Article. Usually all H1. We use manual anchors}
  - name: {max 30 Chars}
    url: {short and specific. Example: "#dogfood"}
  - name:
    url:
---
```

### Step 7: Fill in the blanks

``` Yaml
---
layout: page
title: V² Plan System
subtitle: How V² will improve your life, how we make it happen and how you can help. 
visualURL: https://cloud.githubusercontent.com/assets/7278716/14466638/3a39ff76-010a-11e6-803d-2822584a79b3.jpg
abstract: After reading this Article you have a complete overview to V²Plan and you will know what each Article is about so that you can focus your further reading on the topics you are interested in. The content will change with progress of development of V²Plan. In the beginning we focus more on guiding development whereas with ongoing completion focus will shift to user documentation. As with all V² projects the progress bar shows you how usable each article or feature is at this time. We started using V²Plan to manage ourselves right from the get go. In the best spirit of Eating your own dog food.
issueNo: 25
readiness: 2
contents: 
  - name: Introduction
    url: intro
  - name: Eating our own Dog Foot
    url: dog-foot
  - name: Methods
    url: methods
  - name: Cross Repo Management
    url: cross-repo
  - name: How it all fits together
    url: fits
---
```

### Step 8: Commit Article

Write a commit statement "Initial Post" and press button "Commit Changes"

### Step 9: Testing

Test the Article and its links

**Comment by VillageHubertChen** [comment]
# New Progress Bar

# Same function as before
- 4 Progress Steps: Create, Develop, Beta, Make
- 3 States per Step: no entry = grey, is-complete = blue, is-active = orange
- 1 Tooltip per step: We will keep using the same ones)

# New Styling
- Looks like Material Design
- Design Metaphor: Representing a progress bar
- Material Design Layers with shadows: 
  - Sticks out from under Book-Bar
  - Hovers over Article Card
- space efficient design
- it is possible that later the top of article card is the image. Thus it is good the new design is small.
