### ISSUE TITLE
Reassign Milestones

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#51]
- [x] Tune Milestone → [Campaign 1](https://v-squared.github.io/v2-Plan/road-map/campaign01/)
- [x] Tune Milestone → [Campaign 2](https://v-squared.github.io/v2-Plan/road-map/campaign02/)
- [x] Delete all M0 ... M06 milestones in corresponding repositories
- [x] Reassign Milestones in all relevant repositories to all issues, open and closed
- [ ] Create the new milestones in corresponding repositories
