### ISSUE TITLE
Proposed new Structure for Hosting V²Site

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#52]
## Tasks
- [x] Document new Structure
- [x] Discuss with SL
- [x] Discuss with LC
- [x] Come to conclusion → Agreed on Conclusion
- [x] Move all open Issues of v2-Plan to V-Squared.github.io
- [ ] Move all closed Issues of v2-Plan to V-Squared.github.io
- [ ] Move pages in v2-Plan wiki to V-Squared.github.io
- [ ] Check everything is empty
- [ ] delete repository
## Conclusion

We go for it due to significant benefits:
1. V²Site Graphs, Pulse, Issues and Pull requests will look much more active and attract more contributors
2. The new structure simplifies coding of Nav-Bar-System and thus saves time
3. It reduces time spend on weekly maintenance of V²Site (no redundancies any more to keep in sync)
4. V²Template as a project becomes more clean and attractive (no redundancies any more)
5. We must use branches and pull requests now. This will lift our GitHub statistics into the realm of big projects on GitHub.
## Terminology

This restructuring would shift some terms. I already wrote this document using the new terms:
- **V²Site:** Name for the web site of V². 
  - It is hosted in the v-squared.github.io and the URL is: http://v-squared.github.io/
- **V²Template: Name for Template System for GitHub Web Sites (formerly V²Site). 
## List of Repositories after restructure
- v-squared.github.io: Hosts entire web site (right now it only hosts V² Home Page)
- V²Template:
  - Template System for GitHub Web Sites with: Menu System, Articles, Blog, Ticket System, Forum, Shop
  - Code base for our template used in _v-squared.github.io_
- Special Repositories on Projects
  - v2-Panel
  - v2-Surge
  - v2-Configurator
  - ...
## Development of V²Template

In place development of our template in v-squared.github.io repository. This speeds up development and testing. In case we have early users of our template it is still straight forward to extract the template files for their projects. We can document this easy enough. 
## Benefits
- Focusing all activities into one repository
  - Make our work look much bigger and more active. Important to get more contributors.
- No redundant Code for Navigation Bar System 
  - (big problem otherwise that would be fixed with this new structure) 
- Saves time to set up 9 repositories for 9 boards
- Saves time to maintain the web site every month, as there is no redundancy of code
- We can use GitHub Branching and Merging to develop and test new content
## Disadvantages
- More complicated filters to get to an Issue Group. More labels.
- We need to consolidate existing Repositories
## Why did we started differently ?
- It was intuitive to have one Repository / Project
  - This is what everybody else did
- Issues are automatically grouped per project
- We used Wiki Pages for initial documentation
  - Wiki pages required one repository / project to manage complex structures
- _Project Development_ in different _Repositories_ are automatically isolated from one another
## Why do we no longer need different repositories?
- V²Site Articles replaces Wikis. V²Site Articles can handle very complex structures in one repository.
- We have learned to filter Issues.
  - big projects (boostrap and others) show that > 10,000 issues in one repository is no problem
- Navigation of V²Site is actually easier than navigating _Repositories_ in GitHub
- We learned to isolate development in different _Projects_ by means of _Feature Branches_

**Comment by LukasChen** [comment]
Great. This is solving the big problem of redundant code! :tada: :+1:

**Comment by VillageHubertChen** [comment]
Feedback Sascha:

Agreed. Sascha suggested to go one step further and to have in place development of our template in v-squared.github.io repository. This speeds up development and testing. In case we have early users of our template it is still straight forward to extract the template files for their projects. We can document this easy enough. I updated above description in response to Sascha's feedback.
