### ISSUE TITLE
Epic > 017 > Parent: V² Plan Create

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#53]
- [x] Write Description
- [x] Finish →  Rendering all Images for V²Plan Board and Slide #102 
- [x] Write → Discussion on True North and Targets → below
- [ ] Finish →  Reassign Milestones #51 
- [ ] Finish →  Quick & Dirty V²Art #87 
- [ ] Finish →  Complete V²Plan on Home Page #103 
- [ ] Finish →  Add all Jumbotron Images to V²Plan Articles → #104 
- [ ] Finish all top level Articles: 
  - [x] Intro
  - [x] True North
  - [x] Road Map
  - [x] Dashboard
  - [ ] Contributing
  - [ ] Agile
  - [ ] Flow
## Targets
- Slide of Plan in Home Page is finished
- Footer of Plan in Home Page is finished
- All top level pages in V²Plan are finished
- I can make a presentation using V²Plan to demonstrate: 
  - True North
  - 1 Year Target
  - 3 month Target
  - 1 month Target
## Discussion on True North and Targets
- I moved Targets to each Campaign
- A visual overview should be given in the Road Map
- As such I propose to Rename Target to True North and focus on True North only. Paint a really beautiful picture (with visuals) on how the future will look like with V². Possibly structure it by interests:
  - Modular PC
  - Docking Stations for PC
  - Docking Stations for Industrial
  - Docking Stations for Mobile
## Reference
- Hackathon V² Home Page → #41
