### ISSUE TITLE
V² > Plan > Agile > Intro

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#54]
# Tasks Stage 1
- [x] Create → [List of Articles](#issuecomment-219596479)
- [x] Create → [Titles, Subtitles, Abstracts](#issuecomment-219599960) and possible ToC
- [x] Create → [Structure for each Article](#issuecomment-219974521)
- [x] Create → [Renaming List for already existing Articles](#issuecomment-220025146)
- [x] Create corresponding Issues to Articles
- [x] LukasChen [Create V² Plan Articles](#issuecomment-220025493) with all above information and cross links
- [x] Fix → [Special Situation of this Article](#issuecomment-221237562)
- [x] Create Grouping → [Grouping V²Plan System Articles](#issuecomment-225423662)
  - [x] Implement via →  Add Article-Group to Navigation #153 
- [x] Manually Created Intro Page](#issuecomment-225911270)
- [ ] Add Title Graphics
# Tasks Stage 2
- Create → [Automatically generated Introduction Page](#issuecomment-220031676)
# Reference
- [V² > Plan > Agile > Intro](https://v-squared.github.io/plan/agile/)

**Comment by VillageHubertChen** [comment]
# List of Articles

| # | G | Title | Menu | File Name | i # |
| :-: | :-: | :-: | :-: | :-: | :-: |
| 1 | 1 | Introduction to V²Plan System | Intro | system.md | 59 |
| 2 | 1 | V²Agile Workflow on GitHub | V²Agile Workflow | agile-workflow.md | 60 |
| 3 | 1 | V²Sprint Workflow on GitHub | V²Sprint Workflow | sprint-workflow.md | 61 |
| 4 | 1 | Roles & Communication | Roles & Communication | roles.md | 62 |
| 5 | 1 | Iterations & Testing | Iterations & Testing | iterations.md | 63 |
| 6 | 1 | Solving today's Problems | Solving Problems | solving-problems.md | 64 |
| 7 | 1 | Features of V²Plan | Features of V²Plan | features.md | 65 |
| 8 | 5 | Video Tutorials V²Plan | Video Tutorials V²Plan | videos.md | 66 |
| 9 | 1 | Agile Development Primer | Agile Primer | agile-primer.md | 67 |
| 10 | 3 | Toyota Production Primer | Toyota Production Primer | toyota-primer.md | 68 |
| 11 | 1 | Motivation by Design | Motivation by Design | motivation.md | 69 |
| 12 | 1 | Multi Repo Management | Multi Repo Management | multi-repo.md | 70 |
| 12 | 1 | Adding SCRUM to GitHub | Adding SCRUM | adding-scrum.md | 71 |
| 13 | 1 | Adding Dashboard to GitHub | Adding Dashboard | dashboard.md | 72 |
| 14 | 2 | Adding Gantt to GitHub | Adding Gantt | adding-gantt.md | 73 |
| 15 | 4 | Adding Workload to GitHub | Adding Workload | workload.md | 74 |
| 16 | 1 | V² Plan Reference | V² Plan Reference | reference.md | 75 |
| 17 | 1 | Developing V²Plan | Developing V²Plan | developing.md | 76 |
| 19 | 1 | Adapting V²Plan | Adapting V²Plan | adapting.md | 77 |

# Articles Published in First Stage

We only create Articles that we intent to finish writing in th

| # | Title | Notes |
| :-: | :-: | :-: |
| 0- | Intro | Assorted list of Content of Article Series |
| 1- | Solving today's Problems | Renamed from Problems of the Past. Need to be rewritten to reflect the new title and abstract. Our problems from the past are maybe a chapter in the end? |
| 2 | Adding SCRUM to GitHub | 1) Evaluating 3rd Party Tools |
| 3 | Adding Dashboard to GitHub | 1) Focusing Development Team 2) Keeping Overview on Cross Repo Development 3) Updating Stake Holders |
| 3- | Agile Development Primer | Compile writing from → [tutorialspoint](http://www.tutorialspoint.com/agile/index.htm). Use Illustrations I already made. Remember to move Roles and Communications to separate Article as per below list entry |
| 4- | V²Agile Workflow on GitHub | Fill out writing as per Illustration and template writing already present |
| 5- | V²Sprint Workflow on GitHub | Use Illustration I already mad. Write as per Article above |
| 6 | Roles & Communication | as per → [tutorialspoint](http://www.tutorialspoint.com/agile/index.htm) |
| 7 | Testing |  |
| 8- | V² Plan Reference | 1) Sort out into other Articles which no longer belongs here 2) Reorganize 3) Add table for Labels 4) Add Waffle Integration |
| 9 | Features of V²Plan | Every time I am working on a Feature not listed yet then list it here |
| 10 | Developing V²Plan |  |
| 11 | Motivation by Design |  |
| 12 | Multi Repo Management |  |
| 13 | Adapting V²Plan |  |

**Comment by VillageHubertChen** [comment]
# Titles, Subtitles, Abstracts

!!! Now transferred → https://v-squared.github.io/plan/agile/ !!!
- **h1:** Title
- **h2:** Subtitle
- **p:** Abstract

---

# Introduction to V²Plan System

### Linked Listing of all Articles with Titles, Info-graphics and Abstracts.

After reading this Article you have a complete overview to V²Plan and you will know what each Article is about so that you can focus your further reading on the topics you are interested in. The content will change with progress of development of V²Plan. In the beginning we focus more on guiding development whereas with ongoing completion focus will shift to user documentation. As with all V² projects the progress bar shows you how usable each article or feature is at this time. We started using V²Plan to manage ourselves right from the get go. In the best spirit of [Eating your own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food). 

**Tip:** In the best spirit of Agile Development that puts experience over documentation you can dive straight into V²Plan with the four _Getting Started_ Articles: → V²Agile Workflow on GitHub, → V²Sprint Workflow on GitHub, → Roles & Communication, → Testing.

# V²Agile Workflow on GitHub

### Getting Started 1: All Steps from Vision to Ideas through Sprint Development to Product Release

Agile development requires the repeated precise execution of specific workflows. V²Plan tools are designed to guide and assist in executing these workflows. This Article first shows the _Overview Agile Workflow_ from beginning to end. Then you can zoom into each step of the overview which is a complete workflow in on itself. Each workflow is documented with three methods: **1)** User Stories, **2)** Step by Step Text Tutorial, **3)** Video Tutorial. Interactive Info-graphics assist in the learning process. Whereas the → _Agile Development Primer_ focus on the principles of Agile Development, these workflows focus on their implementation in daily work.

# V²Sprint Workflow on GitHub

### Getting Started 2: Workflow during a Sprint. Integration with GitHub Issues and Waffles.

The Sprint Workflow is at the core of the Agile Workflow as such we give it this dedicated  Article. This Article works just the same as the previous: It first shows the Overview Sprint Workflow from beginning to end. Then you can zoom into each step of the overview which is a complete workflow in on itself. Each workflow is documented with three methods: **1)** User Stories, **2)** Step by Step Text Tutorial, **3)** Video Tutorial. Interactive Info-graphics assist in the learning process.

# Roles & Communication

### Getting Started 3: Who is doing what, when and why. How to let whom know and when.

Definition of each Role in the Agile Development System. What are responsibilities and activities of each Role. How to communicate between each role using the tools of the V²Plan System so that communication is transparent. Thanks to the V²Plan System some of the communication even automatically becomes documentation, saving your time.

# Testing

### Getting Started 4: How to frequently test, integrate and release a Shipable Product Increment.

Testing, integration and shipping need to be very efficient when you have to release the product once a week. Naturally solutions will be very specific to your type of product and development tools. Our products are Know How Articles and Web Applications. This Article shows how we solved the practical problems for us, how our Workflow looks like and what tools we are using.

# Solving today's Problems

### How V² Plan solves the Problems of managing Agile Development and Production on GitHub.

V²Plan is for Organizations that have their Repositories on GitHub and who are looking for a better way to manage their Development and Production. V²Plan is an Open Source Zero Cost Solution. It utilizes the capabilities of _GitHub Issues_ to its full extent and then adds the missing tools, such as Cross Repository Management, SCRUM Boards, Gantt Charts and True North.

# Features of V²Plan

### Key Features and Specs of V²Plan.

**If you are evaluating V²Plan** this list of features shall quickly show you what V²Plan can and can not do. **While developing V²Plan** this is one of our guides what to develop. The availability of Features is listed → _V²Plan Development_. User Stories are in → _V²Agile Workflow on GitHub_ and → _V²Sprint Workflow on GitHub_.

# Video Tutorials V²Plan

### One Video Tutorial per Workflow

When completed this Article will be a a structured and illustrated assembly of all V²Plan Instruction Videos. Until then we record any idea that we want to show in the Videos here.

# Agile Development Primer

### How Incremental and Rapid Develop works and its benefits.

Complete Introduction Article on how _Agile Development_ works and what are the benefits versus the _Traditional Waterfall Development_. The key idea and key benefit is to produce a _Shippable Product Increment_ aka _Iteration_ in a very short time, such as one week. This makes for a very fast _Return of Investment_ as well as very fast _Customer Feedback_. We excluded any V²Plan specific information so that those already knowledgeable on Agile Development can safely skip this Article. 

# Toyota Production Primer

### How Incremental and Rapid Production works, its benefits and V²Plan's Implementation.

_Agile Development_ is based on the principles of the _Toyota Production System_ aka _TPS_. Understanding its principles makes the difference between making _Agile Development_ really work for you versus only going through the motions yet not achieving faster speed and higher quality. The Toyota Production System is also the logical choice for a company who develops Software using the Agile Method and also manufactures computer hardware. We apply TPS for the production of: Computer Cases, Printed Circuit Board Assemblies and Cables.
- http://blog.jdriven.com/2012/10/the-lean-agile-connection/
- http://the-agile-pmo.org/?p=54
- https://en.wikipedia.org/wiki/Toyota_Production_System
- http://www.toyota-global.com/company/vision_philosophy/toyota_production_system/
- http://www.toyota-global.com/company/vision_philosophy/toyota_production_system/illustration_of_the_toyota_production_system.html ← 

# Motivation by Design

### How to keep your Developer and your Community happy.

Motivation of both developer and community is essential to fast development of high quality products in demand. In turn: Fast development of high quality products is very motivating to developer and the community. This article shows how this relationship is at the core of all principles of Agile Development System. Understanding these principles will help you to always keep a high level of motivation.

Notes to the Author: We chose Waffle because it can show the SCRUM Board to anyone without requiring to install a browser plugin. We plan to show to boards in the Repository Menu: 1) Scrum Board of all that is going on. 2) Scrum Board of this V²Board only. If all Issues are in v-squared.github.io they are filtered out by current milestone. Current milestone is given in the URL and would need to be updated with a milestone change. As such this step would need to go into instructions on what to do when switching milestones.

# Multi Repo Management

### How to manage an Organization on GitHub with many Repositories.

Some Organizations need to manage more than one Repository which are closely interrelated between each other. V²Plan provides the strategy to achieve this target with as little effort as possible and adds the missing tools. In this Article we also show links to our Implementation with our Real World Data so that you can see how Multi Repo Management looks like in V²Plan: What information are given at your fingertips, how things are cross linked and how you quickly can navigate these cross links.

# Adding SCRUM to GitHub

### Complete How to Add SCRUM to GitHub Tutorial and Primer

All you want to know in one Article: 1) What software tools GitHub is missing when using it for Agile SCRUM 2) What third Party tools are available and which one is best for you 3) Installation, Configuration and Integration 4) Usage and Workflow Example

# Adding Dashboard to GitHub

### How to focus your development team and how to update your stake holders on progress

1) Focusing Development Team 2) Keeping Overview on Cross Repo Development 3) Updating Stake Holders 4) Creating and archiving history of work done.

# Adding Gantt to GitHub

### Complete How to Add Gantt Charts to GitHub Tutorial and Primer

All you want to know in one Article: 1) When Gantt Charts make a Difference 2) What third party tools are available 3) Installation, Configuration and Integration 4) Usage and Workflow Example

# Adding Workload to GitHub

### Complete How to Add Workload Estimates to GitHub Tutorial and Primer

How to solve the problems on: 1) Creating accurate estimates on required time to complete an issue. 2) Balance workload on developers 3) Complete a Sprint on time.

# V² Plan Reference

### Architecture, Data Structure, Tools, Visualization and Navigation of V²Plan. Mapping of V²Plan to Agile Development.

The Reference Manual to V²Plan serves two purposes: **1)** The theoretical look behind the scenes shows the Architecture of V²Plan with occasional goodies such as an explanation why we made particular choices. This background information will help you to better remember the V²Agile Workflows. **2)** A place to quickly look up information. 

# Developing V²Plan

### What Features are already working, which features are planned and how you can help

The core features of V²Plan are ready by June 2016 so that we can manage ourselves using V²Plan in the best spirit of [Eating your own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food). This Article gives an overview which features are available when. It also shows our development approach and our current development focus. This is also the place to read up on how to contribute or how to make suggestions or to report bugs.

# Adapting V²Plan

### Tutorials an how to introduce and adapt V²Plan to your GitHub Organization.

A three step procedure to install and configure V²Plan on your GitHub Organization: **1)** Overview of what is involved in terms of time, technology and cost. **2)** Table of all Parameters you want to adjust. **3)** Step by step Tutorials on how to install and configure V²Plan.

**Comment by VillageHubertChen** [comment]
# Structure for each Article

## Jumbotron
- Background Color 300 of Board Color
- Title + Info Graphics + Sub Title + Abstract

## Bread Crumb
- Under Jumbotron
- It is the Logical Path to the Article

## Info Graphics

It is placed in Jumbotron, however here I explain more of its features
- Each Heading 1 Section of the Article is represented with an Icon in the Info-graphics
- Each Icon has a Call Out Number
- Each Call Out Number has a Tooltip with more detail information to it
  - The text of the Tooltip is the abstract for each Heading 1 Section
  - At the end of the Tooltip text is a link "→ more" that links to the corresponding section
  - Each Heading 1 Section is numbered, corresponding to the call out number
- Each Article has only one Info Graphics. If it were to need more, split the Article
- Each Info-graphics is also used in the Introduction Article

## Article Section
- Numbered, identical to corresponding Call Out Number in Info-graphics
- Heading 1
- Abstract: Identical to Tooltip in Info-graphics
- Idea on Info-graphics: 
  - Focus circle with full contrast on where we are in the Info-graphics
  - rest of Info-graphics is only 50% contrast and brightness
- Regular writing explaining the topic of this section

# Benefits of this Structure
- Navigation will repeat Info-graphics, which helps the reader to feel he is not loosing the path
- Lots of Info-graphics will help to memorize the content much better
- Introduction Article allows both for fast scanning as well as intensive reading, due to use of Info-graphics with Tool-Tips and Abstract, both of which need to be revealed by reader, which is his choice of scanning or intensive reading.
- Each Article has the exact same structure. So the reader needs no brainpower to figure out the structure of each Article and can use all his brain power on understanding the content of the Article.

**Comment by VillageHubertChen** [comment]
# Renaming List for already existing Articles
- system.md → system.md
- agile-philosophy → agile-primer.md
- agile-workflow.md → agile-workflow.md
- plan-reference.md → reference.md
- problems.md → solving-problems.md
- sprint-workflow.md → sprint-workflow.md
- [ ] for the files no need to rename you still need to check if you may need to rename the title in the YAML Front Matter. For sure you will have to add the abstract and update the front matter for the new attributes.

**Comment by VillageHubertChen** [comment]
# Create V² Plan Articles
1. all Articles are in the /system/ folder
2. [Rename the existing Articles](#issuecomment-220025146) first
3. Add the → [Titles, Subtitles and Abstracts](#issuecomment-219599960)
4. Create the remaining Articles of First Stage onlye → [List of Articles](#issuecomment-219596479) !!! First Stage is in second table. Total only 14 Articles instead of 19!!!
5. Add Issue Numbers → [Titles, Subtitles and Abstracts](#issuecomment-219599960)

**Comment by VillageHubertChen** [comment]
# Automatically generated Introduction Page
- [x] LC, HC: Write specs
- [ ] Implement as per specs, then trigger HC to review

## Hot Edit

We added grouping of Articles. Read grouping and Article order from YML file.

## Overview
- the content of body the system.md page will be automatically generated
- LC will code an include template, that is included with markdown in system.md
- we will give it as parameter the book-bar.yml file with pointer to system folder
- All content is pulled out of YML front matter of the articles
- the include-template will then generate the page as described below:

## Content
- Title
- Info Graphics 
- Subtitle
- Abstract
- Link to Article

**Comment by VillageHubertChen** [comment]
# Jekyll Template for Introduction Page

**Comment by VillageHubertChen** [comment]
# Change Introduction Page to Kramdown

**Comment by VillageHubertChen** [comment]
# Special Situation of this Article
- This  Article started as "Introduction to V²Plan System".
- When developing further the Article series we changed that the Introduction is an Assorted list of all Jumbotrons of all V²PLan System Articles
- [x] Sort the existing content into corresponding articles of this Article series

**Comment by VillageHubertChen** [comment]
# Grouping V²Plan System Articles
- Getting Started
  - V²Agile Workflow on GitHub
  - V²Sprint Workflow on GitHub
  - Roles & Communication
  - Testing.
- Fundamentals
  - Agile Development Primer
  - Toyota Production Primer
  - Motivation by Design
- Developing / Evaluating
  - Solving today's Problems
  - Multi Repo Management
  - Adding SCRUM to GitHub
  - Adding Dashboard to GitHu
  - Developing V²Plan
  - Adapting V²Plan
- Reference
  - Features of V²Plan  
  - V² Plan Reference

**Comment by VillageHubertChen** [comment]
# Manually Created Intro Page
- [x] Create an Overview Page from content of → - [x] Create → [Titles, Subtitles, Abstracts](#issuecomment-219599960)
- [x] Create ToC
- [x] Create Read More links
- [x] Test
- [x] Trigger BC & TC for Beta-Review
- [ ] Trigger LC to style
- [ ] Implement feedback
- [ ] Check styling

**Comment by VillageHubertChen** [comment]
# Beta-Review

@bcaswelch , @tcaswelch 

Please review / edit this article. The content and structure has already undergone a major edit from GI, so hopefully all what is left for you is to fix my German-English.

All feedback is welcome. After this Beta Review this Article will be set to "Make".

**Comment by VillageHubertChen** [comment]
# Styling

@LukasChen 

Originally we wanted you to generate this Article automatically from front matter content of each Article. But you were sick and I wanted to make progress. Can you still style this Article as in Markdown? Remember the original ideas to use cards? At this time we will not have yet title graphics available for each article. However, can you make it so that clicking on a card brings you to the article?

**Comment by VillageHubertChen** [comment]
# Beta-Review

@georgillies 
Please review / edit this article. 
1. Does the sum of abstracts cover all ground you would want to see covered?
2. How is the grouping of the articles?
3. How is the order of the articles?
4. Is each abstract in on itself self explanatory?
5. How is the flow of all abstracts when reading from top to bottom in one sitting?

All feedback is welcome. After this Beta Review this Article will be set to "Make".
