### ISSUE TITLE
Add Dashboard to V²Flow FAB Menu 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#58]
# Tasks
- [x] HC: Write User Story
- [x] Add Dash Board Icon in form of: 3 vertical Bars (see ZenHub)
- [x] link to Waffle Board
- [x] Rename "Board" to "Dashboard"
- [x] change link to → [Dashboard](https://v-squared.github.io/plan/dashboard/)
- [x] HC: Add snapshots and links to both boards in Dashboard
# User Story
## New V² Reader

As a **new reader** to V² I found the Dashboard feature in the V²Flow button very useful. One click brought me to the dashboard. It was clearly structured and I could study the progress in the last sprints as well as see the work on the up to date scrum boards.
## V²Contributor

As a **V²Contributor** I have to go to the dashboard each time I complete an issue and am looking for the next thing to do. Putting the dashboard into the V²Flow menu is a very logical place that is more convenient than finding it in my bookmarks folder. It is a tiny feature but makes using the V²Site just a little bit smoother. Having all management pages compiled in the V²Flow menu is also easing the learning curve for new contributors.
