### ISSUE TITLE
Add Links on V²Home to Repositories

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#6]
# Link Types
- GitHub (mandatory, link to the repository on V²GitHub)
- Website (optional, in case the repository has a gh-pages branch)
- App (optional, in case there is a working app in the gh-pages)
# Hero Page
- http://square.github.io/
# Dependencies
- #5 need to be completed first
# Tasks
- [x] HC: Write initial card
- [x] @LukasChen Add three link types to HTML / JSON
- [x] @LukasChen Add all the links in JSON file. Test on Home Page all works. Trigger HC for final review
- [ ] @HC Final review and closing of card
