### ISSUE TITLE
Epic►006►Parent: V²►Plan►System►V² Plan Reference

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#75]
# Generic Tasks
- [x] Create Issue
- [ ] Create Article with basic content as per → [Article►Introduction to V²Plan System](https://github.com/V-Squared/V-Squared.github.io/issues/54)
- [x] Link Issue to Article
- [x] Link Article to Issue in Reference
- [ ] Collect any writing Materials from other places to here
- [ ] Develop rough outline and some writing in here
- [ ] Transfer writing to Article
- [ ] Set Progress to "Develop"
- [ ] Completely develop Article and ToC (in Article)
- [ ] Transfer ToC to Front Matter and test it.
- [ ] Develop description Info-graphics of Article (in Issue)
- [ ] Develop Tooltip simulation for Infographics with links Sections of Article (in Article)
- [ ] Review by at least one reader. Reader suggests improvements in comments to this Issue
- [ ] Implement suggestions by reviewer
- [ ] Create Info-graphics Illustration. Upload to V²Art.
- [ ] Add Info-graphics to Article. Add Tooltips. Test tooltips and their links.
- [ ] Set Progress to "Beta"
- [ ] Trigger reviews. Suggestions are made in comments to this issue.
- [ ] Implement reviews
- [ ] Set Progress to "Make"
# Specific Tasks
- [x] HC: Get feedback from SL → Completely rewritten after feedback
- [x] HC: Find a FOSS Gantt Chart plugin written in Angular reading its data from Angular
- [x] HC: Initial evaluation of https://waffle.io → Adds boards to GitHub Management. Works like Trello Boards, but with GitHub integration. For us it will be zero cost.
- [x] HC: Create initial Waffle Board → https://waffle.io/V-Squared/V-Squared.github.io Was easy and straight forward. Assign to column using GitHub Issues Label
- [x] LC: Create a repository "Plan". Prepare it for Jekyll. Cross link it with V² Home Page. 
- [x] Added Labels Section
- [ ] Create Table → When to assign what label
# Reference
- [V²►Plan►System►Reference](https://v-squared.github.io/v2-Plan/system/reference/)
