### ISSUE TITLE
Add Progress Batch to V²Home Page

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#8]
# User Story

As a **new Reader of the V² Home Page** I was originally put off that most of the places I navigated to were not very developed and almost wanted to abandon V². But now after the introduction of _Progress Batches_ I get it: This is an Open Source repository for the Community to both create and to look up Know How. If I am in the business of looking up Know How, I know that I will find little when the progress batch says "Incubating". And the more the progress batch moves to the right, the more Know How in the better presentation I can expect. Now browsing the Home Page does not make me frustrated anymore. Thanks guys!
# Illustrating Progress
### Development Progress

This is intuitive and it's inside what it says on the label. Since years we stage development internally into 4 stages: 1) Incubation, 2) Development, 3) Beta Testing 4) Production. Actually we have a fifths stage, which is 5) Archived. But at the time of publishing V² to the public as a new Standard Organization it is not the right moment to talk about archiving standards when we have not even published our first one.
### Move to GitHub Progress

This is was not so intuitive at first. Lets look at an example problem: ViCase. Development is complete and it is already in production. Yet on GitHub you can see nothing yet, because all work is still done on the internal server. By adding the "Move to GitHub" Progress Badge we can make two statements:
- **Development:** In Production
- **Move to GitHub:** Development is currently happening off GitHub. It will be moved to V² GitHub soon.

So even the visitor can't see anything yet, he gets the idea that soon he can see a lot, as all that need to be done is moving the content from one server to the other.
## Color and Shape Codes

We minimized the user of color and shapes. Each remaining color and shape have a coded meaning. This makes it easier for the visitor to scan the page and to get an overview of Development and Move Progress.
### Progress Bar under the Project Poster

This is very common and intuitive.
### Move to GitHub Progress as Corner Ribbon

It has become a habit to place a "Fork on GitHub" Ribbon in the top right corner, Ribbon Color in GitHub Green. Our design shows the "Move to GitHub" status in the same way.
# Staged "Move to GitHub" Progress
## Four Stages of "Move to GitHub"
1. **Off:** Development is currently happening off GitHub. It will be moved to V² GitHub soon.
2. **Next:** This project is next in line to be moved to a V² GitHub repository.
3. **Hot:** We are moving this project right now to V² GitHub!
4. **On:** This project is on our V² GitHub.
## Design as CSS Corner Ribbon

![Example Corner Ribbon](http://www.technicalkeeda.com/img/images/article/css-ribbon-example.png)
- https://css-tricks.com/snippets/css/corner-ribbon/
- http://www.cssportal.com/css-ribbon-generator/
- http://www.technicalkeeda.com/html/how-to-add-badge-corner-ribbon-using-css
- Each Corner Ribbon gets its Ribbon Name, see list above
- Each Corner Ribbon Name gets its Tooltip, see list above
## Colors
1. **Off:** (Gray)
2. **Next:** (Tangerine)
3. **Hot:** (Hot)
4. **On:** (Green)
## Tooltips
- Tooltips with uikit
- Content as per list above
## JSON
- **Name:** Move-Stage
- **Values:** "1", "2", "3", "4"
# Staged Development Progress
## Four Stages of Development with Tooltips
1.  **Incubating:** Creating the Concept and Specs while getting Community's feedback. Cast your Vote or propose a Feature.
2.  **Developing:** Making it happen. If we already moved it to GitHub you can join by Opening Issues with Enhancement Requests or by assiging yourself to Issues in search for an owner or simply Fork, Improve and make a Pull Request.
3.  **Beta:** Beta Testing. Fine tuning Functionality with Pre-Production Units. Get involved and provide enhancement requests. 
4.  **Production:** Enjoy! It is ready to use. Let us know your praise or file a bug report in GitHub Issues.
## We shortened the Stage Names

| New Stage Name | Old Stage Name (on previous server) |
| :-: | :-: |
| Create | Incubation |
| Develop | Developing |
| Beta | Beta |
| Make | Production |
## Design as Stacked Progress Bar
- uikit has a Stacked Progress Bar. It is not documented. It works like the one Bootstrap, see below
  - http://getbootstrap.com/components/#progress-stacked
- http://getuikit.com/docs/customizer.html
- Each Segment gets its Segment Name, see list above
- Each Segment Name gets its Tooltip, see list above
## Colors
- It is a progress bar, so all segments are the same color
- Progress Bar Color is V² Theme color (blue)
- Progress Bar background is light grey
## Tooltips
- Tooltips with uikit
- Content as per list above
## JSON
- **Name:** Devel-Stage
- **Value:** "0 ... 100" (to indicate percentage completed of progress bar)
# Reference
- [V² Home Page](http://v-squared.github.io)
# Tasks
- [x] HC: Write User Story to have kick of meeting with LC
- [x] LC: Develop rapid prototype. Show HC what is possible with uikit / bootstrap
- [x] HC: Write detailed spec with color theme
- [x] HC: Find example implementation in Open Source, put links into Article
- [x] LC: Implementation. Trigger HC for review. Tune until review passed.
- [x] LC: Implement JSON
- [x] LC: Add Ribbon
- [x] HC: Add status information into JSON file. Final review. Close this issue.

**Comment by VillageHubertChen** [comment]
# Find shorter Words for:
- Incubating
- Developing
- Beta
- Production

# Shorter Words for Stages:
- Create
- Develop
- Beta
- Make

# Tasks
- [x] Find shorter words
- [x] Test if they are short enough

**Comment by VillageHubertChen** [comment]
# New Progress Bar Implementation
- Show stages numbered in circles: 1, 2, 3, 4
- Each stage has two stages: "Active" = Tangerine ; "Completed" = V² Blue
- Illustration more demonstrates accomplishment of stages
  ![](https://s-media-cache-ak0.pinimg.com/736x/f0/22/65/f022655c809d341285d73909a04091d5.jpg)
- http://codepen.io/villagelukaschen/pen/reMZaN

# Tasks
- [x] HC spell out better solution and find hero
- [x] @LukasChen Implement

**Comment by VillageHubertChen** [comment]
Yeah! :tada:
