### ISSUE TITLE
Epic > 016 > Parent: V²Art Create

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#87]
@VillageHubertChen commented on [Tue Apr 12 2016](https://github.com/V-Squared/v2-Plan/issues/22)
- [x] Write V²Art Article in Classeur and Stack Edit
- [x] Create V²Art Create Milestone and assign to issue
- [ ] Find final place of Article 
  - new idea → V² > Plan > Flow > Art
  - old idea → [ Page Structure for V²►Spreading #19 ](https://github.com/V-Squared/v2-Spreading/issues/19)
- [ ] Collect all V²Art Articles. Publish in above place as markdown files.
- [ ] Create a V²Art Introduction article with links to all other files
- [ ] Write → [Workflow on Creating Visuals for Articles](#issuecomment-225493742)
  - [ ] Announce this Article to BC and TC to use it when illustrating DIY Articles
- [ ] Finish the Article on Folder Structure
- [ ] Backup my MySQL data base
- [ ] Install Windows GitHub Client or SmartGit ?
- [ ] Set up workflow
- [ ] Convert the Portfolio Images ML already made. Upload to V²Art and add to V²Home Page
- [ ] Create missing images and host in V²Art using file structure as per above article
- [ ] Link images in V²Plan and V² Home Page

![milestones](https://cloud.githubusercontent.com/assets/7278716/14466638/3a39ff76-010a-11e6-803d-2822584a79b3.jpg)

**Comment by VillageHubertChen** [comment]
# Workflow on Creating Visuals for Articles
- Create Code / Text based visual place holders
- scour internet to find place holder graphics that come close to description in text place holders
- process internet images to size / ratio and insert into article
- read article with visuals. See how it flows. Make changes to flow / visuals if needed
- create in Article Issue to do list for custom visuals
- create custom visuals as per V²Art work flow

# References
- Method of illustration Lego blocks on white background used in assembling new images
- Description of Lego Capabilities in 3D design
- Phoenix CI + V² Stick Men CI
