### ISSUE TITLE
Restructure Marketing Repository

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#9]
# Purpose
- Build the first working Repository + Site Twin. Get experience for all others
- Build first round trip experience from V² Home Page to V² Section and back. Experience how clean is building? How consistent is user experience?
- Extract Articles from Issues
  - Can we get a better authoring experience?
  - We need Articles in Code section of GitHub to use GitHub Flow for contribution!
  - Can we isolate function: 1) Issues to move Article forward 2) Article to present know how
  - Are Articles easy to find / navigate in final web site presentation?
  - Can we make it easy to toggle back and forth between site view and repository view?
# Folder Structure we need

```
gh-pages Branch of Marketing Repository
 ├ _pages (authoring pages of site)
 │   ├ promotions
 │   │   ├ index.md
 │   │   ├ promo-page-1.md
 │   │   ├ promo-page-2.md
 │   ├ shops
 │   │   ├ listings
 │   │   │   ├ index.md
 │   │   │   ├ shop-1.md
 │   │   │   ├ shop-2.md
 │   │   ├ creating
 │   │   │   ├ index.md
 │   │   │   ├ create-shop-page-1.md
 │   │   │   ├ create-shop-page-2.md
 │   │   │   ├ create-shop-page-3.md
 │   ├ milestones
 │   │   ├ index.md
 ├ _posts (authoring pages of blog)
 ├ _site (web site generated by Jekyll)
 ├ index.html
```
# Folder Structure Jekyll needs

Please look up → [Jekyll►Directory Structure](https://jekyllrb.com/docs/structure/)
# Tasks
- [x] HC & LC: Create Folder structure of our files in Marketing
- [x] HC: Rename Online Shop Repository to Marketing Repository
- [x] LC: Initialize Jekyll and create all its folders in Marketing Repository
- [ ] HC: Create the folder structure and files as per above
- [ ] HC: Extract Articles that are finished from Issues → _pages folder & Rewrite Issue Header.
- [ ] LC: Generate Marketing Site, then demo to HC. Improve based on feedback. Repeat until OK.
- [x] LC: Add marketing link to navigation bar in home page
- [x] LC: Design nav bar in marketing, so you can do round trip
- [x] LC: Design nav bar in marketing, so you can navigate all pages in marketing

**Comment by VillageHubertChen** [comment]
# Moved this Issue to:
1. → [Page Structure for V²►Spreading](https://github.com/V-Squared/v2-Spreading/issues/19)
2. → [Extract Articles from Issues](https://github.com/V-Squared/v2-Spreading/issues/20)
