### ISSUE TITLE
V² > Plan > Index

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#91]
# Tasks (Stage 1)
- [x] HC: Get feedback from SL → Completely rewritten after feedback
- [x] HC: Find a FOSS Gantt Chart plugin written in Angular reading its data from Angular
- [x] HC: Initial evaluation of https://waffle.io → Adds boards to GitHub Management. Works like Trello Boards, but with GitHub integration. For us it will be zero cost.
- [x] HC: Create initial Waffle Board → https://waffle.io/V-Squared/V-Squared.github.io Was easy and straight forward. Assign to column using GitHub Issues Label
- [x] HC: Get feedback from GI → All makes sense. Visualization charts are great. Simulating how contributors and people who evaluate V² would react is congruent with outlined targets. 
- [x] HC: Rewrite Plan in V² Home Page to reflect new terminology
- [x] HC: Complete this Article
- [x] LC: Create a repository "Plan". Prepare it for Jekyll. Cross link it with V² Home Page. 
- [x] HC: Rewrite according to → [GI's feedback](#issuecomment-225850192)
# Ideas for Future
- [Ideas for Future](#issuecomment-222348581)
# Tasks (Stage 2)
- → [Tasks (Stage 2)](#issuecomment-225851580)
# Reference
- [V² Plan Introduction](https://v-squared.github.io/plan/)
# Issue was moved

HC moved → [Thu Apr 07 2016](https://github.com/V-Squared/v2-Plan/issues/2)

@VillageHubertChen commented on [Sat May 07 2016](https://github.com/V-Squared/v2-Plan/issues/2#issuecomment-217646098)

**Comment by VillageHubertChen** [comment]
# Ideas for Future

## Movie on how to edit

Record a simple screen recording of complete steps on how to edit and Article and put it into the section "Simple and Fast"

**Comment by VillageHubertChen** [comment]
# GI's feedback
- Purpose and Motivation are similar. Rewrite it to be more compact.
- Georg and Sascha both felt uncomfortable I wrote about what makes motivation happen. They simply want it to magically happen but feel manipulated if we make a design effort to cause motivation.

**Comment by VillageHubertChen** [comment]
# Tasks (Stage 2)
- [x] Change Contribution Page to Flow Page
- [x] Rewrite Chapter: Key Elements of V²Plan
- [x] Add Chapter: Next Campaigns
- [x] Add Chapter: V²Flow Simple and Fast Contribution
- [x] Rewrite → V²Agile is the engine of V²Plan
- [x] Add → ToC
- [x] Update links to pages with changed URL
- [x] Trigger BC & TC for Beta Text Review
- [ ] Trigger LC to → Add Amazing Visuals → below

# Add Amazing Visuals

## Key Elements of V²Plan
- 2 row 3 columns Tile Slide Show, same style as in Big Picture Slide Show in Home Page 
- actually many tiles can be used 1:1
- Coding is exactly the same
- to be implemented once the Home Page is refactored to Kramdown
- All functions of slide show with readiness bar, GitHub Badge, hover over text, links, etc ...

## Next Campaigns
- Same as Key Elements above
- The 3 Tiles are already finished in Big Picture Slide Show in Home Page

**Comment by VillageHubertChen** [comment]
# Beta Text Review

@bcaswelch , @tcaswelch 
- [ ] Please review the structure and flow of text and comment about it. Good or bad.
- [ ] Please edit my German English to nice English

**Comment by georgillies** [comment]
- New Board Slogan is good
- I realy like the new V²Flow conept
- Page structure: Logical
- Key Elements comes to the point. Good intro. I like the idea to reuse the tiles from the slide show
- Next Campaigns: Make sense. Good intro to get work done.
- V²Flow Simple and Fast Contribution: OK
- V²Agile is the engine of V²Plan: Concise and complete

**Comment by VillageHubertChen** [comment]
@georgillies 

Thanks for the review. It is a very nice feeling to pass a review with no change request :-) Good to know it is all on the right track.

**Comment by VillageHubertChen** [comment]
# Tasks (Stage 3)
- [x] Create new Intro Page and move content of this page to there
- [x] Rename this page to Index
- [x] Code automatic index card generation → #189 
- [x] Skype review with GI
- [x] Implement GI's feedback
