### ISSUE TITLE
Plan►Dashboard

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#94]
# Tasks
- [x] Create Article
- [x] Create Issue and link Issue to Article
- [x] Link Article to Issue
- [x] Set Labels, Milestone, Assignee
- [x] Update to new Front Matter
- [x] Add Weekly Sprints
- [x] Add Images with links to Scrum Boards
- [x] Improve Abstract
- [x] Write content
- [x] Add ToC to Front Matter
- [x] Create the Title Graphics
- [x] Bump Readiness to Core-Beta
- [x] Add Feature: All Issues closed this week
- [x] Added several sprints to look ahead in planning
- [x] Added Statistics on completed sprint
- [ ] Process the Graphics and add to Jumbotron
# Improvements for later
- After the V²Plan System / V²Agile Articles are more complete, rewrite the copy of the _Dashboard_ so to add links to the corresponding articles. This makes it easy to look up Agile and Sprint related know how for those not familiar with it.
# Reference
- [V²►Plan►Dashboard](https://v-squared.github.io/v2-Plan/dashboard/)

**Comment by VillageHubertChen** [comment]
# Adding Snaps for Scrum Boards

## V-Squared

![scrum-board-v-squared](https://cloud.githubusercontent.com/assets/7278716/15988570/568b6f40-3088-11e6-8bd9-e9405bbc453f.png)

## Production

![scrum-board-production](https://cloud.githubusercontent.com/assets/7278716/15988587/1b82a2dc-3089-11e6-8d9c-10c44b94914c.png)
