### ISSUE TITLE
V²►Plan►Road Map►Intro

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#95]
# Tasks of Original Issue

→ [Thu Apr 07 2016](https://github.com/V-Squared/v2-Plan/issues/8)
- [x] Create Road Map Article in Wiki → [v2 Road Map](https://github.com/V-Squared/v2-Plan/wiki/v2-Road-Map)
- [x] Rewrite Road Map from M01, M02, ... style which has cross repository milestones to the new style which contains each milestone to only one repository
- [x] Move Road Map on Wiki → [V²►Plan►Road Map](http://v-squared.github.io/v2-Plan/road-map/)
- [x] Cross link to old Road Map
- [x] Transfer all important data from old to new Road Map
- [ ] Create and Add the Info Graphics of "Where it fits in" as per → [Feedback Georg](https://github.com/V-Squared/v-squared.github.io/issues/100#issuecomment-226433498)
- [ ] Create SVG of Road Map with Tooltips
- [ ] Adopt SVG drawing for Home Page
# New Tasks
- [x] Create Article
- [x] Find old issue in V²Plan on this topic and move to here → [Thu Apr 07 2016](https://github.com/V-Squared/v2-Plan/issues/8)
- [x] Set Labels, Milestone, Assignee
- [x] Update Article to new Front Matter
- [x] Split this Article into Index and Intro
- [ ] Add Chapter Road Map Overview
  - 2011-2021 Road Map (SVG + Tooltips + Paragraph)
  - Next 2 Years Road Map (SVG + Tooltips + Paragraph)
- [ ] Add ToC to Front Matter
- [ ] Add Title Graphics
# Reference
- [V² > Plan > Road Map > How it Works](https://v-squared.github.io/plan/road-map/)
- [Road Map 2016 ... 2018 v1](https://github.com/V-Squared/v2-Marketing/issues/11) Previous Version in Spreading Marketing / Repository. Not yet adopted to new V²Plan Structure.
- [Milestones v4](https://github.com/V-Squared/v2-Marketing/issues/10) Previous Versions of Campaigns

**Comment by VillageHubertChen** [comment]
# Text Review

@bcaswelch @tcaswelch 

I have completely overhauled this Introduction to V² Road Map. I made too many changes to be efficient to list here. 
- [ ] Please read the Article and give feedback on structure & flow
- [ ] If you are satisfied with structure and flow then go ahead and edit my German English to Real English. 
- [ ] If you are not satisfied with the structure and flow then write me a change list and I will rewrite the article accordingly.

**Comment by georgillies** [comment]
# Text Review Georg
- Jumbotron: OK
- Table of Contents: OK
- Where Road Map fits in: OK
- How Road Map Works: OK
- Compact List of Campaigns: All in all OK. I really like it.
  - Typo: Schrinking
- Detailed List of Campaigns
  - 1: Change: "via Article Issues" to "V² Flow Button"
  - 2-3: Shorten it
  - 3: Last sentence does not flow
  - 3-4: typo: onine, typo: V²Case Mini to V²Case Small
  - 5: highlight: High End Gaming consumer market
  - 5-6: Same highlighting as above
  - 6: typo: different
  - 7-8: typo in end: V²Case. to ViCase 
    - Lift copyright in Campaign 9 after V²Dock provides income
- overall: This all makes sense, it flows well.

**Comment by VillageHubertChen** [comment]
@georgillies 

I included all your feedback. Thanks for your review!
