### ISSUE TITLE
V²►Plan►Road Map►Strategy

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#96]
- [x] Create Article
- [x] Create Issue and link Issue to Article
- [x] Link Article to Issue
- [x] Set Labels, Milestone, Assignee
- [x] Update Article to new Front Matter
- [x] Change Content to be about Strategy to be about Strategic Road Map, that is covering 10 Years from 2011 to 2021. A second Road Map to cover the next two years.
- [x] Add ToC to Front Matter
- [x] Set readiness
- [x] Trigger Structure Review BC, TC
- [x] Include feedback BC, TC
- [x] Change structure to reflect new Title: Road Map > 2011-2021
- [ ] Write content
- [ ] Add Title Graphics
# Reference
- [V² > Plan > V² Road Map > Strategic](https://v-squared.github.io/plan/road-map/strategic/)

**Comment by VillageHubertChen** [comment]
# Structure Review

@bcaswelch & @tcaswelch 
- [x] Please check out Title, Subtitle and Abstract. How does it make sense in context?
- [x] Please check the Article Bar. How does each item make sens in context?

**Comment by bcaswelch** [comment]
Looks good, I would add a smaller timeline to the road map. People want to know whats going to happen in the near future, consumers aren't very happy looking far into the future.

**Comment by VillageHubertChen** [comment]
@bcaswelch Thank you. Added Next 3 Months.

**Comment by bcaswelch** [comment]
@VillageHubertChen 

Great!
