### ISSUE TITLE
V²►Plan►Road Map►Campaign 1

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#97]
# Tasks from old Issue

→ [Thu Apr 07 2016](https://github.com/V-Squared/v2-Plan/issues/9)
- [x] Create New Milestones for Campaign
- [x] Review new Campaigns by GI → Passed
- [x] Write description for Campaign 1, reformat to table
- [x] Write description for Campaign 2, reformat to table
- [x] Move to Wiki Article → [v2 Campaigns](https://github.com/V-Squared/v2-Plan/wiki/v2-Campaigns)
- [x] Move Wiki Article → [V²►Plan►Campaign 1](http://v-squared.github.io/v2-Plan/roadMap/campaign01/)
  - [x] Split 3 Campaigns into 3 Articles
- [x] Create → Page Structure for V²►Plan►Road Map → #29 
- [x] I changed the label. I need to modify filter in URL to milestones in table
- [x] Implement the Milestone V²Plan Start of Campaign 1 as per new Method
- [x] Double check structure, that each Milestone only has issues of the same repository
- [x] Create Waffle boards for V² all issues and for Production
  - https://waffle.io/V-Squared/V-Squared.github.io
  - https://waffle.io/V-Squared/v2-Production
# New Tasks
- [x] Create Article
- [x] Create Issue and link Issue to Article
- [x] Link Article to Issue
- [x] Find old issue in V²Plan on this topic and move to here → [Thu Apr 07 2016](https://github.com/V-Squared/v2-Plan/issues/9)
- [x] Set Labels, Milestone, Assignee
- [x] Update Article to new Front Matter
- [x] Add Milestone: "GitHub.V-Squared.Create"
- [x] Restructure Article to show three chapters:
  1. Campaign Target
  2. Milestones to reach Target
  3. Campaign Progress
- [x] Add ToC
- [x] Rename Milestones so the URL does not contain special characters translated to %xy 
- [x] Write Abstract (Moved into Article in this case due to better reading flow)
- [x] Double Check Milestone in Campaign
- [x] Create Milestones in V-Squared.github.io repository and assign milestones it issues
- [x] Link Milestones in Table to Milestones in Issues
- [x] remove Milestone M01 ... M06 from repository V-Squared.github.io
# Major Update 1

on [Sun May 08 2016](https://github.com/V-Squared/v2-Plan/issues/9#issuecomment-217688061)
- [x] Move Wiki Article → [V²►Plan►Campaign 1](http://v-squared.github.io/v2-Plan/roadMap/campaign01/)
  - [x] Split 3 Campaigns into 3 Articles
- [x] Create → Page Structure for V²►Plan►Road Map → #29 
# Major Update 2 <a name="major-update-2"></a>
- [x] Add → ToC to Front Matter
- [x] Add → Target of Campaign 1
- [x] Add → Preparing for Campaign 2
- [x] Add → Campaign Progress
- [x] Add → Where Campaign fits in
- [x] Trigger BC & TC for Text Review
- [x] Include Review Feedback
# Reference

→ [V²►Plan►Road Map►Campaign 1](https://v-squared.github.io/plan/road-map/campaign01/)

**Comment by VillageHubertChen** [comment]
# Add Campaign Progress

![progress-milestones](https://cloud.githubusercontent.com/assets/7278716/15971227/b75cfed4-2f6a-11e6-827b-dfeb1e688762.png)

**Comment by bcaswelch** [comment]
Looks great! Love the status bars. Will make things much clearer :)

**Comment by VillageHubertChen** [comment]
Wow. You put a smile on my face. :-)  I worked on it last night. Very tedious job. I am glad you noticed and likes it. It is part of my effort to make V²Plan very easy to understand. If you have any ideas to this end, please post them in the comment :-)

**Comment by bcaswelch** [comment]
Definitely will. Using as many visual cues will not only make it look less like an engineering document but make ti easier for people to read and comprehend. I'll be thinking of other ways to possibly update other efforts.

**Comment by VillageHubertChen** [comment]
@bcaswelch Great and thank you! I strongly feel the same. I know from experience that writing with good related visuals will reach 1000% more audience than text alone. 

This is why V²Art Workflow is very high on my list. Take as example the DIY Articles. They have great content. But after we moved them from Wiki to Pages they appear so much more appealing. Next step will be to create the Illustrations to the Articles and they will get another bump on the attractiveness scale.

Question:
- Would it make sense to put V²Art under V²Flow?
- Path: V²Plan > V²Flow > V²Art
- V²Flow would have then the following workflows
  - V²Article
  - V²Art
  - V²E-Design
  - V²M-Design
  - V²Production
  - V²App
  - V²Site
- We would focus now on V²Article and V²Art. Both we need urgently to complete the Articles, which is highest priority gating item to start community sales, besides having ViCase Sample.

**Comment by VillageHubertChen** [comment]
# Text Review

@bcaswelch @tcaswelch 

## Please answer within one working day

I just noticed you have not answered my above question since 3 days. This is frustrating. In this case asking questions is actually wasting my time, since I do not get a Return of Investment from it. After 3 days I have long moved over that point.

## This Text Review
- [ ] Please check all upgrades made according to → [Major Update 2](#major-update-2)
- [ ] How is the flow
- [ ] How does → "Where Campaign fits in" work. Does it help you to understand where you are on each page?

**Comment by VillageHubertChen** [comment]
# Text Review

@georgillies 

## This Text Review
- [x] Please check all upgrades made according to → [Major Update 2](#major-update-2)
- [x] How is the flow
- [x] How does → "Where Campaign fits in" work. Does it help you to understand where you are on each page?

**Comment by georgillies** [comment]
Major Update 2 + Flow: Good!
"Where Campaign fits in": There is still no pyramid image. Together with such a sort of illustration it would be more helpful for the "newby".But even without that it makes sense.

**Comment by VillageHubertChen** [comment]
@georgillies 

Thanks for the review. The pyramid image is scheduled and will be coming. It will be just a bit until I can get to it.
