### ISSUE TITLE
V²►Plan►Road Map►Campaign 2

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#98]
# Tasks
- [x] Create Article
- [x] Create Issue and link Issue to Article
- [x] Link Article to Issue
- [x] Set Labels, Milestone, Assignee
- [x] Update Article to new Front Matter
- [x] Write Abstract
- [x] Double Check Milestones in Campaign
- [x] Remove any overlapping or missing milestones when compared to Campaign 1
- [x] @bcaswelch Intensive review with HC including brainstorming of changes
- [x] HC: Intensive rewrite based on Bobby's review
- [x] @bcaswelch New review of → [Intensive rewrite based on Bobby's review](#issuecomment-222982948)
  Please review ASAP. Once you OK it I want to create Milestones in the repository as I need it for further writing.
- [x] Break up the table and group them
  - Creating all Boards of V²
  - Shop
  - Marketing
- [x] Create Milestones in V-Squared.github.io repository and assign milestones to issues
- [x] Link Milestones in Table to Milestones in Issues
- [x] remove Milestone M01 ... M06 from repository V-Squared.github.io
- [x] Add ToC to Front Matter
- [x] Once this has been proven then back annotate Campaign 1 to be consistent
# Major Update 1 <a name="major-update-1"></a>
- [x] Add → ToC to Front Matter
- [x] Add → Target of Campaign 1
- [x] Add → Preparing for Campaign 2
- [x] Add → Campaign Progress
- [x] Add → Where Campaign fits in
- [x] Trigger BC & TC for Text Review
- [ ] Include Review Feedback
# Reference
- [V²►Plan►Road Map►Campaign 2](https://v-squared.github.io/v2-Plan/road-map/campaign02/)

**Comment by VillageHubertChen** [comment]
# Intensive rewrite based on Bobby's review

## Things I added as we discussed
- ViCase Promotion
- Previews ViCase
- Reviews ViCase

## Things I added different than we discussed

### New place for DIY Articles

I found that I made a big error: The DIY PC and Configuration PC Articles do not belong to the V²►Spreading►Know-How section. They belong to V²DIY, which is a dedicated board for these Articles. The error will be obvious after reading the [For DIY Slide in Home Page](https://v-squared.github.io/#/tab1-4)

### Creating all Boards now

After I almost placed the DIY articles into the wrong board I want to go ahead and create all boards now. They can be minimum number of pages, but enough to achieve two things:
1. Once we start promoting the V²Site every board has enough content so that the site does not look unfinished
2. If I happen to come across or get inspired on the right content I will then have the final resting place to put it down
3. Creating all boards now will engrave in my brain what goes where so to not make another mistake again to place content into the wrong board

### Tuned ViCase Promotion Milestone

Sascha was really sensitive to ensure we are not misunderstood to run a crowd funding campaign. So this is the new wording: "Create a campaign page in the same format as a crowd funding project. ViCase Promotion is having all crowd funding benefits without their risks"

## General tune up

I tuned most of the milestone description. I optimized ordering. Kicked some milestone in and others out.

## Added Prefix to Milestones

We are going to have lots of Milestones. So I added prefixes to the milestones to group them into campaigns in the drop down menu. This will make finding the right milestone a bit faster.

## Added Hyphens

This will recognizing a _Milestone_ within copy faster.

## Added Object Notation
- **.Create:** Part of our Create, Develop, Beta, Make notation.
- **.R1:** Production Run number. Will continue: R2, R3, ..
- **QA.ViPC:** Other will be QA.ViCase, etc ...
- **More:** → [V²►Plan►Road Map►Campaign 2](http://v-squared.github.io/v2-Plan/road-map/campaign02/)

## Changed ViCase-Mini to ViCase.Mini

Benefits:
1. More consistent to the writing style that we are developing. I am using more and more onject notation with great success on V²
2. Logically it makes sense. Mini is a variation that inherits lots of its parents features.
   - ViCase.Tiny
   - ViCase.Mini
   - ViCase.Small
3. Object notation is still a modern thing. As such using it will make us appear more modern.

This is not to be mistaken to replace spaces with dots in a term. Where there is no object logic we will continue to use the hyphen.

**Comment by bcaswelch** [comment]
R&U, I'm OK with all of the new changes to the campaign. At some point in the future lets talk about the blog, its going to be MUCH easier talking to the community through social media they already use like Facebook and Twitter than it will be trying to convince people to use yet another online blog.

**Comment by VillageHubertChen** [comment]
1. Thanks for the review. Going to implement it now
2. Future use of the Blog and Social Media: I totally agree your comment and this is actually our current strategy of using social media: We blog everything in our blog. We will categorize each post. We will classify each social media to have a focus. According to content of the blog post we will re-post it on the matching social media
3. Our blog is a focal point for us. We do not require others to read it. Some may. Our blog will offer better search engine support and classifications, so when people are researching on a topic a post on our blog may rank hire than on say twitter.

**Comment by bcaswelch** [comment]
Ok, this makes a lot of sense. Using both hand in hand won't bring any negatives and if people decide of read ours, good for us :)

In full support of this decision.

**Comment by VillageHubertChen** [comment]
Thanks for your feedback. That's what we were thinking. We will make it so.

P.S. Jekyll's key purpose is blogging. It is supposed to have tools to help automate re-blogging. We will look into this once we get there ...

**Comment by VillageHubertChen** [comment]
# Text Review

@bcaswelch @tcaswelch 
- [x] Please check all upgrades made according to → [Major Update 1](#major-update-1)
- [x] How is the flow ?
- [x] How do "Based on Campaign 1" and "Preparing for Campaign 3" work to put Campaign 2 into context of the Road Map?

**Comment by VillageHubertChen** [comment]
# Text Review

@georgillies 
- [x] Please check all upgrades made according to → [Major Update 1](#major-update-1)
- [x] How is the flow ?
- [x] How do "Based on Campaign 1" and "Preparing for Campaign 3" work to put Campaign 2 into context of the Road Map?

**Comment by georgillies** [comment]
Major Update 1: 

Well done. Perhaps make clear what the difference between American customers (c2.v2-Shop ... launch the _V²Shop_) and Asian/European customers (c2.ViShop.Create ... launch the _ViShop_) is. 
In "Campain Progress" bottom line: "VSp_r_eading Start".

Flow: Reads well.

Context: I think this is fairly clear.

**Comment by VillageHubertChen** [comment]
@georgillies Thanks for the review. I included your changes.
