### ISSUE TITLE
V²►Plan►Road Map►Campaign 3

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#99]
# New Tasks
- [x] Create Article
- [x] Create Issue and link Issue to Article
- [x] Link Article to Issue
- [x] Set Labels, Milestone, Assignee
- [x] Update Article to new Front Matter
- [ ] Write Abstract
- [ ] Double Check Milestones in Campaign
- [ ] Create Milestones in V-Squared.github.io repository and assign milestones to issues
- [ ] Link Milestones in Table to Milestones in Issues
- [ ] Add Cross Links → [V²►Plan►Road Map►Campaign 3](https://github.com/V-Squared/v2-Plan/edit/gh-pages/road-map/campaign03.md) in Description of Milestone. If possible with anchor to milestone so that the page scrolls to that milestone in table.
- [ ] remove Milestone M01 ... M06 from repository V-Squared.github.io
- [ ] Add ToC to Front Matter
- [ ] Set label to "need-visual". Describe visual, then design and link it.
# Reference
- [V²►Plan►Road Map►Campaign 3](https://v-squared.github.io/v2-Plan/road-map/campaign03/)
